'''
* Script - M_S5_DPA_SUMMARIZE_FACT_EMS_SMS_APLY_TYPE_TXN.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_S5_DPA_SUMMARIZE_FACT_EMS_SMS_APLY_TYPE_TXN mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_S5_DPA_SUMMARIZE_FACT_EMS_SMS_APLY_TYPE_TXN")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_S5_DPA_SUMMARIZE_FACT_EMS_SMS_APLY_TYPE_TXN", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "DPA")

    v_snsh_date = ""
    v_rpt_mth = ""
    # Load mapping variables from the UTL_JOB_PARAM file (shared helper)
    _vars = lib.load_mapping_variables(config, [ "$$v_snsh_date",  "$$v_rpt_mth", ], logger)
    v_snsh_date = _vars.get("v_snsh_date", v_snsh_date)
    v_rpt_mth = _vars.get("v_rpt_mth", v_rpt_mth)
    
    try:
        logger.info("Step: apply_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1")
        # Source Qualifier: apply_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1
        # SQL Pushdown - executes Informatica SQ SQL on source database
        _conn = lib.get_db_config(config, "SOR")
        query = f"""SELECT DESP_DTL_DMNS_KEY, TIME_DMNS_KEY, 
   SUM(TXN_CNT), MAX(LAST_REC_TXN_DATE)
FROM DPA_FACT_EMS_SMS_APLY_TYPE_TXN dpa, DDS_DMNS_EMS_APLY_TYPE aply
WHERE APLY_TYPE_CODE = 'PRH'
AND dpa.APLY_TYPE_DMNS_KEY = aply.APLY_TYPE_DMNS_KEY
GROUP BY DESP_DTL_DMNS_KEY, TIME_DMNS_KEY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1 = lib.read_sql(spark, _conn, query=query)
        df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1 = lib.sq_output(
            input_df=df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1,
            port_cols={
                'DESP_DTL_DMNS_KEY': 'decimal',
                'TIME_DMNS_KEY': 'decimal',
                'TXN_CNT': 'decimal',
                'LAST_REC_TXN_DATE': 'date/time',
            },
        )
        ctx.register_df("df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1", df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1)
        
        logger.info("Step: apply_SQ_SOR_3")
        # Source Qualifier: apply_SQ_SOR_3
        # SQL Pushdown - executes Informatica SQ SQL on source database
        _conn = lib.get_db_config(config, "SOR")
        # Parameterize schema from connection config
        _schema = _conn.get("schema", "") or "psor"
        query = f"""select aply_sts.SCHM_CODE, cep_sts.GF_CERT_TYPE_CODE
from SOR_EMS_SMS_LN ln, SOR_EMS_SMS_LN_STS ln_sts,
SOR_EMS_SMS_LN_APLY aply, SOR_EMS_SMS_LN_APLY_STS aply_sts,
SOR_EMS_SMS_CEP_CERT cert, SOR_EMS_SMS_CEP_CERT_STS cert_sts,
SOR_EMS_SMS_CEP_APLY cep, SOR_EMS_SMS_CEP_APLY_STS cep_sts
where
ln.LN_KEY = ln_sts.LN_KEY
and aply.LN_APLY_KEY = aply_sts.LN_APLY_KEY
and cert.CEP_CERT_KEY = cert_sts.CEP_CERT_KEY
and cep.CEP_APLY_KEY = cep_sts.CEP_APLY_KEY
and ln_sts.LN_APLY_KEY = aply.LN_APLY_KEY
and aply_sts.CEP_CERT_KEY = cert.CEP_CERT_KEY
and cert_sts.CEP_APLY_KEY = cep.CEP_APLY_KEY
and ln_sts.LN_STS_CODE in ('V','S') and cep_sts.GF_CERT_TYPE_CODE is not null
and trunc(ln_sts.ln_iss_date, 'MM') = to_date('$$v_rpt_mth','YYYYMM')
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  ln_sts.BGN_DATE AND  ln_sts.END_DATE
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  aply_sts.BGN_DATE AND  aply_sts.END_DATE
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  cert_sts.BGN_DATE AND  cert_sts.END_DATE
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  cep_sts.BGN_DATE AND  cep_sts.END_DATE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_SQ_SOR_3 = lib.read_sql(spark, _conn, query=query)
        df_SQ_SOR_3 = lib.sq_output(
            input_df=df_SQ_SOR_3,
            port_cols={
                'SCHM_CODE': 'string',
                'GF_CERT_TYPE_CODE': 'string',
            },
        )
        ctx.register_df("df_SQ_SOR_3", df_SQ_SOR_3)
        
        logger.info("Step: apply_SQ_SOR_2")
        # Source Qualifier: apply_SQ_SOR_2
        # SQL Pushdown - executes Informatica SQ SQL on source database
        _conn = lib.get_db_config(config, "SOR")
        # Parameterize schema from connection config
        _schema = _conn.get("schema", "") or "psor"
        query = f"""select aply_sts.SCHM_CODE, 'INT'
from SOR_EMS_SMS_LN ln, SOR_EMS_SMS_LN_STS ln_sts,
SOR_EMS_SMS_LN_APLY aply, SOR_EMS_SMS_LN_APLY_STS aply_sts,
SOR_EMS_SMS_CEP_CERT cert, SOR_EMS_SMS_CEP_CERT_STS cert_sts,
SOR_EMS_SMS_CEP_APLY cep, SOR_EMS_SMS_CEP_APLY_STS cep_sts
where
ln.LN_KEY = ln_sts.LN_KEY
and aply.LN_APLY_KEY = aply_sts.LN_APLY_KEY
and cert.CEP_CERT_KEY = cert_sts.CEP_CERT_KEY
and cep.CEP_APLY_KEY = cep_sts.CEP_APLY_KEY
and ln_sts.LN_APLY_KEY = aply.LN_APLY_KEY
and aply_sts.CEP_CERT_KEY = cert.CEP_CERT_KEY
and cert_sts.CEP_APLY_KEY = cep.CEP_APLY_KEY
and ln_sts.LN_STS_CODE in ('V','S') and UNIT_CODE_ADDR is not null
and substr(UNIT_CODE_ADDR, 1, 2) = 'E9'  
and trunc(ln_sts.LN_ISS_DATE, 'MM') = to_date('$$v_rpt_mth','YYYYMM')
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  ln_sts.BGN_DATE AND  ln_sts.END_DATE
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  aply_sts.BGN_DATE AND  aply_sts.END_DATE
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  cert_sts.BGN_DATE AND  cert_sts.END_DATE
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  cep_sts.BGN_DATE AND  cep_sts.END_DATE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_SQ_SOR_2 = lib.read_sql(spark, _conn, query=query)
        df_SQ_SOR_2 = lib.sq_output(
            input_df=df_SQ_SOR_2,
            port_cols={
                'SCHM_CODE': 'string',
                'APLY_TYPE_CODE': 'string',
            },
        )
        ctx.register_df("df_SQ_SOR_2", df_SQ_SOR_2)
        
        logger.info("Step: apply_SQ_SOR_1")
        # Source Qualifier: apply_SQ_SOR_1
        # SQL Pushdown - executes Informatica SQ SQL on source database
        _conn = lib.get_db_config(config, "SOR")
        # Parameterize schema from connection config
        _schema = _conn.get("schema", "") or "psor"
        query = f"""select aply_sts.SCHM_CODE, substr(UNIT_CODE_ADDR, 1, 1)
from SOR_EMS_SMS_LN ln, SOR_EMS_SMS_LN_STS ln_sts,
SOR_EMS_SMS_LN_APLY aply, SOR_EMS_SMS_LN_APLY_STS aply_sts,
SOR_EMS_SMS_CEP_CERT cert, SOR_EMS_SMS_CEP_CERT_STS cert_sts,
SOR_EMS_SMS_CEP_APLY cep, SOR_EMS_SMS_CEP_APLY_STS cep_sts
where
ln.LN_KEY = ln_sts.LN_KEY
and aply.LN_APLY_KEY = aply_sts.LN_APLY_KEY
and cert.CEP_CERT_KEY = cert_sts.CEP_CERT_KEY
and cep.CEP_APLY_KEY = cep_sts.CEP_APLY_KEY
and ln_sts.LN_APLY_KEY = aply.LN_APLY_KEY
and aply_sts.CEP_CERT_KEY = cert.CEP_CERT_KEY
and cert_sts.CEP_APLY_KEY = cep.CEP_APLY_KEY
and ln_sts.LN_STS_CODE in ('V','S') and UNIT_CODE_ADDR is not null
and substr(UNIT_CODE_ADDR, 1, 2) <> 'E9' 
and trunc(ln_sts.LN_ISS_DATE, 'MM') = to_date('$$v_rpt_mth','YYYYMM')
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  ln_sts.BGN_DATE AND  ln_sts.END_DATE
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  aply_sts.BGN_DATE AND  aply_sts.END_DATE
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  cert_sts.BGN_DATE AND  cert_sts.END_DATE
AND TO_DATE('$$v_snsh_date', 'YYYYMMDD') BETWEEN  cep_sts.BGN_DATE AND  cep_sts.END_DATE
and substr(UNIT_CODE_ADDR, 1, 1) in ('E','C','R','L')"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_SQ_SOR_1 = lib.read_sql(spark, _conn, query=query)
        df_SQ_SOR_1 = lib.sq_output(
            input_df=df_SQ_SOR_1,
            port_cols={
                'SCHM_CODE': 'string',
                'UNIT_CODE_ADDR': 'string',
            },
        )
        ctx.register_df("df_SQ_SOR_1", df_SQ_SOR_1)
        
        logger.info("Step: apply_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN")
        # Source Qualifier: apply_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN
        # SQL Pushdown - executes Informatica SQ SQL on source database
        _conn = lib.get_db_config(config, "SOR")
        query = f"""SELECT APLY_TYPE_DMNS_KEY AS APLY_TYPE_DMNS_KEY, TIME_DMNS_KEY AS TIME_DMNS_KEY, 
   SUM(TXN_CNT) AS TXN_CNT, MAX(LAST_REC_TXN_DATE)
FROM DPA_FACT_EMS_SMS_APLY_TYPE_TXN dpa, DDS_DMNS_EMS_DESP_DTL dtl
WHERE DESP_DTL_CODE = 'no_of_tran_hos'
AND dpa.DESP_DTL_DMNS_KEY = dtl.DESP_DTL_DMNS_KEY
GROUP BY APLY_TYPE_DMNS_KEY, TIME_DMNS_KEY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN = lib.read_sql(spark, _conn, query=query)
        df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN = lib.sq_output(
            input_df=df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN,
            port_cols={
                'APLY_TYPE_DMNS_KEY': 'decimal',
                'TIME_DMNS_KEY': 'decimal',
                'TXN_CNT': 'decimal',
                'LAST_REC_TXN_DATE': 'date/time',
            },
        )
        ctx.register_df("df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN", df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN)
        
        logger.info("Step: read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13")
        # Reading Data From Source - read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        query = f"""SELECT DESP_DTL_DMNS_KEY AS DESP_DTL_DMNS_KEY, TIME_DMNS_KEY AS TIME_DMNS_KEY, 
   SUM(TXN_CNT) AS TXN_CNT, MAX(LAST_REC_TXN_DATE) AS LAST_REC_TXN_DATE 
FROM DPA_FACT_EMS_SMS_APLY_TYPE_TXN dpa, DDS_DMNS_EMS_APLY_TYPE aply
WHERE APLY_TYPE_CODE = 'INT'
AND dpa.APLY_TYPE_DMNS_KEY = aply.APLY_TYPE_DMNS_KEY
GROUP BY DESP_DTL_DMNS_KEY, TIME_DMNS_KEY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13 = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13")
        # Lookup: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13 = df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13.dropDuplicates(subset=["TIME_DMNS_KEY", "DESP_DTL_DMNS_KEY"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1
        _lkp_input = _lkp_input.withColumn("IN_DESP_DTL_DMNS_KEY", col("DESP_DTL_DMNS_KEY"))
        _lkp_input = _lkp_input.withColumn("IN_TIME_DMNS_KEY", col("TIME_DMNS_KEY"))
        # Join condition: IN_TIME_DMNS_KEY=TIME_DMNS_KEY AND IN_DESP_DTL_DMNS_KEY=DESP_DTL_DMNS_KEY
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1 = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13).alias("_lkp"),
            (col("_main.IN_TIME_DMNS_KEY") == col("_lkp.TIME_DMNS_KEY")) &
            (col("_main.IN_DESP_DTL_DMNS_KEY") == col("_lkp.DESP_DTL_DMNS_KEY")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13[c] for c in df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN13.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        ctx.register_df("df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1", df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1)        
        logger.info("Step: read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12")
        # Reading Data From Source - read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        query = f"""SELECT DESP_DTL_DMNS_KEY AS DESP_DTL_DMNS_KEY, TIME_DMNS_KEY AS TIME_DMNS_KEY, 
   SUM(TXN_CNT) AS TXN_CNT, MAX(LAST_REC_TXN_DATE) AS LAST_REC_TXN_DATE 
FROM DPA_FACT_EMS_SMS_APLY_TYPE_TXN dpa, DDS_DMNS_EMS_APLY_TYPE aply
WHERE APLY_TYPE_CODE = 'COT'
AND dpa.APLY_TYPE_DMNS_KEY = aply.APLY_TYPE_DMNS_KEY
GROUP BY DESP_DTL_DMNS_KEY, TIME_DMNS_KEY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12 = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12")
        # Lookup: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12 = df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12.dropDuplicates(subset=["TIME_DMNS_KEY", "DESP_DTL_DMNS_KEY"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1
        _lkp_input = _lkp_input.withColumn("IN_DESP_DTL_DMNS_KEY", col("DESP_DTL_DMNS_KEY"))
        _lkp_input = _lkp_input.withColumn("IN_TIME_DMNS_KEY", col("TIME_DMNS_KEY"))
        # Join condition: IN_TIME_DMNS_KEY=TIME_DMNS_KEY AND IN_DESP_DTL_DMNS_KEY=DESP_DTL_DMNS_KEY
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1 = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12).alias("_lkp"),
            (col("_main.IN_TIME_DMNS_KEY") == col("_lkp.TIME_DMNS_KEY")) &
            (col("_main.IN_DESP_DTL_DMNS_KEY") == col("_lkp.DESP_DTL_DMNS_KEY")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12[c] for c in df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN12.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11")
        # Reading Data From Source - read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        query = f"""SELECT DESP_DTL_DMNS_KEY AS DESP_DTL_DMNS_KEY, TIME_DMNS_KEY AS TIME_DMNS_KEY, 
   SUM(TXN_CNT) AS TXN_CNT, MAX(LAST_REC_TXN_DATE) AS LAST_REC_TXN_DATE 
FROM DPA_FACT_EMS_SMS_APLY_TYPE_TXN dpa, DDS_DMNS_EMS_APLY_TYPE aply
WHERE APLY_TYPE_CODE = 'THA'
AND dpa.APLY_TYPE_DMNS_KEY = aply.APLY_TYPE_DMNS_KEY
GROUP BY DESP_DTL_DMNS_KEY, TIME_DMNS_KEY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11 = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11")
        # Lookup: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11 = df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11.dropDuplicates(subset=["TIME_DMNS_KEY", "DESP_DTL_DMNS_KEY"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1
        _lkp_input = _lkp_input.withColumn("IN_DESP_DTL_DMNS_KEY", col("DESP_DTL_DMNS_KEY"))
        _lkp_input = _lkp_input.withColumn("IN_TIME_DMNS_KEY", col("TIME_DMNS_KEY"))
        # Join condition: IN_TIME_DMNS_KEY=TIME_DMNS_KEY AND IN_DESP_DTL_DMNS_KEY=DESP_DTL_DMNS_KEY
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1 = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11).alias("_lkp"),
            (col("_main.IN_TIME_DMNS_KEY") == col("_lkp.TIME_DMNS_KEY")) &
            (col("_main.IN_DESP_DTL_DMNS_KEY") == col("_lkp.DESP_DTL_DMNS_KEY")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11[c] for c in df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN11.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1")
        # Reading Data From Source - read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        query = f"""SELECT DESP_DTL_DMNS_KEY AS DESP_DTL_DMNS_KEY, TIME_DMNS_KEY AS TIME_DMNS_KEY, 
   SUM(TXN_CNT) AS TXN_CNT, MAX(LAST_REC_TXN_DATE) AS LAST_REC_TXN_DATE 
FROM DPA_FACT_EMS_SMS_APLY_TYPE_TXN dpa, DDS_DMNS_EMS_APLY_TYPE aply
WHERE APLY_TYPE_CODE = 'HSO'
AND dpa.APLY_TYPE_DMNS_KEY = aply.APLY_TYPE_DMNS_KEY
GROUP BY DESP_DTL_DMNS_KEY, TIME_DMNS_KEY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1 = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1")
        # Lookup: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1 = df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1.dropDuplicates(subset=["TIME_DMNS_KEY", "DESP_DTL_DMNS_KEY"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1
        _lkp_input = _lkp_input.withColumn("IN_DESP_DTL_DMNS_KEY", col("DESP_DTL_DMNS_KEY"))
        _lkp_input = _lkp_input.withColumn("IN_TIME_DMNS_KEY", col("TIME_DMNS_KEY"))
        # Join condition: IN_TIME_DMNS_KEY=TIME_DMNS_KEY AND IN_DESP_DTL_DMNS_KEY=DESP_DTL_DMNS_KEY
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1 = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1).alias("_lkp"),
            (col("_main.IN_TIME_DMNS_KEY") == col("_lkp.TIME_DMNS_KEY")) &
            (col("_main.IN_DESP_DTL_DMNS_KEY") == col("_lkp.DESP_DTL_DMNS_KEY")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1[c] for c in df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: apply_EXPTRANS1")
        # Expression: apply_EXPTRANS1
        df_EXPTRANS1 = lib.expression(
            input_df=df_SQ_SOR_1,
            computed_columns=[
                {'name': 'APLY_TYPE_CODE', 'expr': "CASE WHEN UNIT_CODE_ADDR = 'E' THEN 'PRH' WHEN UNIT_CODE_ADDR = 'C' THEN 'COT' WHEN UNIT_CODE_ADDR = 'R' THEN 'HSO' WHEN UNIT_CODE_ADDR = 'L' THEN 'THA' ELSE NULL END"}
            ],
        )
        ctx.register_df("df_EXPTRANS1", df_EXPTRANS1)
        
        logger.info("Step: read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN")
        # Reading Data From Source - read_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        query = f"""SELECT dpa.DESP_DTL_DMNS_KEY AS DESP_DTL_DMNS_KEY, APLY_TYPE_DMNS_KEY AS APLY_TYPE_DMNS_KEY, TIME_DMNS_KEY AS TIME_DMNS_KEY, 
   SUM(TXN_CNT) AS TXN_CNT, MAX(LAST_REC_TXN_DATE)
FROM DPA_FACT_EMS_SMS_APLY_TYPE_TXN dpa, DDS_DMNS_EMS_DESP_DTL dtl
WHERE DESP_DTL_CODE = 'no_of_tran_tps'
AND dpa.DESP_DTL_DMNS_KEY = dtl.DESP_DTL_DMNS_KEY
GROUP BY dpa.DESP_DTL_DMNS_KEY, APLY_TYPE_DMNS_KEY, TIME_DMNS_KEY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN")
        # Lookup: apply_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN = df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN.dropDuplicates(subset=["APLY_TYPE_DMNS_KEY", "TIME_DMNS_KEY"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN
        _lkp_input = _lkp_input.withColumn("IN_APLY_TYPE_DMNS_KEY", col("APLY_TYPE_DMNS_KEY"))
        _lkp_input = _lkp_input.withColumn("IN_TIME_DMNS_KEY", col("TIME_DMNS_KEY"))
        # Join condition: IN_APLY_TYPE_DMNS_KEY=APLY_TYPE_DMNS_KEY AND IN_TIME_DMNS_KEY=TIME_DMNS_KEY
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN).alias("_lkp"),
            (col("_main.IN_APLY_TYPE_DMNS_KEY") == col("_lkp.APLY_TYPE_DMNS_KEY")) &
            (col("_main.IN_TIME_DMNS_KEY") == col("_lkp.TIME_DMNS_KEY")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN[c] for c in df_LKP_DPA_FACT_EMS_SMS_APLY_TYPE_TXN.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        ctx.register_df("df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN", df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN)        
        logger.info("Step: apply_EXPTRANS3")
        # Expression: apply_EXPTRANS3
        df_EXPTRANS3 = lib.expression(
            input_df=df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN1,
            computed_columns=[
                {'name': 'APLY_TYPE_CODE', 'expr': "'ST'"},
                {'name': 'SCHM_CODE', 'expr': "'SMS'"},
                {'name': 'TXN_CNT_V', 'expr': 'CASE WHEN (TXN_CNT IS NULL) THEN 0 ELSE TXN_CNT END'},
                {'name': 'TXN_CNT1', 'expr': 'TXN_CNT'},
                {'name': 'TXN_CNT1_V', 'expr': 'CASE WHEN (TXN_CNT IS NULL) THEN 0 ELSE TXN_CNT END'},
                {'name': 'TXN_CNT2', 'expr': 'TXN_CNT'},
                {'name': 'TXN_CNT2_V', 'expr': 'CASE WHEN (TXN_CNT IS NULL) THEN 0 ELSE TXN_CNT END'},
                {'name': 'TXN_CNT3', 'expr': 'TXN_CNT'},
                {'name': 'TXN_CNT3_V', 'expr': 'CASE WHEN (TXN_CNT IS NULL) THEN 0 ELSE TXN_CNT END'},
                {'name': 'TXN_CNT4', 'expr': 'TXN_CNT'},
                {'name': 'TXN_CNT4_V', 'expr': 'CASE WHEN (TXN_CNT IS NULL) THEN 0 ELSE TXN_CNT END'},
                {'name': 'SUM', 'expr': 'TXN_CNT_V + TXN_CNT1_V +TXN_CNT2_V + TXN_CNT3_V + TXN_CNT4_V'}
            ],
        )
        ctx.register_df("df_EXPTRANS3", df_EXPTRANS3)
        
        logger.info("Step: apply_Union_Transformation")
        # Union: apply_Union_Transformation
        df_Union_Transformation = lib.union(
            input_df=df_SQ_SOR_3,
            union_selects=[
                {'df_input': df_EXPTRANS1, 'selects': [
                    'SCHM_CODE',
                    'APLY_TYPE_CODE'
                ]},
                {'df_input': df_SQ_SOR_2, 'selects': [
                    'SCHM_CODE',
                    'APLY_TYPE_CODE'
                ]},
                {'df_input': df_SQ_SOR_3, 'selects': [
                    'SCHM_CODE',
                    'GF_CERT_TYPE_CODE'
                ]},
            ],
            output_columns=['SCHM_CODE', 'APLY_TYPE_CODE'],
        )
        ctx.register_df("df_Union_Transformation", df_Union_Transformation)
        
        logger.info("Step: apply_EXPTRANS2")
        # Expression: apply_EXPTRANS2
        df_EXPTRANS2 = lib.expression(
            input_df=df_lkp_merge_SQ_DPA_FACT_EMS_SMS_APLY_TYPE_TXN,
            computed_columns=[
                {'name': 'DESP_DTL_DMNS_KEY', 'expr': 'NULL'},
                {'name': 'CNT1_V', 'expr': 'CASE WHEN (TXN_CNT IS NULL) THEN 0 ELSE TXN_CNT END'},
                {'name': 'LAST_REC_TXN_TYPE_CODE', 'expr': 'NULL'},
                {'name': 'REC_RLS_IND', 'expr': 'NULL'},
                {'name': 'CNT2_V', 'expr': 'CASE WHEN (TXN_CNT IS NULL) THEN 0 ELSE TXN_CNT END'},
                {'name': 'DESP_DTL_CODE', 'expr': "'no_of_tran_total'"},
                {'name': 'DESP_DTL_SCHM_CDOE', 'expr': "'SMS'"},
                {'name': 'TOT_CNT', 'expr': 'CNT1_V + CNT2_V'}
            ],
        )
        ctx.register_df("df_EXPTRANS2", df_EXPTRANS2)
        
        logger.info("Step: read_LKP_DDS_DMNS_EMS_APLY_TYPE1")
        # Reading Data From Source - read_LKP_DDS_DMNS_EMS_APLY_TYPE1
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        df_LKP_DDS_DMNS_EMS_APLY_TYPE1 = lib.read_sql(spark, _conn, table="DDS_DMNS_EMS_APLY_TYPE")
        
        logger.info("Step: apply_LKP_DDS_DMNS_EMS_APLY_TYPE1")
        # Lookup: apply_LKP_DDS_DMNS_EMS_APLY_TYPE1
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DDS_DMNS_EMS_APLY_TYPE1 = df_LKP_DDS_DMNS_EMS_APLY_TYPE1.dropDuplicates(subset=["APLY_TYPE_CODE", "APLY_TYPE_SCHM_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_EXPTRANS3
        _lkp_input = _lkp_input.withColumn("IN_APLY_TYPE_SCHM_CODE", col("SCHM_CODE"))
        _lkp_input = _lkp_input.withColumn("IN_APLY_TYPE_CODE", col("APLY_TYPE_CODE"))
        # Join condition: IN_APLY_TYPE_CODE=APLY_TYPE_CODE AND IN_APLY_TYPE_SCHM_CODE=APLY_TYPE_SCHM_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS3 = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DDS_DMNS_EMS_APLY_TYPE1).alias("_lkp"),
            (col("_main.IN_APLY_TYPE_CODE") == col("_lkp.APLY_TYPE_CODE")) &
            (col("_main.IN_APLY_TYPE_SCHM_CODE") == col("_lkp.APLY_TYPE_SCHM_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DDS_DMNS_EMS_APLY_TYPE1[c] for c in df_LKP_DDS_DMNS_EMS_APLY_TYPE1.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        ctx.register_df("df_lkp_merge_EXPTRANS3", df_lkp_merge_EXPTRANS3)        
        logger.info("Step: apply_AGGTRANS3")
        # Aggregator: apply_AGGTRANS3
        # Select only mapped upstream columns with correct port names
        _agg_input = df_Union_Transformation.select(
            col("SCHM_CODE"),
            col("APLY_TYPE_CODE")        )
        df_AGGTRANS3 = _agg_input.groupBy("SCHM_CODE", "APLY_TYPE_CODE")
        df_AGGTRANS3 = df_AGGTRANS3.agg(
            count(expr("""*""")).alias("CNT")
        )
        ctx.register_df("df_AGGTRANS3", df_AGGTRANS3)
        
        logger.info("Step: read_LKP_DDS_DMNS_EMS_DESP_DTL1")
        # Reading Data From Source - read_LKP_DDS_DMNS_EMS_DESP_DTL1
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        df_LKP_DDS_DMNS_EMS_DESP_DTL1 = lib.read_sql(spark, _conn, table="DDS_DMNS_EMS_DESP_DTL")
        
        logger.info("Step: apply_LKP_DDS_DMNS_EMS_DESP_DTL1")
        # Lookup: apply_LKP_DDS_DMNS_EMS_DESP_DTL1
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DDS_DMNS_EMS_DESP_DTL1 = df_LKP_DDS_DMNS_EMS_DESP_DTL1.dropDuplicates(subset=["DESP_DTL_CODE", "DESP_DTL_SCHM_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_EXPTRANS2
        _lkp_input = _lkp_input.withColumn("IN_DESP_DTL_CODE", col("DESP_DTL_CODE"))
        _lkp_input = _lkp_input.withColumn("IN_DESP_DTL_SCHM_CODE", col("DESP_DTL_SCHM_CDOE"))
        # Join condition: IN_DESP_DTL_CODE=DESP_DTL_CODE AND IN_DESP_DTL_SCHM_CODE=DESP_DTL_SCHM_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS2 = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DDS_DMNS_EMS_DESP_DTL1).alias("_lkp"),
            (col("_main.IN_DESP_DTL_CODE") == col("_lkp.DESP_DTL_CODE")) &
            (col("_main.IN_DESP_DTL_SCHM_CODE") == col("_lkp.DESP_DTL_SCHM_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DDS_DMNS_EMS_DESP_DTL1[c] for c in df_LKP_DDS_DMNS_EMS_DESP_DTL1.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        ctx.register_df("df_lkp_merge_EXPTRANS2", df_lkp_merge_EXPTRANS2)        
        logger.info("Step: write_DPA_FACT_EMS_SMS_APLY_TYPE_TXN21")
        # Write to Target: write_DPA_FACT_EMS_SMS_APLY_TYPE_TXN21
        lib.write_target(
            spark=spark,
            df=df_lkp_merge_EXPTRANS3,
            conn=conn_target,
            table='DPA_FACT_EMS_SMS_APLY_TYPE_TXN',
            mode='append',
            source_columns=[
                'DESP_DTL_DMNS_KEY',
                'APLY_TYPE_DMNS_KEY',
                'TIME_DMNS_KEY',
                'SUM',
                'LAST_REC_TXN_DATE',
                None,
                None,
            ],
            target_columns=[
                'DESP_DTL_DMNS_KEY',
                'APLY_TYPE_DMNS_KEY',
                'TIME_DMNS_KEY',
                'TXN_CNT',
                'LAST_REC_TXN_DATE',
                'LAST_REC_TXN_TYPE_CODE',
                'REC_RLS_IND',
            ],
            config=config,
        )

        logger.info("write_DPA_FACT_EMS_SMS_APLY_TYPE_TXN21 write completed")
        logger.info("Step: apply_EXPTRANS")
        # Expression: apply_EXPTRANS
        df_EXPTRANS = lib.expression(
            input_df=df_AGGTRANS3,
            computed_columns=[
                {'name': 'DESP_DTL_SCHM_CODE', 'expr': "CASE WHEN SCHM_CODE = 'T' THEN 'no_of_tran_tps' ELSE 'no_of_tran_hos' END"},
                {'name': 'APLY_TYPE_CODE_OUT', 'expr': 'rtrim(ltrim(APLY_TYPE_CODE))'},
                {'name': 'TIME', 'expr': "to_date(cast(concat('$$v_rpt_mth', '01') as string), 'yyyyMMdd')"},
                {'name': 'LAST_REC_TXN_DATE', 'expr': 'current_timestamp()'},
                {'name': 'SMS_SCHM_CODE', 'expr': "'SMS'"}
            ],
            substitutions={'$$v_rpt_mth': v_rpt_mth},
        )
        ctx.register_df("df_EXPTRANS", df_EXPTRANS)
        
        logger.info("Step: write_DPA_FACT_EMS_SMS_APLY_TYPE_TXN2")
        # Write to Target: write_DPA_FACT_EMS_SMS_APLY_TYPE_TXN2
        lib.write_target(
            spark=spark,
            df=df_lkp_merge_EXPTRANS2,
            conn=conn_target,
            table='DPA_FACT_EMS_SMS_APLY_TYPE_TXN',
            mode='append',
            source_columns=[
                'DESP_DTL_DMNS_KEY',
                'APLY_TYPE_DMNS_KEY',
                'TIME_DMNS_KEY',
                'TOT_CNT',
                'LAST_REC_TXN_DATE',
                'LAST_REC_TXN_TYPE_CODE',
                'REC_RLS_IND',
            ],
            target_columns=[
                'DESP_DTL_DMNS_KEY',
                'APLY_TYPE_DMNS_KEY',
                'TIME_DMNS_KEY',
                'TXN_CNT',
                'LAST_REC_TXN_DATE',
                'LAST_REC_TXN_TYPE_CODE',
                'REC_RLS_IND',
            ],
            config=config,
        )

        logger.info("write_DPA_FACT_EMS_SMS_APLY_TYPE_TXN2 write completed")
        logger.info("Step: read_LKP_DDS_DMNS_TIME_1")
        # Reading Data From Source - read_LKP_DDS_DMNS_TIME_1
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        query = f"""SELECT DDS_DMNS_TIME.TIME_DMNS_KEY as TIME_DMNS_KEY, DDS_DMNS_TIME.CLDR_MTH_DAY as CLDR_MTH_DAY, DDS_DMNS_TIME.CLDR_MTH as CLDR_MTH, DDS_DMNS_TIME.CLDR_MTH_NAME as CLDR_MTH_NAME, DDS_DMNS_TIME.CLDR_YEAR as CLDR_YEAR, DDS_DMNS_TIME.CLDR_QTR as CLDR_QTR, DDS_DMNS_TIME.FSCL_MTH as FSCL_MTH, DDS_DMNS_TIME.FSCL_MTH_SEQ_NUM as FSCL_MTH_SEQ_NUM, DDS_DMNS_TIME.FSCL_QTR as FSCL_QTR, DDS_DMNS_TIME.FSCL_YEAR as FSCL_YEAR, DDS_DMNS_TIME.FSCL_QTR_SEQ_NUM as FSCL_QTR_SEQ_NUM, DDS_DMNS_TIME.CLDR_WKDY_NUM as CLDR_WKDY_NUM, DDS_DMNS_TIME.CLDR_HLDY_IND as CLDR_HLDY_IND, DDS_DMNS_TIME.FSCL_YEAR_SEQ_NUM as FSCL_YEAR_SEQ_NUM, DDS_DMNS_TIME.CLDR_HLDY_NAME as CLDR_HLDY_NAME, DDS_DMNS_TIME.TIME_VAL_DATE as TIME_VAL_DATE FROM DDS_DMNS_TIME
WHERE DDS_DMNS_TIME.TIME_DMNS_KEY like '2%'"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_rpt_mth", v_rpt_mth)
        df_LKP_DDS_DMNS_TIME_1 = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DDS_DMNS_TIME_1")
        # Lookup: apply_LKP_DDS_DMNS_TIME_1
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DDS_DMNS_TIME_1 = df_LKP_DDS_DMNS_TIME_1.dropDuplicates(subset=["TIME_VAL_DATE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_EXPTRANS
        _lkp_input = _lkp_input.withColumn("IN_TIME_VAL_DATE", col("TIME"))
        # Join condition: IN_TIME_VAL_DATE=TIME_VAL_DATE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DDS_DMNS_TIME_1).alias("_lkp"),
            (col("_main.IN_TIME_VAL_DATE") == col("_lkp.TIME_VAL_DATE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DDS_DMNS_TIME_1[c] for c in df_LKP_DDS_DMNS_TIME_1.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        ctx.register_df("df_lkp_merge_EXPTRANS", df_lkp_merge_EXPTRANS)        
        logger.info("Step: read_LKP_DDS_DMNS_EMS_DESP_DTL")
        # Reading Data From Source - read_LKP_DDS_DMNS_EMS_DESP_DTL
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        df_LKP_DDS_DMNS_EMS_DESP_DTL = lib.read_sql(spark, _conn, table="DDS_DMNS_EMS_DESP_DTL")
        
        logger.info("Step: apply_LKP_DDS_DMNS_EMS_DESP_DTL")
        # Lookup: apply_LKP_DDS_DMNS_EMS_DESP_DTL
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DDS_DMNS_EMS_DESP_DTL = df_LKP_DDS_DMNS_EMS_DESP_DTL.dropDuplicates(subset=["DESP_DTL_CODE", "DESP_DTL_SCHM_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_EXPTRANS
        _lkp_input = _lkp_input.withColumn("IN_DESP_DTL_CODE", col("DESP_DTL_SCHM_CODE"))
        _lkp_input = _lkp_input.withColumn("IN_DESP_DTL_SCHM_CODE", col("SMS_SCHM_CODE"))
        # Join condition: IN_DESP_DTL_CODE=DESP_DTL_CODE AND IN_DESP_DTL_SCHM_CODE=DESP_DTL_SCHM_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DDS_DMNS_EMS_DESP_DTL).alias("_lkp"),
            (col("_main.IN_DESP_DTL_CODE") == col("_lkp.DESP_DTL_CODE")) &
            (col("_main.IN_DESP_DTL_SCHM_CODE") == col("_lkp.DESP_DTL_SCHM_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DDS_DMNS_EMS_DESP_DTL[c] for c in df_LKP_DDS_DMNS_EMS_DESP_DTL.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: read_LKP_DDS_DMNS_EMS_APLY_TYPE")
        # Reading Data From Source - read_LKP_DDS_DMNS_EMS_APLY_TYPE
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        df_LKP_DDS_DMNS_EMS_APLY_TYPE = lib.read_sql(spark, _conn, table="DDS_DMNS_EMS_APLY_TYPE")
        
        logger.info("Step: apply_LKP_DDS_DMNS_EMS_APLY_TYPE")
        # Lookup: apply_LKP_DDS_DMNS_EMS_APLY_TYPE
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DDS_DMNS_EMS_APLY_TYPE = df_LKP_DDS_DMNS_EMS_APLY_TYPE.dropDuplicates(subset=["APLY_TYPE_CODE", "APLY_TYPE_SCHM_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_EXPTRANS
        _lkp_input = _lkp_input.withColumn("IN_APLY_TYPE_CODE", col("APLY_TYPE_CODE_OUT"))
        _lkp_input = _lkp_input.withColumn("IN_APLY_TYPE_SCHM_CODE", col("SMS_SCHM_CODE"))
        # Join condition: IN_APLY_TYPE_CODE=APLY_TYPE_CODE AND IN_APLY_TYPE_SCHM_CODE=APLY_TYPE_SCHM_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DDS_DMNS_EMS_APLY_TYPE).alias("_lkp"),
            (col("_main.IN_APLY_TYPE_CODE") == col("_lkp.APLY_TYPE_CODE")) &
            (col("_main.IN_APLY_TYPE_SCHM_CODE") == col("_lkp.APLY_TYPE_SCHM_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DDS_DMNS_EMS_APLY_TYPE[c] for c in df_LKP_DDS_DMNS_EMS_APLY_TYPE.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: write_DPA_FACT_EMS_SMS_APLY_TYPE_TXN")
        # Write to Target: write_DPA_FACT_EMS_SMS_APLY_TYPE_TXN
        lib.write_target(
            spark=spark,
            df=df_lkp_merge_EXPTRANS,
            conn=conn_target,
            table='DPA_FACT_EMS_SMS_APLY_TYPE_TXN',
            mode='append',
            source_columns=[
                'DESP_DTL_DMNS_KEY',
                'APLY_TYPE_DMNS_KEY',
                'TIME_DMNS_KEY',
                'CNT',
                'LAST_REC_TXN_DATE',
                None,
                None,
            ],
            target_columns=[
                'DESP_DTL_DMNS_KEY',
                'APLY_TYPE_DMNS_KEY',
                'TIME_DMNS_KEY',
                'TXN_CNT',
                'LAST_REC_TXN_DATE',
                'LAST_REC_TXN_TYPE_CODE',
                'REC_RLS_IND',
            ],
            config=config,
        )

        logger.info("write_DPA_FACT_EMS_SMS_APLY_TYPE_TXN write completed")
        
        metrics.complete()
        logger.info("Mapping M_S5_DPA_SUMMARIZE_FACT_EMS_SMS_APLY_TYPE_TXN completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_S5_DPA_SUMMARIZE_FACT_EMS_SMS_APLY_TYPE_TXN FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_S5_DPA_SUMMARIZE_FACT_EMS_SMS_APLY_TYPE_TXN", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_S5_DPA_SUMMARIZE_FACT_EMS_SMS_APLY_TYPE_TXN")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())