'''
* Script - M_EMS_SSAL1_EXTR_CSA_DRP_SWD_ADDR_MAP.py
* @date    2026-07-02
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
from pyspark.sql import DataFrame
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None) -> bool:
    """
    Execute the M_EMS_SSAL1_EXTR_CSA_DRP_SWD_ADDR_MAP mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
    
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_EMS_SSAL1_EXTR_CSA_DRP_SWD_ADDR_MAP")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_EMS_SSAL1_EXTR_CSA_DRP_SWD_ADDR_MAP", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_oracle = lib.get_db_config(config, "oracle-defaults")
    conn_source = lib.get_db_config(config, "SSA")
    conn_target = lib.get_db_config(config, "SSA")

    v_load_start_ds = ""
    v_load_end_ds = ""
    # Load mapping variables from job_params or UTL_JOB_PARAM file
    if job_params:
        for _var, _val in job_params.items():
            _clean = _var.replace("$", "")
            if _clean in [ "v_load_start_ds",  "v_load_end_ds", ]:
                if _clean == "v_load_start_ds":
                    v_load_start_ds = _val
                if _clean == "v_load_end_ds":
                    v_load_end_ds = _val
                logger.info("Loaded %s=%s from job_params", _var, _val)
    else:
        try:
            _param_obj = objects.get("UTL_JOB_PARAM", {})
            if isinstance(_param_obj, dict):
                _param_path = lib._resolve_path(_param_obj.get('path', '/tmp/UTL_JOB_PARAM'))
            with open(_param_path, "r") as _f:
                for _line in _f:
                    _line = _line.strip()
                    for _var in [ "$$v_load_start_ds",  "$$v_load_end_ds", ]:
                        if _line.startswith(_var + "="):
                            _val = _line.split("=", 1)[1]
                            _clean = _var.replace("$", "")
                            if _clean == "v_load_start_ds":
                                v_load_start_ds = _val
                            if _clean == "v_load_end_ds":
                                v_load_end_ds = _val
                            logger.info("Loaded %s=%s from %s", _var, _val, _param_path)
        except Exception:
            logger.warning("UTL_JOB_PARAM not found, using default values")
    
    try:
        logger.info("Step: read_CSA_DRP_SWD_ADDR_MAP")
        # Reading Data From Source - read_CSA_DRP_SWD_ADDR_MAP
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_src_1 = lib.read_sql(spark, _conn, table="CSA_DRP_SWD_ADDR_MAP")
        
        logger.info("Step: apply_SQ_CSA_DRP_SWD_ADDR_MAP")
        # Source Qualifier: apply_SQ_CSA_DRP_SWD_ADDR_MAP
        df_sq_2 = df_src_1
        df_sq_2 = df_sq_2.filter(expr("LAST_REC_TXN_DATE> to_date(''$$v_load_start_ds'','yyyy-mm-dd hh24:mi:ss') AND LAST_REC_TXN_DATE<= to_date(''$$v_load_end_ds'','yyyy-mm-dd hh24:mi:ss')"))
        # Select only SQ output ports (matches Informatica behavior)
        df_sq_2 = df_sq_2.select("SWD_EST_CODE", "SWD_BLK_CODE", "SWD_EST_NAME", "SWD_BLK_NAME", "SWD_WING_INFO", "HSE_BLK_KEY", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID")
        ctx.register_df("df_sq_2", df_sq_2)
        
        logger.info("Step: apply_EXPTRANS")
        # Expression: apply_EXPTRANS
        df_exp_3 = df_sq_2
        df_exp_3 = df_exp_3.withColumn("SWD_EST_CODE_OUT", expr("ltrim(rtrim(SWD_EST_CODE))"))
        df_exp_3 = df_exp_3.withColumn("SWD_BLK_CODE_OUT", expr("ltrim(rtrim(SWD_BLK_CODE))"))
        df_exp_3 = df_exp_3.withColumn("SWD_EST_NAME_OUT", expr("ltrim(rtrim(SWD_EST_NAME))"))
        df_exp_3 = df_exp_3.withColumn("SWD_BLK_NAME_OUT", expr("ltrim(rtrim(SWD_BLK_NAME))"))
        df_exp_3 = df_exp_3.withColumn("SWD_WING_INFO_OUT", expr("ltrim(rtrim(SWD_WING_INFO))"))
        df_exp_3 = df_exp_3.withColumn("HSE_BLK_KEY_OUT", expr("ltrim(rtrim(HSE_BLK_KEY))"))
        df_exp_3 = df_exp_3.withColumn("LAST_REC_TXN_TYPE_CODE_OUT", expr("ltrim(rtrim(LAST_REC_TXN_TYPE_CODE))"))
        df_exp_3 = df_exp_3.withColumn("LAST_REC_TXN_DATE_OUT", expr("LAST_REC_TXN_DATE"))
        df_exp_3 = df_exp_3.withColumn("LAST_REC_TXN_USER_ID_OUT", expr("ltrim(rtrim(LAST_REC_TXN_USER_ID))"))
        df_exp_3 = df_exp_3.withColumn("DUMMY", expr("'1'"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        # Select only mapping output ports (prevents column leakage)
        df_exp_3 = df_exp_3.select("SWD_EST_CODE_OUT", "SWD_BLK_CODE_OUT", "SWD_EST_NAME_OUT", "SWD_BLK_NAME_OUT", "SWD_WING_INFO_OUT", "HSE_BLK_KEY_OUT", "LAST_REC_TXN_TYPE_CODE_OUT", "LAST_REC_TXN_DATE_OUT", "LAST_REC_TXN_USER_ID_OUT", "DUMMY")
        ctx.register_df("df_exp_3", df_exp_3)
        
        logger.info("Step: write_EMS_CSA_DRP_SWD_ADDR_MAP")
        # Write to Target: write_EMS_CSA_DRP_SWD_ADDR_MAP
        df_write = df_exp_3
        # Cast columns to match target schema data types
        if "swd_est_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_est_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "swd_blk_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_blk_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "swd_est_name" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_est_name":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "swd_blk_name" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_blk_name":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "swd_wing_info" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_wing_info":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "hse_blk_key" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "hse_blk_key":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_type_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_type_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        if "last_rec_txn_user_id" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_user_id":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        # Map source columns to target columns using connector field map (handles name mismatches)
        _field_map = {"HSE_BLK_KEY": "HSE_BLK_KEY_OUT", "LAST_REC_TXN_DATE": "LAST_REC_TXN_DATE_OUT", "LAST_REC_TXN_TYPE_CODE": "LAST_REC_TXN_TYPE_CODE_OUT", "LAST_REC_TXN_USER_ID": "LAST_REC_TXN_USER_ID_OUT", "SWD_BLK_CODE": "SWD_BLK_CODE_OUT", "SWD_BLK_NAME": "SWD_BLK_NAME_OUT", "SWD_EST_CODE": "SWD_EST_CODE_OUT", "SWD_EST_NAME": "SWD_EST_NAME_OUT", "SWD_WING_INFO": "SWD_WING_INFO_OUT"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col not in df_write.columns and _src_col in df_write.columns:
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['SWD_EST_CODE', 'SWD_BLK_CODE', 'SWD_EST_NAME', 'SWD_BLK_NAME', 'SWD_WING_INFO', 'HSE_BLK_KEY', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'LAST_REC_TXN_USER_ID']
        df_write = df_write.select(*[col for col in _target_cols if col in df_write.columns])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "EMS_CSA_DRP_SWD_ADDR_MAP", mode="append")

        logger.info("write_EMS_CSA_DRP_SWD_ADDR_MAP write completed")
        logger.info("Step: write_EMS_CSA_DRP_SWD_ADDR_MAP1")
        # Write to Target: write_EMS_CSA_DRP_SWD_ADDR_MAP1
        df_write = df_exp_3
        # Cast columns to match target schema data types
        if "swd_est_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_est_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "swd_blk_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_blk_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "swd_est_name" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_est_name":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "swd_blk_name" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_blk_name":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "swd_wing_info" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "swd_wing_info":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "hse_blk_key" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "hse_blk_key":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_type_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_type_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        if "last_rec_txn_user_id" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_user_id":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "dummy" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "dummy":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        # Map source columns to target columns using connector field map (handles name mismatches)
        _field_map = {"DUMMY": "DUMMY", "HSE_BLK_KEY": "HSE_BLK_KEY_OUT", "LAST_REC_TXN_DATE": "LAST_REC_TXN_DATE_OUT", "LAST_REC_TXN_TYPE_CODE": "LAST_REC_TXN_TYPE_CODE_OUT", "LAST_REC_TXN_USER_ID": "LAST_REC_TXN_USER_ID_OUT", "SWD_BLK_CODE": "SWD_BLK_CODE_OUT", "SWD_BLK_NAME": "SWD_BLK_NAME_OUT", "SWD_EST_CODE": "SWD_EST_CODE_OUT", "SWD_EST_NAME": "SWD_EST_NAME_OUT", "SWD_WING_INFO": "SWD_WING_INFO_OUT"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col not in df_write.columns and _src_col in df_write.columns:
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['SWD_EST_CODE', 'SWD_BLK_CODE', 'SWD_EST_NAME', 'SWD_BLK_NAME', 'SWD_WING_INFO', 'HSE_BLK_KEY', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'LAST_REC_TXN_USER_ID', 'DUMMY']
        df_write = df_write.select(*[col for col in _target_cols if col in df_write.columns])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "EMS_CSA_DRP_SWD_ADDR_MAP1", mode="append")

        logger.info("write_EMS_CSA_DRP_SWD_ADDR_MAP1 write completed")
        
        metrics.complete()
        logger.info("Mapping M_EMS_SSAL1_EXTR_CSA_DRP_SWD_ADDR_MAP completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_EMS_SSAL1_EXTR_CSA_DRP_SWD_ADDR_MAP FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_EMS_SSAL1_EXTR_CSA_DRP_SWD_ADDR_MAP", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_EMS_SSAL1_EXTR_CSA_DRP_SWD_ADDR_MAP")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        return 0 if success else 1
    finally:
        spark.stop()


if __name__ == "__main__":
    main()