'''
* Script - M_S5_SSAL1_EXTRACT_TOW_TPS_AGRMT.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_S5_SSAL1_EXTRACT_TOW_TPS_AGRMT mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_S5_SSAL1_EXTRACT_TOW_TPS_AGRMT")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_S5_SSAL1_EXTRACT_TOW_TPS_AGRMT", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "EMS")

    v_load_start_ds = ""
    v_load_end_ds = ""
    # Load mapping variables from job_params or UTL_JOB_PARAM file
    try:
        _param_obj = objects.get("UTL_JOB_PARAM", {})
        if isinstance(_param_obj, dict):
            _param_path = lib._resolve_path(_param_obj.get('path'))
        with open(_param_path, "r") as _f:
            for _line in _f:
                _line = _line.strip()
                for _var in [ "$$v_load_start_ds",  "$$v_load_end_ds", ]:
                    if _line.startswith(_var + "="):
                        _val = _line.split("=", 1)[1]
                        _clean = _var.replace("$", "")
                        if _clean == "v_load_start_ds":
                            v_load_start_ds = _val
                        if _clean == "v_load_end_ds":
                            v_load_end_ds = _val
                        logger.info("Loaded %s=%s from %s", _var, _val, _param_path)
    except Exception:
        logger.warning("UTL_JOB_PARAM not found, using default values")
    
    try:
        logger.info("Step: read_TOW_TPS_AGRMT")
        # Reading Data From Source - read_TOW_TPS_AGRMT
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "EMS")
        df_TOW_TPS_AGRMT = lib.read_sql(spark, _conn, table="TOW_TPS_AGRMT")
        
        logger.info("Step: apply_SQ_TOW_TPS_AGRMT")
        # Source Qualifier: apply_SQ_TOW_TPS_AGRMT
        df_SQ_TOW_TPS_AGRMT = df_TOW_TPS_AGRMT
        _filter_text = """LAST_REC_TXN_DATE > to_date('$$v_load_start_ds','yyyy-MM-dd HH:mm:ss') AND LAST_REC_TXN_DATE <= to_date('$$v_load_end_ds','yyyy-MM-dd HH:mm:ss')"""
        _filter_text = _filter_text.replace("$$v_load_start_ds", str(v_load_start_ds or "0"))
        _filter_text = _filter_text.replace("$$v_load_end_ds", str(v_load_end_ds or "0"))
        df_SQ_TOW_TPS_AGRMT = df_SQ_TOW_TPS_AGRMT.filter(expr(_filter_text))
        # Select only SQ output ports (matches Informatica behavior) — missing ports become lit(None)
        _port_cols = ["HSE_SRVC_APLY_KEY", "TPS_HSE_UNIT_KEY", "TPS_AGRMT_SEQ_NUM", "CUST_KEY", "TPS_AGRMT_ASGN_DATE", "TPS_AGRMT_TRMT_DATE", "TPS_PCHS_FROM_CODE", "TPS_TRMT_TYPE_CODE", "TPS_AGRMT_EXOWNR_REF_CODE", "TPS_AGRMT_HOME_PHONE_NUM_1", "TPS_AGRMT_HOME_PHONE_NUM_2", "TPS_AGRMT_OFFC_PHONE_NUM_1", "TPS_AGRMT_OFFC_PHONE_NUM_2", "TPS_AGRMT_MBL_PHONE_NUM_1", "TPS_AGRMT_MBL_PHONE_NUM_2", "TPS_AGRMT_RMK_TEXT", "TPS_CHNG_OWNR_RMK_TEXT", "TPS_MGT_FEE_DPST_AMT", "ORIG_CUST_KEY", "ORIG_HSE_SRVC_APLY_KEY", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID", "TPS_APLY_TYPE_CODE", "APLY_MBR_TYPE_CODE", "APLY_MBR_REF_NUM", "TPS_AGRMT_CRE_DATE", "TPS_AGRMT_PHASE_CODE", "TPS_AGRMT_FRST_ASGN_DATE", "MBR_ACT_IND", "ORIG_HSE_UNIT_TOT_IFA_AREA", "CAS_DBR_END_DATE"]
        df_SQ_TOW_TPS_AGRMT = df_SQ_TOW_TPS_AGRMT.select([col(c) if c.lower() in [x.lower() for x in df_SQ_TOW_TPS_AGRMT.columns] else lit(None).alias(c) for c in _port_cols])
        ctx.register_df("df_SQ_TOW_TPS_AGRMT", df_SQ_TOW_TPS_AGRMT)
        
        logger.info("Step: apply_EXPTRANS")
        # Expression: apply_EXPTRANS
        df_EXPTRANS = df_SQ_TOW_TPS_AGRMT
        df_EXPTRANS = df_EXPTRANS.withColumn("HSE_SRVC_APLY_KEY_OUT", expr("ltrim(rtrim(HSE_SRVC_APLY_KEY))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_HSE_UNIT_KEY_OUT", expr("ltrim(rtrim(TPS_HSE_UNIT_KEY))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_SEQ_NUM_OUT", expr("TPS_AGRMT_SEQ_NUM"))
        df_EXPTRANS = df_EXPTRANS.withColumn("CUST_KEY_OUT", expr("ltrim(rtrim(CUST_KEY))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_ASGN_DATE_OUT", expr("TPS_AGRMT_ASGN_DATE"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_TRMT_DATE_OUT", expr("TPS_AGRMT_TRMT_DATE"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_PCHS_FROM_CODE_OUT", expr("ltrim(rtrim(TPS_PCHS_FROM_CODE))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_TRMT_TYPE_CODE_OUT", expr("ltrim(rtrim(TPS_TRMT_TYPE_CODE))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_EXOWNR_REF_CODE_OUT", expr("ltrim(rtrim(TPS_AGRMT_EXOWNR_REF_CODE))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_HOME_PHONE_NUM_1_OUT", expr("ltrim(rtrim(TPS_AGRMT_HOME_PHONE_NUM_1))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_HOME_PHONE_NUM_2_OUT", expr("ltrim(rtrim(TPS_AGRMT_HOME_PHONE_NUM_2))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_OFFC_PHONE_NUM_1_OUT", expr("ltrim(rtrim(TPS_AGRMT_OFFC_PHONE_NUM_1))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_OFFC_PHONE_NUM_2_OUT", expr("ltrim(rtrim(TPS_AGRMT_OFFC_PHONE_NUM_2))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_MBL_PHONE_NUM_1_OUT", expr("ltrim(rtrim(TPS_AGRMT_MBL_PHONE_NUM_1))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_MBL_PHONE_NUM_2_OUT", expr("ltrim(rtrim(TPS_AGRMT_MBL_PHONE_NUM_2))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_RMK_TEXT_OUT", expr("ltrim(rtrim(TPS_AGRMT_RMK_TEXT))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_CHNG_OWNR_RMK_TEXT_OUT", expr("ltrim(rtrim(TPS_CHNG_OWNR_RMK_TEXT))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_MGT_FEE_DPST_AMT_OUT", expr("TPS_MGT_FEE_DPST_AMT"))
        df_EXPTRANS = df_EXPTRANS.withColumn("ORIG_CUST_KEY_OUT", expr("ltrim(rtrim(ORIG_CUST_KEY))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("ORIG_HSE_SRVC_APLY_KEY_OUT", expr("ltrim(rtrim(ORIG_HSE_SRVC_APLY_KEY))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("LAST_REC_TXN_TYPE_CODE_OUT", expr("ltrim(rtrim(LAST_REC_TXN_TYPE_CODE))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("LAST_REC_TXN_DATE_OUT", expr("LAST_REC_TXN_DATE"))
        df_EXPTRANS = df_EXPTRANS.withColumn("LAST_REC_TXN_USER_ID_OUT", expr("ltrim(rtrim(LAST_REC_TXN_USER_ID))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_APLY_TYPE_CODE_OUT", expr("ltrim(rtrim(TPS_APLY_TYPE_CODE))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("APLY_MBR_TYPE_CODE_OUT", expr("ltrim(rtrim(APLY_MBR_TYPE_CODE))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("APLY_MBR_REF_NUM_OUT", expr("ltrim(rtrim(APLY_MBR_REF_NUM))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_CRE_DATE_OUT", expr("TPS_AGRMT_CRE_DATE"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_PHASE_CODE_OUT", expr("ltrim(rtrim(TPS_AGRMT_PHASE_CODE))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("TPS_AGRMT_FRST_ASGN_DATE_OUT", expr("TPS_AGRMT_FRST_ASGN_DATE"))
        df_EXPTRANS = df_EXPTRANS.withColumn("MBR_ACT_IND_OUT", expr("ltrim(rtrim(MBR_ACT_IND))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("ORIG_HSE_UNIT_TOT_IFA_AREA_OUT", expr("ltrim(rtrim(ORIG_HSE_UNIT_TOT_IFA_AREA))"))
        df_EXPTRANS = df_EXPTRANS.withColumn("DUMMY", expr("'|'"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["CAS_DBR_END_DATE"]:
            if _col.lower() not in [x.lower() for x in df_EXPTRANS.columns]:
                df_EXPTRANS = df_EXPTRANS.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_EXPTRANS", df_EXPTRANS)
        
        logger.info("Step: write_EMS_TOW_TPS_AGRMT1")
        # Write to Target: write_EMS_TOW_TPS_AGRMT1
        df_write = df_EXPTRANS
        # Map source columns to target columns using connector field map (handles name
        # mismatches) — done BEFORE the _update_flag split so UPDATE/DELETE use target
        # column names in batch_update/batch_delete.
        _field_map = {"APLY_MBR_REF_NUM": "APLY_MBR_REF_NUM_OUT", "APLY_MBR_TYPE_CODE": "APLY_MBR_TYPE_CODE_OUT", "CUST_KEY": "CUST_KEY_OUT", "DUMMY": "DUMMY", "HSE_SRVC_APLY_KEY": "HSE_SRVC_APLY_KEY_OUT", "LAST_REC_TXN_DATE": "LAST_REC_TXN_DATE_OUT", "LAST_REC_TXN_TYPE_CODE": "LAST_REC_TXN_TYPE_CODE_OUT", "LAST_REC_TXN_USER_ID": "LAST_REC_TXN_USER_ID_OUT", "MBR_ACT_IND": "MBR_ACT_IND_OUT", "ORIG_CUST_KEY": "ORIG_CUST_KEY_OUT", "ORIG_HSE_SRVC_APLY_KEY": "ORIG_HSE_SRVC_APLY_KEY_OUT", "ORIG_HSE_UNIT_TOT_IFA_AREA": "ORIG_HSE_UNIT_TOT_IFA_AREA_OUT", "TPS_AGRMT_ASGN_DATE": "TPS_AGRMT_ASGN_DATE_OUT", "TPS_AGRMT_CRE_DATE": "TPS_AGRMT_CRE_DATE_OUT", "TPS_AGRMT_EXOWNR_REF_CODE": "TPS_AGRMT_EXOWNR_REF_CODE_OUT", "TPS_AGRMT_FRST_ASGN_DATE": "TPS_AGRMT_FRST_ASGN_DATE_OUT", "TPS_AGRMT_HOME_PHONE_NUM_1": "TPS_AGRMT_HOME_PHONE_NUM_1_OUT", "TPS_AGRMT_HOME_PHONE_NUM_2": "TPS_AGRMT_HOME_PHONE_NUM_2_OUT", "TPS_AGRMT_MBL_PHONE_NUM_1": "TPS_AGRMT_MBL_PHONE_NUM_1_OUT", "TPS_AGRMT_MBL_PHONE_NUM_2": "TPS_AGRMT_MBL_PHONE_NUM_2_OUT", "TPS_AGRMT_OFFC_PHONE_NUM_1": "TPS_AGRMT_OFFC_PHONE_NUM_1_OUT", "TPS_AGRMT_OFFC_PHONE_NUM_2": "TPS_AGRMT_OFFC_PHONE_NUM_2_OUT", "TPS_AGRMT_PHASE_CODE": "TPS_AGRMT_PHASE_CODE_OUT", "TPS_AGRMT_RMK_TEXT": "TPS_AGRMT_RMK_TEXT_OUT", "TPS_AGRMT_SEQ_NUM": "TPS_AGRMT_SEQ_NUM_OUT", "TPS_AGRMT_TRMT_DATE": "TPS_AGRMT_TRMT_DATE_OUT", "TPS_APLY_TYPE_CODE": "TPS_APLY_TYPE_CODE_OUT", "TPS_CHNG_OWNR_RMK_TEXT": "TPS_CHNG_OWNR_RMK_TEXT_OUT", "TPS_HSE_UNIT_KEY": "TPS_HSE_UNIT_KEY_OUT", "TPS_MGT_FEE_DPST_AMT": "TPS_MGT_FEE_DPST_AMT_OUT", "TPS_PCHS_FROM_CODE": "TPS_PCHS_FROM_CODE_OUT", "TPS_TRMT_TYPE_CODE": "TPS_TRMT_TYPE_CODE_OUT"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col.lower() not in [x.lower() for x in df_write.columns] and _src_col.lower() in [x.lower() for x in df_write.columns]:
                # Drop any column that would conflict case-insensitively with the target name 
                for _c in list(df_write.columns):
                    if _c.lower() == _tgt_col.lower() and _c != _src_col:
                        df_write = df_write.drop(_c)
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("CAS_DBR_END_DATE", lit(None).cast(StringType()))
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['HSE_SRVC_APLY_KEY', 'TPS_HSE_UNIT_KEY', 'TPS_AGRMT_SEQ_NUM', 'CUST_KEY', 'TPS_AGRMT_ASGN_DATE', 'TPS_AGRMT_TRMT_DATE', 'TPS_PCHS_FROM_CODE', 'TPS_TRMT_TYPE_CODE', 'TPS_AGRMT_EXOWNR_REF_CODE', 'TPS_AGRMT_HOME_PHONE_NUM_1', 'TPS_AGRMT_HOME_PHONE_NUM_2', 'TPS_AGRMT_OFFC_PHONE_NUM_1', 'TPS_AGRMT_OFFC_PHONE_NUM_2', 'TPS_AGRMT_MBL_PHONE_NUM_1', 'TPS_AGRMT_MBL_PHONE_NUM_2', 'TPS_AGRMT_RMK_TEXT', 'TPS_CHNG_OWNR_RMK_TEXT', 'TPS_MGT_FEE_DPST_AMT', 'ORIG_CUST_KEY', 'ORIG_HSE_SRVC_APLY_KEY', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'LAST_REC_TXN_USER_ID', 'TPS_APLY_TYPE_CODE', 'APLY_MBR_TYPE_CODE', 'APLY_MBR_REF_NUM', 'TPS_AGRMT_CRE_DATE', 'TPS_AGRMT_PHASE_CODE', 'TPS_AGRMT_FRST_ASGN_DATE', 'MBR_ACT_IND', 'ORIG_HSE_UNIT_TOT_IFA_AREA', 'CAS_DBR_END_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col.lower() in [x.lower() for x in df_write.columns]])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "EMS_TOW_TPS_AGRMT", mode="append")

        logger.info("write_EMS_TOW_TPS_AGRMT1 write completed")
        logger.info("Step: write_EMS_TOW_TPS_AGRMT")
        # Write to Target: write_EMS_TOW_TPS_AGRMT
        df_write = df_EXPTRANS
        # Map source columns to target columns using connector field map (handles name
        # mismatches) — done BEFORE the _update_flag split so UPDATE/DELETE use target
        # column names in batch_update/batch_delete.
        _field_map = {"APLY_MBR_REF_NUM": "APLY_MBR_REF_NUM_OUT", "APLY_MBR_TYPE_CODE": "APLY_MBR_TYPE_CODE_OUT", "CAS_DBR_END_DATE": "CAS_DBR_END_DATE", "CUST_KEY": "CUST_KEY_OUT", "HSE_SRVC_APLY_KEY": "HSE_SRVC_APLY_KEY_OUT", "LAST_REC_TXN_DATE": "LAST_REC_TXN_DATE_OUT", "LAST_REC_TXN_TYPE_CODE": "LAST_REC_TXN_TYPE_CODE_OUT", "LAST_REC_TXN_USER_ID": "LAST_REC_TXN_USER_ID_OUT", "MBR_ACT_IND": "MBR_ACT_IND_OUT", "ORIG_CUST_KEY": "ORIG_CUST_KEY_OUT", "ORIG_HSE_SRVC_APLY_KEY": "ORIG_HSE_SRVC_APLY_KEY_OUT", "ORIG_HSE_UNIT_TOT_IFA_AREA": "ORIG_HSE_UNIT_TOT_IFA_AREA_OUT", "TPS_AGRMT_ASGN_DATE": "TPS_AGRMT_ASGN_DATE_OUT", "TPS_AGRMT_CRE_DATE": "TPS_AGRMT_CRE_DATE_OUT", "TPS_AGRMT_EXOWNR_REF_CODE": "TPS_AGRMT_EXOWNR_REF_CODE_OUT", "TPS_AGRMT_FRST_ASGN_DATE": "TPS_AGRMT_FRST_ASGN_DATE_OUT", "TPS_AGRMT_HOME_PHONE_NUM_1": "TPS_AGRMT_HOME_PHONE_NUM_1_OUT", "TPS_AGRMT_HOME_PHONE_NUM_2": "TPS_AGRMT_HOME_PHONE_NUM_2_OUT", "TPS_AGRMT_MBL_PHONE_NUM_1": "TPS_AGRMT_MBL_PHONE_NUM_1_OUT", "TPS_AGRMT_MBL_PHONE_NUM_2": "TPS_AGRMT_MBL_PHONE_NUM_2_OUT", "TPS_AGRMT_OFFC_PHONE_NUM_1": "TPS_AGRMT_OFFC_PHONE_NUM_1_OUT", "TPS_AGRMT_OFFC_PHONE_NUM_2": "TPS_AGRMT_OFFC_PHONE_NUM_2_OUT", "TPS_AGRMT_PHASE_CODE": "TPS_AGRMT_PHASE_CODE_OUT", "TPS_AGRMT_RMK_TEXT": "TPS_AGRMT_RMK_TEXT_OUT", "TPS_AGRMT_SEQ_NUM": "TPS_AGRMT_SEQ_NUM_OUT", "TPS_AGRMT_TRMT_DATE": "TPS_AGRMT_TRMT_DATE_OUT", "TPS_APLY_TYPE_CODE": "TPS_APLY_TYPE_CODE_OUT", "TPS_CHNG_OWNR_RMK_TEXT": "TPS_CHNG_OWNR_RMK_TEXT_OUT", "TPS_HSE_UNIT_KEY": "TPS_HSE_UNIT_KEY_OUT", "TPS_MGT_FEE_DPST_AMT": "TPS_MGT_FEE_DPST_AMT_OUT", "TPS_PCHS_FROM_CODE": "TPS_PCHS_FROM_CODE_OUT", "TPS_TRMT_TYPE_CODE": "TPS_TRMT_TYPE_CODE_OUT"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col.lower() not in [x.lower() for x in df_write.columns] and _src_col.lower() in [x.lower() for x in df_write.columns]:
                # Drop any column that would conflict case-insensitively with the target name 
                for _c in list(df_write.columns):
                    if _c.lower() == _tgt_col.lower() and _c != _src_col:
                        df_write = df_write.drop(_c)
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['HSE_SRVC_APLY_KEY', 'TPS_HSE_UNIT_KEY', 'TPS_AGRMT_SEQ_NUM', 'CUST_KEY', 'TPS_AGRMT_ASGN_DATE', 'TPS_AGRMT_TRMT_DATE', 'TPS_PCHS_FROM_CODE', 'TPS_TRMT_TYPE_CODE', 'TPS_AGRMT_EXOWNR_REF_CODE', 'TPS_AGRMT_HOME_PHONE_NUM_1', 'TPS_AGRMT_HOME_PHONE_NUM_2', 'TPS_AGRMT_OFFC_PHONE_NUM_1', 'TPS_AGRMT_OFFC_PHONE_NUM_2', 'TPS_AGRMT_MBL_PHONE_NUM_1', 'TPS_AGRMT_MBL_PHONE_NUM_2', 'TPS_AGRMT_RMK_TEXT', 'TPS_CHNG_OWNR_RMK_TEXT', 'TPS_MGT_FEE_DPST_AMT', 'ORIG_CUST_KEY', 'ORIG_HSE_SRVC_APLY_KEY', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'LAST_REC_TXN_USER_ID', 'TPS_APLY_TYPE_CODE', 'APLY_MBR_TYPE_CODE', 'APLY_MBR_REF_NUM', 'TPS_AGRMT_CRE_DATE', 'TPS_AGRMT_PHASE_CODE', 'TPS_AGRMT_FRST_ASGN_DATE', 'MBR_ACT_IND', 'ORIG_HSE_UNIT_TOT_IFA_AREA', 'CAS_DBR_END_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col.lower() in [x.lower() for x in df_write.columns]])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "EMS_TOW_TPS_AGRMT", mode="append")

        logger.info("write_EMS_TOW_TPS_AGRMT write completed")
        
        metrics.complete()
        logger.info("Mapping M_S5_SSAL1_EXTRACT_TOW_TPS_AGRMT completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_S5_SSAL1_EXTRACT_TOW_TPS_AGRMT FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_S5_SSAL1_EXTRACT_TOW_TPS_AGRMT", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_S5_SSAL1_EXTRACT_TOW_TPS_AGRMT")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())