'''
* Script - M_EMS_SOR_LOAD_MRRS_UAO_FEE_ARR_CF_FOR_INSERT.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_EMS_SOR_LOAD_MRRS_UAO_FEE_ARR_CF_FOR_INSERT mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_EMS_SOR_LOAD_MRRS_UAO_FEE_ARR_CF_FOR_INSERT")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_EMS_SOR_LOAD_MRRS_UAO_FEE_ARR_CF_FOR_INSERT", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "SOR")

    EMM_MRRS_RENT_CUTOFF = ""
    # Load mapping variables from the UTL_JOB_PARAM file (shared helper)
    _vars = lib.load_mapping_variables(config, [ "$$EMM_MRRS_RENT_CUTOFF", ], logger)
    EMM_MRRS_RENT_CUTOFF = _vars.get("EMM_MRRS_RENT_CUTOFF", EMM_MRRS_RENT_CUTOFF)
    
    try:
        logger.info("Step: read_SSA_EMS_MRRS_UAO_FEE_ARR_CF")
        # Reading Data From Source - read_SSA_EMS_MRRS_UAO_FEE_ARR_CF
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_EMS_MRRS_UAO_FEE_ARR_CF = lib.read_sql(spark, _conn, table="SSA_EMS_MRRS_UAO_FEE_ARR_CF")
        
        logger.info("Step: apply_SQ_SSA_EMS_MRRS_UAO_FEE_ARR_CF")
        # Source Qualifier: apply_SQ_SSA_EMS_MRRS_UAO_FEE_ARR_CF
        df_SQ_SSA_EMS_MRRS_UAO_FEE_ARR_CF = df_SSA_EMS_MRRS_UAO_FEE_ARR_CF
        df_SQ_SSA_EMS_MRRS_UAO_FEE_ARR_CF = lib.sq_output(
            input_df=df_SQ_SSA_EMS_MRRS_UAO_FEE_ARR_CF,
            port_cols={
                'UAO_FEE_ARR_CF_KEY': 'decimal',
                'UAO_FEE_ARR_CF_BK': 'string',
                'CUST_KEY': 'string',
                'HSE_SRVC_APLY_KEY': 'string',
                'HSE_UNIT_KEY': 'decimal',
                'SYS_RPT_YEAR': 'decimal',
                'SYS_RPT_MTH': 'decimal',
                'HSE_UNIT_CODE_ADDR': 'string',
                'FRST_UAO_FEE_ARR_CF_AMT': 'decimal',
                'SCND_UAO_FEE_ARR_CF_AMT': 'decimal',
                'THRD_UAO_FEE_ARR_CF_AMT': 'decimal',
                'FRTH_UAO_FEE_ARR_CF_AMT': 'decimal',
                'FTH_UAO_FEE_ARR_CF_AMT': 'decimal',
                'SXTH_UAO_FEE_ARR_CF_AMT': 'decimal',
                'SVNTH_UAO_FEE_ARR_CF_AMT': 'decimal',
                'EGHTH_UAO_FEE_ARR_CF_AMT': 'decimal',
                'NTH_UAO_FEE_ARR_CF_AMT': 'decimal',
                'UAO_FEE_ARR_CF_RMK_TEXT': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'LAST_REC_TXN_USER_ID': 'string',
                'OPR_IND': 'string',
            },
            filter_condition="OPR_IND = 'B' OR OPR_IND = 'A'",
        )
        ctx.register_df("df_SQ_SSA_EMS_MRRS_UAO_FEE_ARR_CF", df_SQ_SSA_EMS_MRRS_UAO_FEE_ARR_CF)
        
        logger.info("Step: apply_EMM_MRRS_RENT_CUTOFF")
        # Source Qualifier: apply_EMM_MRRS_RENT_CUTOFF
        # SQL Pushdown - executes Informatica SQ SQL on source database
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT DISTINCT SYS_RPT_YEAR, SYS_RPT_MTH FROM SOR_EMS_MRRS_UAO_FEE_ARR_CF 
WHERE (SYS_RPT_YEAR=TO_NUMBER(SUBSTR('$$EMM_MRRS_RENT_CUTOFF',1,4)) AND SYS_RPT_MTH>TO_NUMBER(SUBSTR('$$EMM_MRRS_RENT_CUTOFF',5,2)))
OR SYS_RPT_YEAR>TO_NUMBER(SUBSTR('$$EMM_MRRS_RENT_CUTOFF',1,4))"""
        query = query.replace("$$EMM_MRRS_RENT_CUTOFF", EMM_MRRS_RENT_CUTOFF)
        df_EMM_MRRS_RENT_CUTOFF = lib.read_sql(spark, _conn, query=query)
        df_EMM_MRRS_RENT_CUTOFF = lib.sq_output(
            input_df=df_EMM_MRRS_RENT_CUTOFF,
            port_cols={
                'SYS_RPT_YEAR': 'decimal',
                'SYS_RPT_MTH': 'decimal',
            },
        )
        ctx.register_df("df_EMM_MRRS_RENT_CUTOFF", df_EMM_MRRS_RENT_CUTOFF)
        
        logger.info("Step: write_SOR_EMS_MRRS_UAO_FEE_ARR_CF")
        # Write to Target: write_SOR_EMS_MRRS_UAO_FEE_ARR_CF
        lib.write_target(
            spark=spark,
            df=df_SQ_SSA_EMS_MRRS_UAO_FEE_ARR_CF,
            conn=conn_target,
            table='SOR_EMS_MRRS_UAO_FEE_ARR_CF',
            mode='append',
            source_columns=[
                'UAO_FEE_ARR_CF_KEY',
                'UAO_FEE_ARR_CF_BK',
                None,
                'CUST_KEY',
                'HSE_SRVC_APLY_KEY',
                'HSE_UNIT_KEY',
                'SYS_RPT_YEAR',
                'SYS_RPT_MTH',
                'HSE_UNIT_CODE_ADDR',
                'FRST_UAO_FEE_ARR_CF_AMT',
                'SCND_UAO_FEE_ARR_CF_AMT',
                'THRD_UAO_FEE_ARR_CF_AMT',
                'FRTH_UAO_FEE_ARR_CF_AMT',
                'FTH_UAO_FEE_ARR_CF_AMT',
                'SXTH_UAO_FEE_ARR_CF_AMT',
                'SVNTH_UAO_FEE_ARR_CF_AMT',
                'EGHTH_UAO_FEE_ARR_CF_AMT',
                'NTH_UAO_FEE_ARR_CF_AMT',
                'UAO_FEE_ARR_CF_RMK_TEXT',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            target_columns=[
                'UAO_FEE_ARR_CF_KEY',
                'UAO_FEE_ARR_CF_BK',
                'TNCY_AGRMT_KEY',
                'CUST_KEY',
                'HSE_SRVC_APLY_KEY',
                'HSE_UNIT_KEY',
                'SYS_RPT_YEAR',
                'SYS_RPT_MTH',
                'HSE_UNIT_CODE_ADDR',
                'FRST_UAO_FEE_ARR_CF_AMT',
                'SCND_UAO_FEE_ARR_CF_AMT',
                'THRD_UAO_FEE_ARR_CF_AMT',
                'FRTH_UAO_FEE_ARR_CF_AMT',
                'FTH_UAO_FEE_ARR_CF_AMT',
                'SXTH_UAO_FEE_ARR_CF_AMT',
                'SVNTH_UAO_FEE_ARR_CF_AMT',
                'EGHTH_UAO_FEE_ARR_CF_AMT',
                'NTH_UAO_FEE_ARR_CF_AMT',
                'UAO_FEE_ARR_CF_RMK_TEXT',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            config=config,
        )

        logger.info("write_SOR_EMS_MRRS_UAO_FEE_ARR_CF write completed")
        logger.info("Step: apply_UPDTRANS")
        # Update Strategy: apply_UPDTRANS
        # Strategy: DD_DELETE
        df_UPDTRANS = lib.update_strategy(
            input_df=df_EMM_MRRS_RENT_CUTOFF,
        )
        ctx.register_df("df_UPDTRANS", df_UPDTRANS)
        
        logger.info("Step: write_SOR_EMS_MRRS_UAO_FEE_ARR_CF1")
        # Write to Target: write_SOR_EMS_MRRS_UAO_FEE_ARR_CF1
        lib.write_target(
            spark=spark,
            df=df_UPDTRANS,
            conn=conn_target,
            table='SOR_EMS_MRRS_UAO_FEE_ARR_CF',
            mode='append',
            source_columns=[
                None,
                None,
                None,
                None,
                None,
                None,
                'SYS_RPT_YEAR',
                'SYS_RPT_MTH',
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ],
            target_columns=[
                'UAO_FEE_ARR_CF_KEY',
                'UAO_FEE_ARR_CF_BK',
                'TNCY_AGRMT_KEY',
                'CUST_KEY',
                'HSE_SRVC_APLY_KEY',
                'HSE_UNIT_KEY',
                'SYS_RPT_YEAR',
                'SYS_RPT_MTH',
                'HSE_UNIT_CODE_ADDR',
                'FRST_UAO_FEE_ARR_CF_AMT',
                'SCND_UAO_FEE_ARR_CF_AMT',
                'THRD_UAO_FEE_ARR_CF_AMT',
                'FRTH_UAO_FEE_ARR_CF_AMT',
                'FTH_UAO_FEE_ARR_CF_AMT',
                'SXTH_UAO_FEE_ARR_CF_AMT',
                'SVNTH_UAO_FEE_ARR_CF_AMT',
                'EGHTH_UAO_FEE_ARR_CF_AMT',
                'NTH_UAO_FEE_ARR_CF_AMT',
                'UAO_FEE_ARR_CF_RMK_TEXT',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            is_delete=True,
            delete_keys=['UAO_FEE_ARR_CF_KEY', 'SYS_RPT_YEAR', 'SYS_RPT_MTH'],
            static_dd='DD_DELETE',
            config=config,
        )

        logger.info("write_SOR_EMS_MRRS_UAO_FEE_ARR_CF1 write completed")
        
        metrics.complete()
        logger.info("Mapping M_EMS_SOR_LOAD_MRRS_UAO_FEE_ARR_CF_FOR_INSERT completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_EMS_SOR_LOAD_MRRS_UAO_FEE_ARR_CF_FOR_INSERT FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_EMS_SOR_LOAD_MRRS_UAO_FEE_ARR_CF_FOR_INSERT", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_EMS_SOR_LOAD_MRRS_UAO_FEE_ARR_CF_FOR_INSERT")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())