'''
* Script - M_EMS_SSAL2_TRANS_PAL_PRH_INTK_SCHD.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_EMS_SSAL2_TRANS_PAL_PRH_INTK_SCHD mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_EMS_SSAL2_TRANS_PAL_PRH_INTK_SCHD")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_EMS_SSAL2_TRANS_PAL_PRH_INTK_SCHD", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "SSA")

    v_snsh_date = ""
    v_init_flag = ""
    # Load mapping variables from job_params or UTL_JOB_PARAM file
    try:
        _param_obj = objects.get("UTL_JOB_PARAM", {})
        if isinstance(_param_obj, dict):
            _param_path = lib._resolve_path(_param_obj.get('path'))
        with open(_param_path, "r") as _f:
            for _line in _f:
                _line = _line.strip()
                for _var in [ "$$v_snsh_date",  "$$v_init_flag", ]:
                    if _line.startswith(_var + "="):
                        _val = _line.split("=", 1)[1]
                        _clean = _var.replace("$", "")
                        if _clean == "v_snsh_date":
                            v_snsh_date = _val
                        if _clean == "v_init_flag":
                            v_init_flag = _val
                        logger.info("Loaded %s=%s from %s", _var, _val, _param_path)
    except Exception:
        logger.warning("UTL_JOB_PARAM not found, using default values")
    
    try:
        logger.info("Step: read_EMS_PAL_PRH_INTK_SCHD1")
        # Reading Data From Source - read_EMS_PAL_PRH_INTK_SCHD1
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_EMS_PAL_PRH_INTK_SCHD1 = lib.read_sql(spark, _conn, table="EMS_PAL_PRH_INTK_SCHD")
        
        logger.info("Step: read_EMS_PAL_PRH_INTK_SCHD21")
        # Reading Data From Source - read_EMS_PAL_PRH_INTK_SCHD21
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_EMS_PAL_PRH_INTK_SCHD21 = lib.read_sql(spark, _conn, table="EMS_PAL_PRH_INTK_SCHD")
        
        logger.info("Step: read_EMS_PAL_PRH_INTK_SCHD2")
        # Reading Data From Source - read_EMS_PAL_PRH_INTK_SCHD2
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_EMS_PAL_PRH_INTK_SCHD2 = lib.read_sql(spark, _conn, table="EMS_PAL_PRH_INTK_SCHD")
        
        logger.info("Step: read_EMS_PAL_PRH_INTK_SCHD")
        # Reading Data From Source - read_EMS_PAL_PRH_INTK_SCHD
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_EMS_PAL_PRH_INTK_SCHD = lib.read_sql(spark, _conn, table="EMS_PAL_PRH_INTK_SCHD")
        
        logger.info("Step: apply_SQ_EMS_PAL_PRH_INTK_SCHD1")
        # Source Qualifier: apply_SQ_EMS_PAL_PRH_INTK_SCHD1
        df_SQ_EMS_PAL_PRH_INTK_SCHD1 = df_EMS_PAL_PRH_INTK_SCHD1
        # Select only SQ output ports (matches Informatica behavior) — missing ports become lit(None)
        _port_cols = ["HSE_SRVC_APLY_KEY", "CUST_KEY", "ALCT_HSE_UNIT_KEY", "INTL_INTK_DATE", "ALCT_HSE_UNIT_CODE_ADDR", "CUST_INTK_DATE", "TNT_SPCL_NEED_IND", "DPST_AMT", "FRST_RENT_AMT", "INTK_SCHD_INPT_USER_ID", "INTK_SCHD_INPT_DATE", "INTK_SCHD_TYPE_CODE", "INTK_SCHD_STS_CODE", "INTK_RVN_TXN_NUM", "LAST_INTK_SCHD_UPD_DATE", "INTK_SCHD_CATG_CODE", "TNT_RENT_CODE", "INTK_HSE_EST_KEY", "TNCY_AGRMT_CMNC_DATE", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID", "INTL_INTK_TIME", "ORIG_CUST_KEY", "ORIG_HSE_SRVC_APLY_KEY", "PND_TNT_RENT_CODE", "PND_TNT_RENT_CODE_BGN_DATE", "DPST_RCPT_NUM", "DPST_RCPT_TYPE_CODE", "HSE_EST_KEY", "IH_INTK_DATE", "INTK_CLCT_TXN_NUM", "INTK_RENT_AMT", "INTK_SCHD_RMK_TEXT", "INTK_TYPE_CODE", "NEXT_RENT_BGN_DATE", "NEXT_RENT_FCTR_CODE", "OFR_DATE", "OFR_LTR_INTK_DATE", "OFR_LTR_ISS_DATE", "OFR_SEQ_NUM", "PREV_CUST_KEY", "PREV_HSE_SRVC_APLY_KEY", "PRH_APLY_NUM", "RENT_BGN_DATE", "RENT_FCTR_CODE", "RENT_FREE_INTL_BGN_DATE", "RENT_FREE_PHASE_CNT", "RENT_FREE_PRD_CODE", "RENT_FREE_TFR_DBR_END_DATE", "RENT_FREE_TYPE_CODE", "RENT_RVW_CATG_BGN_DATE", "RENT_RVW_CATG_CODE", "RVS_NEXT_RENT_BGN_DATE", "RVS_NEXT_RENT_FCTR_CODE", "RVS_RENT_BGN_DATE", "RVS_RENT_FCTR_CODE", "RVS_RENT_RVW_CATG_BGN_DATE", "RVS_RENT_RVW_CATG_CODE", "FWD_FROM_PREV_RENT_IND", "INTL_DOC_DATE", "RVS_DOC_DATE", "RVS_FWD_FROM_PREV_RENT_IND", "RVS_INTK_DATE"]
        df_SQ_EMS_PAL_PRH_INTK_SCHD1 = df_SQ_EMS_PAL_PRH_INTK_SCHD1.select([col(c) if c.lower() in [x.lower() for x in df_SQ_EMS_PAL_PRH_INTK_SCHD1.columns] else lit(None).alias(c) for c in _port_cols])
        ctx.register_df("df_SQ_EMS_PAL_PRH_INTK_SCHD1", df_SQ_EMS_PAL_PRH_INTK_SCHD1)
        
        logger.info("Step: apply_SQ_EMS_PAL_PRH_INTK_SCHD21")
        # Source Qualifier: apply_SQ_EMS_PAL_PRH_INTK_SCHD21
        df_SQ_EMS_PAL_PRH_INTK_SCHD21 = df_EMS_PAL_PRH_INTK_SCHD21
        # Select only SQ output ports (matches Informatica behavior) — missing ports become lit(None)
        _port_cols = ["HSE_SRVC_APLY_KEY", "CUST_KEY", "ALCT_HSE_UNIT_KEY", "INTL_INTK_DATE", "ALCT_HSE_UNIT_CODE_ADDR", "CUST_INTK_DATE", "TNT_SPCL_NEED_IND", "DPST_AMT", "FRST_RENT_AMT", "INTK_SCHD_INPT_USER_ID", "INTK_SCHD_INPT_DATE", "INTK_SCHD_TYPE_CODE", "INTK_SCHD_STS_CODE", "INTK_RVN_TXN_NUM", "LAST_INTK_SCHD_UPD_DATE", "INTK_SCHD_CATG_CODE", "TNT_RENT_CODE", "INTK_HSE_EST_KEY", "TNCY_AGRMT_CMNC_DATE", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID", "INTL_INTK_TIME", "ORIG_CUST_KEY", "ORIG_HSE_SRVC_APLY_KEY", "PND_TNT_RENT_CODE", "PND_TNT_RENT_CODE_BGN_DATE", "DPST_RCPT_NUM", "DPST_RCPT_TYPE_CODE", "HSE_EST_KEY", "IH_INTK_DATE", "INTK_CLCT_TXN_NUM", "INTK_RENT_AMT", "INTK_SCHD_RMK_TEXT", "INTK_TYPE_CODE", "NEXT_RENT_BGN_DATE", "NEXT_RENT_FCTR_CODE", "OFR_DATE", "OFR_LTR_INTK_DATE", "OFR_LTR_ISS_DATE", "OFR_SEQ_NUM", "PREV_CUST_KEY", "PREV_HSE_SRVC_APLY_KEY", "PRH_APLY_NUM", "RENT_BGN_DATE", "RENT_FCTR_CODE", "RENT_FREE_INTL_BGN_DATE", "RENT_FREE_PHASE_CNT", "RENT_FREE_PRD_CODE", "RENT_FREE_TFR_DBR_END_DATE", "RENT_FREE_TYPE_CODE", "RENT_RVW_CATG_BGN_DATE", "RENT_RVW_CATG_CODE", "RVS_NEXT_RENT_BGN_DATE", "RVS_NEXT_RENT_FCTR_CODE", "RVS_RENT_BGN_DATE", "RVS_RENT_FCTR_CODE", "RVS_RENT_RVW_CATG_BGN_DATE", "RVS_RENT_RVW_CATG_CODE", "FWD_FROM_PREV_RENT_IND", "INTL_DOC_DATE", "RVS_DOC_DATE", "RVS_FWD_FROM_PREV_RENT_IND", "RVS_INTK_DATE"]
        df_SQ_EMS_PAL_PRH_INTK_SCHD21 = df_SQ_EMS_PAL_PRH_INTK_SCHD21.select([col(c) if c.lower() in [x.lower() for x in df_SQ_EMS_PAL_PRH_INTK_SCHD21.columns] else lit(None).alias(c) for c in _port_cols])
        ctx.register_df("df_SQ_EMS_PAL_PRH_INTK_SCHD21", df_SQ_EMS_PAL_PRH_INTK_SCHD21)
        
        logger.info("Step: apply_SQ_EMS_PAL_PRH_INTK_SCHD2")
        # Source Qualifier: apply_SQ_EMS_PAL_PRH_INTK_SCHD2
        df_SQ_EMS_PAL_PRH_INTK_SCHD2 = df_EMS_PAL_PRH_INTK_SCHD2
        # Select only SQ output ports (matches Informatica behavior) — missing ports become lit(None)
        _port_cols = ["HSE_SRVC_APLY_KEY", "CUST_KEY", "ALCT_HSE_UNIT_KEY", "INTL_INTK_DATE", "ALCT_HSE_UNIT_CODE_ADDR", "CUST_INTK_DATE", "TNT_SPCL_NEED_IND", "DPST_AMT", "FRST_RENT_AMT", "INTK_SCHD_INPT_USER_ID", "INTK_SCHD_INPT_DATE", "INTK_SCHD_TYPE_CODE", "INTK_SCHD_STS_CODE", "INTK_RVN_TXN_NUM", "LAST_INTK_SCHD_UPD_DATE", "INTK_SCHD_CATG_CODE", "TNT_RENT_CODE", "INTK_HSE_EST_KEY", "TNCY_AGRMT_CMNC_DATE", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID", "INTL_INTK_TIME", "ORIG_CUST_KEY", "ORIG_HSE_SRVC_APLY_KEY", "PND_TNT_RENT_CODE", "PND_TNT_RENT_CODE_BGN_DATE", "DPST_RCPT_NUM", "DPST_RCPT_TYPE_CODE", "HSE_EST_KEY", "IH_INTK_DATE", "INTK_CLCT_TXN_NUM", "INTK_RENT_AMT", "INTK_SCHD_RMK_TEXT", "INTK_TYPE_CODE", "NEXT_RENT_BGN_DATE", "NEXT_RENT_FCTR_CODE", "OFR_DATE", "OFR_LTR_INTK_DATE", "OFR_LTR_ISS_DATE", "OFR_SEQ_NUM", "PREV_CUST_KEY", "PREV_HSE_SRVC_APLY_KEY", "PRH_APLY_NUM", "RENT_BGN_DATE", "RENT_FCTR_CODE", "RENT_FREE_INTL_BGN_DATE", "RENT_FREE_PHASE_CNT", "RENT_FREE_PRD_CODE", "RENT_FREE_TFR_DBR_END_DATE", "RENT_FREE_TYPE_CODE", "RENT_RVW_CATG_BGN_DATE", "RENT_RVW_CATG_CODE", "RVS_NEXT_RENT_BGN_DATE", "RVS_NEXT_RENT_FCTR_CODE", "RVS_RENT_BGN_DATE", "RVS_RENT_FCTR_CODE", "RVS_RENT_RVW_CATG_BGN_DATE", "RVS_RENT_RVW_CATG_CODE", "FWD_FROM_PREV_RENT_IND", "INTL_DOC_DATE", "RVS_DOC_DATE", "RVS_FWD_FROM_PREV_RENT_IND", "RVS_INTK_DATE"]
        df_SQ_EMS_PAL_PRH_INTK_SCHD2 = df_SQ_EMS_PAL_PRH_INTK_SCHD2.select([col(c) if c.lower() in [x.lower() for x in df_SQ_EMS_PAL_PRH_INTK_SCHD2.columns] else lit(None).alias(c) for c in _port_cols])
        ctx.register_df("df_SQ_EMS_PAL_PRH_INTK_SCHD2", df_SQ_EMS_PAL_PRH_INTK_SCHD2)
        
        logger.info("Step: apply_SQ_EMS_PAL_PRH_INTK_SCHD")
        # Source Qualifier: apply_SQ_EMS_PAL_PRH_INTK_SCHD
        df_SQ_EMS_PAL_PRH_INTK_SCHD = df_EMS_PAL_PRH_INTK_SCHD
        # Select only SQ output ports (matches Informatica behavior) — missing ports become lit(None)
        _port_cols = ["HSE_SRVC_APLY_KEY", "CUST_KEY", "ALCT_HSE_UNIT_KEY", "INTL_INTK_DATE", "ALCT_HSE_UNIT_CODE_ADDR", "CUST_INTK_DATE", "TNT_SPCL_NEED_IND", "DPST_AMT", "FRST_RENT_AMT", "INTK_SCHD_INPT_USER_ID", "INTK_SCHD_INPT_DATE", "INTK_SCHD_TYPE_CODE", "INTK_SCHD_STS_CODE", "INTK_RVN_TXN_NUM", "LAST_INTK_SCHD_UPD_DATE", "INTK_SCHD_CATG_CODE", "TNT_RENT_CODE", "INTK_HSE_EST_KEY", "TNCY_AGRMT_CMNC_DATE", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID", "INTL_INTK_TIME", "ORIG_CUST_KEY", "ORIG_HSE_SRVC_APLY_KEY", "PND_TNT_RENT_CODE", "PND_TNT_RENT_CODE_BGN_DATE", "DPST_RCPT_NUM", "DPST_RCPT_TYPE_CODE", "HSE_EST_KEY", "IH_INTK_DATE", "INTK_CLCT_TXN_NUM", "INTK_RENT_AMT", "INTK_SCHD_RMK_TEXT", "INTK_TYPE_CODE", "NEXT_RENT_BGN_DATE", "NEXT_RENT_FCTR_CODE", "OFR_DATE", "OFR_LTR_INTK_DATE", "OFR_LTR_ISS_DATE", "OFR_SEQ_NUM", "PREV_CUST_KEY", "PREV_HSE_SRVC_APLY_KEY", "PRH_APLY_NUM", "RENT_BGN_DATE", "RENT_FCTR_CODE", "RENT_FREE_INTL_BGN_DATE", "RENT_FREE_PHASE_CNT", "RENT_FREE_PRD_CODE", "RENT_FREE_TFR_DBR_END_DATE", "RENT_FREE_TYPE_CODE", "RENT_RVW_CATG_BGN_DATE", "RENT_RVW_CATG_CODE", "RVS_NEXT_RENT_BGN_DATE", "RVS_NEXT_RENT_FCTR_CODE", "RVS_RENT_BGN_DATE", "RVS_RENT_FCTR_CODE", "RVS_RENT_RVW_CATG_BGN_DATE", "RVS_RENT_RVW_CATG_CODE", "FWD_FROM_PREV_RENT_IND", "INTL_DOC_DATE", "RVS_DOC_DATE", "RVS_FWD_FROM_PREV_RENT_IND", "RVS_INTK_DATE", "MRST_SNSH_IND", "SNSH_OFR_LTR_ISS_DATE", "SNSH_INTL_DOC_DATE", "SNSH_INTK_RENT_AMT", "SNSH_INTK_DPST_AMT", "SNSH_MTH_RENT_AMT", "SNSH_MKT_RENT_AMT", "SNSH_MKT_RATE_AMT", "SNSH_MKT_MGT_FEE_AMT", "INTK_SCHD_CRE_DATE", "RENT_EXMPT_IND"]
        df_SQ_EMS_PAL_PRH_INTK_SCHD = df_SQ_EMS_PAL_PRH_INTK_SCHD.select([col(c) if c.lower() in [x.lower() for x in df_SQ_EMS_PAL_PRH_INTK_SCHD.columns] else lit(None).alias(c) for c in _port_cols])
        ctx.register_df("df_SQ_EMS_PAL_PRH_INTK_SCHD", df_SQ_EMS_PAL_PRH_INTK_SCHD)
        
        logger.info("Step: apply_Union_Transformation2")
        # Union: apply_Union_Transformation2
        df_Union_Transformation2 = df_SQ_EMS_PAL_PRH_INTK_SCHD1
        # Select only union output columns (add lit(None) for any missing)
        for _col in ["RENT_FCTR_CODE"]:
            if _col.lower() not in [x.lower() for x in df_Union_Transformation2.columns]:
                df_Union_Transformation2 = df_Union_Transformation2.withColumn(_col, lit(None))
        df_Union_Transformation2 = df_Union_Transformation2.select("RENT_FCTR_CODE")
        ctx.register_df("df_Union_Transformation2", df_Union_Transformation2)
        
        logger.info("Step: apply_Union_Transformation1")
        # Union: apply_Union_Transformation1
        df_Union_Transformation1 = df_SQ_EMS_PAL_PRH_INTK_SCHD21
        # Select only union output columns (add lit(None) for any missing)
        for _col in ["RENT_RVW_CATG_CODE"]:
            if _col.lower() not in [x.lower() for x in df_Union_Transformation1.columns]:
                df_Union_Transformation1 = df_Union_Transformation1.withColumn(_col, lit(None))
        df_Union_Transformation1 = df_Union_Transformation1.select("RENT_RVW_CATG_CODE")
        ctx.register_df("df_Union_Transformation1", df_Union_Transformation1)
        
        logger.info("Step: apply_EXPTRANS3")
        # Expression: apply_EXPTRANS3
        df_EXPTRANS3 = df_SQ_EMS_PAL_PRH_INTK_SCHD2
        df_EXPTRANS3 = df_EXPTRANS3.withColumn("CUST_APLY_BK", expr("lpad(CUST_KEY,9,'0') || lpad(HSE_SRVC_APLY_KEY,15,'0')"))
        df_EXPTRANS3 = df_EXPTRANS3.withColumn("PREV_CUST_APLY_BK", expr("lpad(PREV_CUST_KEY,9,'0') || lpad(PREV_HSE_SRVC_APLY_KEY,15,'0')"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_EXPTRANS3", df_EXPTRANS3)
        
        logger.info("Step: apply_EXPTRANS")
        # Expression: apply_EXPTRANS
        df_EXPTRANS = df_SQ_EMS_PAL_PRH_INTK_SCHD
        df_EXPTRANS = df_EXPTRANS.withColumn("DUMMY", expr("NULL"))
        df_EXPTRANS = df_EXPTRANS.withColumn("DUMMY_DATE", expr("NULL"))
        df_EXPTRANS = df_EXPTRANS.withColumn("CUST_APLY_BK", expr("lpad(CUST_KEY,9,'0') || lpad(HSE_SRVC_APLY_KEY,15,'0')"))
        df_EXPTRANS = df_EXPTRANS.withColumn("PREV_CUST_APLY_BK", expr("lpad(PREV_CUST_KEY,9,'0') || lpad(PREV_HSE_SRVC_APLY_KEY,15,'0')"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["INTL_INTK_DATE", "ALCT_HSE_UNIT_CODE_ADDR", "CUST_INTK_DATE", "ALCT_HSE_UNIT_KEY", "TNT_SPCL_NEED_IND", "DPST_AMT", "FRST_RENT_AMT", "INTK_SCHD_INPT_USER_ID", "INTK_SCHD_INPT_DATE", "INTK_SCHD_TYPE_CODE", "INTK_SCHD_STS_CODE", "INTK_RVN_TXN_NUM", "LAST_INTK_SCHD_UPD_DATE", "INTK_SCHD_CATG_CODE", "TNT_RENT_CODE", "INTK_HSE_EST_KEY", "TNCY_AGRMT_CMNC_DATE", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID", "INTL_INTK_TIME", "ORIG_CUST_KEY", "ORIG_HSE_SRVC_APLY_KEY", "PND_TNT_RENT_CODE", "PND_TNT_RENT_CODE_BGN_DATE", "DPST_RCPT_NUM", "DPST_RCPT_TYPE_CODE", "HSE_EST_KEY", "IH_INTK_DATE", "INTK_CLCT_TXN_NUM", "INTK_RENT_AMT", "INTK_SCHD_RMK_TEXT", "INTK_TYPE_CODE", "NEXT_RENT_BGN_DATE", "NEXT_RENT_FCTR_CODE", "OFR_DATE", "OFR_LTR_INTK_DATE", "OFR_LTR_ISS_DATE", "OFR_SEQ_NUM", "PRH_APLY_NUM", "RENT_BGN_DATE", "RENT_FCTR_CODE", "RENT_FREE_INTL_BGN_DATE", "RENT_FREE_PHASE_CNT", "RENT_FREE_PRD_CODE", "RENT_FREE_TFR_DBR_END_DATE", "RENT_FREE_TYPE_CODE", "RENT_RVW_CATG_BGN_DATE", "RENT_RVW_CATG_CODE", "RVS_NEXT_RENT_BGN_DATE", "RVS_NEXT_RENT_FCTR_CODE", "RVS_RENT_BGN_DATE", "RVS_RENT_FCTR_CODE", "RVS_RENT_RVW_CATG_BGN_DATE", "RVS_RENT_RVW_CATG_CODE", "FWD_FROM_PREV_RENT_IND", "INTL_DOC_DATE", "RVS_DOC_DATE", "RVS_FWD_FROM_PREV_RENT_IND", "RVS_INTK_DATE", "MRST_SNSH_IND", "SNSH_OFR_LTR_ISS_DATE", "SNSH_INTL_DOC_DATE", "SNSH_INTK_RENT_AMT", "SNSH_INTK_DPST_AMT", "SNSH_MTH_RENT_AMT", "SNSH_MKT_RENT_AMT", "SNSH_MKT_RATE_AMT", "SNSH_MKT_MGT_FEE_AMT", "INTK_SCHD_CRE_DATE", "RENT_EXMPT_IND"]:
            if _col.lower() not in [x.lower() for x in df_EXPTRANS.columns]:
                df_EXPTRANS = df_EXPTRANS.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_EXPTRANS", df_EXPTRANS)
        
        logger.info("Step: apply_FILTRANS3")
        # Filter: apply_FILTRANS3
        __fil_input = df_Union_Transformation2
        df_FILTRANS3 = __fil_input.filter(expr("NOT ((RENT_FCTR_CODE IS NULL))"))
        ctx.register_df("df_FILTRANS3", df_FILTRANS3)

        logger.info("Step: apply_FILTRANS31")
        # Filter: apply_FILTRANS31
        __fil_input = df_Union_Transformation1
        df_FILTRANS31 = __fil_input.filter(expr("NOT ((RENT_RVW_CATG_CODE IS NULL))"))
        ctx.register_df("df_FILTRANS31", df_FILTRANS31)

        logger.info("Step: apply_Union_Transformation")
        # Union: apply_Union_Transformation
        df_Union_Transformation = df_EXPTRANS3
        # Select only union output columns (add lit(None) for any missing)
        for _col in ["CUST_APLY_BK"]:
            if _col.lower() not in [x.lower() for x in df_Union_Transformation.columns]:
                df_Union_Transformation = df_Union_Transformation.withColumn(_col, lit(None))
        df_Union_Transformation = df_Union_Transformation.select("CUST_APLY_BK")
        ctx.register_df("df_Union_Transformation", df_Union_Transformation)
        
        logger.info("Step: read_LKP_PREV_CUST_APLY_KEY")
        # Reading Data From Source - read_LKP_PREV_CUST_APLY_KEY
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SOR_EMS_CPM_CUST_APLY.CUST_APLY_KEY as CUST_APLY_KEY, 
SOR_EMS_CPM_CUST_APLY.CUST_KEY as CUST_KEY, 
SOR_EMS_CPM_CUST_APLY.HSE_SRVC_APLY_KEY as HSE_SRVC_APLY_KEY, SOR_EMS_CPM_CUST_APLY.CUST_APLY_BK as CUST_APLY_BK 
FROM SOR_EMS_CPM_CUST_APLY
union
SELECT SSA_EMS_CPM_CUST_APLY.CUST_APLY_KEY as CUST_APLY_KEY, 
nvl(SSA_EMS_CPM_CUST_APLY.CUST_KEY,0) as CUST_KEY, 
nvl(SSA_EMS_CPM_CUST_APLY.HSE_SRVC_APLY_KEY,0) as HSE_SRVC_APLY_KEY, SSA_EMS_CPM_CUST_APLY.CUST_APLY_BK as CUST_APLY_BK 
FROM SSA_EMS_CPM_CUST_APLY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_PREV_CUST_APLY_KEY = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_PREV_CUST_APLY_KEY")
        # Lookup: apply_LKP_PREV_CUST_APLY_KEY
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_PREV_CUST_APLY_KEY = df_LKP_PREV_CUST_APLY_KEY.dropDuplicates(subset=["CUST_APLY_BK"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_EXPTRANS
        _lkp_input = _lkp_input.withColumn("CUST_APLY_BK1", col("PREV_CUST_APLY_BK"))
        # Join condition: CUST_APLY_BK1=CUST_APLY_BK
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_PREV_CUST_APLY_KEY).alias("_lkp"),
            (col("_main.CUST_APLY_BK1") == col("_lkp.CUST_APLY_BK")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_PREV_CUST_APLY_KEY[c] for c in df_LKP_PREV_CUST_APLY_KEY.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        ctx.register_df("df_lkp_merge_EXPTRANS", df_lkp_merge_EXPTRANS)        
        logger.info("Step: read_LKP_RVS_NEXT_RENT_FCTR_KEY")
        # Reading Data From Source - read_LKP_RVS_NEXT_RENT_FCTR_KEY
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_KEY as RENT_FCTR_KEY, SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_CODE as RENT_FCTR_CODE FROM SOR_EMS_SRF_RENT_FCTR_CODE
UNION 
SELECT SSA_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_KEY as RENT_FCTR_KEY, SSA_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_CODE as RENT_FCTR_CODE FROM SSA_EMS_SRF_RENT_FCTR_CODE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_RVS_NEXT_RENT_FCTR_KEY = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_RVS_NEXT_RENT_FCTR_KEY")
        # Lookup: apply_LKP_RVS_NEXT_RENT_FCTR_KEY
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_RVS_NEXT_RENT_FCTR_KEY = df_LKP_RVS_NEXT_RENT_FCTR_KEY.dropDuplicates(subset=["RENT_FCTR_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_EXPTRANS
        _lkp_input = _lkp_input.withColumn("RENT_FCTR_CODE_IN", col("RVS_NEXT_RENT_FCTR_CODE"))
        # Join condition: RENT_FCTR_CODE_IN=RENT_FCTR_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_RVS_NEXT_RENT_FCTR_KEY).alias("_lkp"),
            (col("_main.RENT_FCTR_CODE_IN") == col("_lkp.RENT_FCTR_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_RVS_NEXT_RENT_FCTR_KEY[c] for c in df_LKP_RVS_NEXT_RENT_FCTR_KEY.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: read_LKP_RENT_FCTR_KEY")
        # Reading Data From Source - read_LKP_RENT_FCTR_KEY
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_KEY as RENT_FCTR_KEY, SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_CODE as RENT_FCTR_CODE FROM SOR_EMS_SRF_RENT_FCTR_CODE
UNION 
SELECT SSA_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_KEY as RENT_FCTR_KEY, SSA_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_CODE as RENT_FCTR_CODE FROM SSA_EMS_SRF_RENT_FCTR_CODE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_RENT_FCTR_KEY = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_RENT_FCTR_KEY")
        # Lookup: apply_LKP_RENT_FCTR_KEY
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_RENT_FCTR_KEY = df_LKP_RENT_FCTR_KEY.dropDuplicates(subset=["RENT_FCTR_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_EXPTRANS
        _lkp_input = _lkp_input.withColumn("RENT_FCTR_CODE_IN", col("RENT_FCTR_CODE"))
        # Join condition: RENT_FCTR_CODE_IN=RENT_FCTR_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_RENT_FCTR_KEY).alias("_lkp"),
            (col("_main.RENT_FCTR_CODE_IN") == col("_lkp.RENT_FCTR_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_RENT_FCTR_KEY[c] for c in df_LKP_RENT_FCTR_KEY.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: read_LKP_NEXT_RENT_FCTR_KEY")
        # Reading Data From Source - read_LKP_NEXT_RENT_FCTR_KEY
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_KEY as RENT_FCTR_KEY, SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_CODE as RENT_FCTR_CODE FROM SOR_EMS_SRF_RENT_FCTR_CODE
UNION 
SELECT SSA_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_KEY as RENT_FCTR_KEY, SSA_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_CODE as RENT_FCTR_CODE FROM SSA_EMS_SRF_RENT_FCTR_CODE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_NEXT_RENT_FCTR_KEY = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_NEXT_RENT_FCTR_KEY")
        # Lookup: apply_LKP_NEXT_RENT_FCTR_KEY
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_NEXT_RENT_FCTR_KEY = df_LKP_NEXT_RENT_FCTR_KEY.dropDuplicates(subset=["RENT_FCTR_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_EXPTRANS
        _lkp_input = _lkp_input.withColumn("RENT_FCTR_CODE_IN", col("NEXT_RENT_FCTR_CODE"))
        # Join condition: RENT_FCTR_CODE_IN=RENT_FCTR_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_NEXT_RENT_FCTR_KEY).alias("_lkp"),
            (col("_main.RENT_FCTR_CODE_IN") == col("_lkp.RENT_FCTR_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_NEXT_RENT_FCTR_KEY[c] for c in df_LKP_NEXT_RENT_FCTR_KEY.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: read_LKP_CUST_APLY_KEY")
        # Reading Data From Source - read_LKP_CUST_APLY_KEY
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SOR_EMS_CPM_CUST_APLY.CUST_APLY_KEY as CUST_APLY_KEY, 
SOR_EMS_CPM_CUST_APLY.CUST_KEY as CUST_KEY, 
SOR_EMS_CPM_CUST_APLY.HSE_SRVC_APLY_KEY as HSE_SRVC_APLY_KEY, SOR_EMS_CPM_CUST_APLY.CUST_APLY_BK as CUST_APLY_BK 
FROM SOR_EMS_CPM_CUST_APLY
union
SELECT SSA_EMS_CPM_CUST_APLY.CUST_APLY_KEY as CUST_APLY_KEY, 
nvl(SSA_EMS_CPM_CUST_APLY.CUST_KEY,0) as CUST_KEY, 
nvl(SSA_EMS_CPM_CUST_APLY.HSE_SRVC_APLY_KEY,0) as HSE_SRVC_APLY_KEY, SSA_EMS_CPM_CUST_APLY.CUST_APLY_BK as CUST_APLY_BK 
FROM SSA_EMS_CPM_CUST_APLY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_CUST_APLY_KEY = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_CUST_APLY_KEY")
        # Lookup: apply_LKP_CUST_APLY_KEY
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_CUST_APLY_KEY = df_LKP_CUST_APLY_KEY.dropDuplicates(subset=["CUST_APLY_BK"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_EXPTRANS
        _lkp_input = _lkp_input.withColumn("CUST_APLY_BK1", col("CUST_APLY_BK"))
        # Join condition: CUST_APLY_BK1=CUST_APLY_BK
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_CUST_APLY_KEY).alias("_lkp"),
            (col("_main.CUST_APLY_BK1") == col("_lkp.CUST_APLY_BK")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_CUST_APLY_KEY[c] for c in df_LKP_CUST_APLY_KEY.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: read_LKP_RENT_RVW_CATG_CODE")
        # Reading Data From Source - read_LKP_RENT_RVW_CATG_CODE
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SOR_EMS_RENT_RVW_CATG_CODE.RENT_RVW_CATG_KEY as RENT_RVW_CATG_KEY, SOR_EMS_RENT_RVW_CATG_CODE.RENT_RVW_CATG_CODE as RENT_RVW_CATG_CODE FROM SOR_EMS_RENT_RVW_CATG_CODE
union 
SELECT SSA_EMS_RENT_RVW_CATG_CODE.RENT_RVW_CATG_KEY as RENT_RVW_CATG_KEY, SSA_EMS_RENT_RVW_CATG_CODE.RENT_RVW_CATG_CODE as RENT_RVW_CATG_CODE FROM SSA_EMS_RENT_RVW_CATG_CODE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_RENT_RVW_CATG_CODE = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_RENT_RVW_CATG_CODE")
        # Lookup: apply_LKP_RENT_RVW_CATG_CODE
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_RENT_RVW_CATG_CODE = df_LKP_RENT_RVW_CATG_CODE.dropDuplicates(subset=["RENT_RVW_CATG_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_EXPTRANS
        _lkp_input = _lkp_input.withColumn("RENT_RVW_CATG_CODE1", col("RENT_RVW_CATG_CODE"))
        # Join condition: RENT_RVW_CATG_CODE1=RENT_RVW_CATG_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_RENT_RVW_CATG_CODE).alias("_lkp"),
            (col("_main.RENT_RVW_CATG_CODE1") == col("_lkp.RENT_RVW_CATG_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_RENT_RVW_CATG_CODE[c] for c in df_LKP_RENT_RVW_CATG_CODE.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: read_LKP_RVS_RENT_RVW_CATG_CODE")
        # Reading Data From Source - read_LKP_RVS_RENT_RVW_CATG_CODE
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SOR_EMS_RENT_RVW_CATG_CODE.RENT_RVW_CATG_KEY as RENT_RVW_CATG_KEY, SOR_EMS_RENT_RVW_CATG_CODE.RENT_RVW_CATG_CODE as RENT_RVW_CATG_CODE FROM SOR_EMS_RENT_RVW_CATG_CODE
union 
SELECT SSA_EMS_RENT_RVW_CATG_CODE.RENT_RVW_CATG_KEY as RENT_RVW_CATG_KEY, SSA_EMS_RENT_RVW_CATG_CODE.RENT_RVW_CATG_CODE as RENT_RVW_CATG_CODE FROM SSA_EMS_RENT_RVW_CATG_CODE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_RVS_RENT_RVW_CATG_CODE = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_RVS_RENT_RVW_CATG_CODE")
        # Lookup: apply_LKP_RVS_RENT_RVW_CATG_CODE
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_RVS_RENT_RVW_CATG_CODE = df_LKP_RVS_RENT_RVW_CATG_CODE.dropDuplicates(subset=["RENT_RVW_CATG_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_EXPTRANS
        _lkp_input = _lkp_input.withColumn("RENT_RVW_CATG_CODE1", col("RVS_RENT_RVW_CATG_CODE"))
        # Join condition: RENT_RVW_CATG_CODE1=RENT_RVW_CATG_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_RVS_RENT_RVW_CATG_CODE).alias("_lkp"),
            (col("_main.RENT_RVW_CATG_CODE1") == col("_lkp.RENT_RVW_CATG_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_RVS_RENT_RVW_CATG_CODE[c] for c in df_LKP_RVS_RENT_RVW_CATG_CODE.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: read_LKP_RVS_RENT_FCTR_KEY")
        # Reading Data From Source - read_LKP_RVS_RENT_FCTR_KEY
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_KEY as RENT_FCTR_KEY, SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_CODE as RENT_FCTR_CODE FROM SOR_EMS_SRF_RENT_FCTR_CODE
UNION 
SELECT SSA_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_KEY as RENT_FCTR_KEY, SSA_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_CODE as RENT_FCTR_CODE FROM SSA_EMS_SRF_RENT_FCTR_CODE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_RVS_RENT_FCTR_KEY = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_RVS_RENT_FCTR_KEY")
        # Lookup: apply_LKP_RVS_RENT_FCTR_KEY
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_RVS_RENT_FCTR_KEY = df_LKP_RVS_RENT_FCTR_KEY.dropDuplicates(subset=["RENT_FCTR_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_lkp_merge_EXPTRANS
        _lkp_input = _lkp_input.withColumn("RENT_FCTR_CODE_IN", col("RVS_RENT_FCTR_CODE"))
        # Join condition: RENT_FCTR_CODE_IN=RENT_FCTR_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_EXPTRANS = _lkp_input.alias("_main").join(
            broadcast(df_LKP_RVS_RENT_FCTR_KEY).alias("_lkp"),
            (col("_main.RENT_FCTR_CODE_IN") == col("_lkp.RENT_FCTR_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_RVS_RENT_FCTR_KEY[c] for c in df_LKP_RVS_RENT_FCTR_KEY.columns if c.lower() not in [x.lower() for x in _lkp_input.columns]]
        )
        
        logger.info("Step: input_MPLT_AGMT_EMS_RENT_FCTR")
        # Expression: input_MPLT_AGMT_EMS_RENT_FCTR
        df_MPLT_AGMT_EMS_RENT_FCTR_input = df_FILTRANS3
        df_MPLT_AGMT_EMS_RENT_FCTR_input = df_MPLT_AGMT_EMS_RENT_FCTR_input.withColumn("IN_BK", expr("RENT_FCTR_CODE"))
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR_input", df_MPLT_AGMT_EMS_RENT_FCTR_input)
        
        logger.info("Step: rename_EXP_NULL_BKEY")
        # Expression: rename_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_RENT_FCTR_input
        __expr_renames = [
            ("IN_BK", "IN_BKEY"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_NULL_BKEY.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_NULL_BKEY)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_FCTR_EXP_NULL_BKEY")
        # Expression: apply_MPLT_AGMT_EMS_RENT_FCTR_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RENT_FCTR_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RENT_FCTR_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_RENT_FCTR_EXP_NULL_BKEY.withColumn("OUT_BKEY", expr("CASE WHEN IN_BKEY IS NULL THEN 0 ELSE IN_BKEY END"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_RENT_FCTR_EXP_NULL_BKEY)
        
        logger.info("Step: rename_EXPTRANS")
        # Expression: rename_EXPTRANS
        df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS = df_MPLT_AGMT_EMS_RENT_FCTR_EXP_NULL_BKEY
        __expr_renames = [
            ("OUT_BKEY", "IN_CUST_BK"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS = df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS", df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS")
        # Expression: apply_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS
        df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS = df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS
        df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS = df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS.withColumn("IN_DUMMY", expr("NULL"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["IN_CUST_BK"]:
            if _col.lower() not in [x.lower() for x in df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS.columns]:
                df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS = df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS", df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS)
        
        logger.info("Step: read_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SOR_EMS_SRF_RENT_FCTR_CODE")
        # Reading Data From Source - read_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SOR_EMS_SRF_RENT_FCTR_CODE
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "target")
        query = f"""SELECT SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_KEY as RENT_FCTR_KEY, NULL as DUMMY, SOR_EMS_SRF_RENT_FCTR_CODE.RENT_FCTR_CODE as RENT_FCTR_CODE FROM SOR_EMS_SRF_RENT_FCTR_CODE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SOR_EMS_SRF_RENT_FCTR_CODE = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SOR_EMS_SRF_RENT_FCTR_CODE")
        # Lookup: apply_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SOR_EMS_SRF_RENT_FCTR_CODE
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS
        df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SOR_EMS_SRF_RENT_FCTR_CODE,
            name='MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SOR_EMS_SRF_RENT_FCTR_CODE',
            join_predicates=[{'source_col': 'IN_CUST_BK', 'lookup_col': 'RENT_FCTR_CODE'}],
            output_columns=['RENT_FCTR_KEY', 'RENT_FCTR_CODE', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'RENT_FCTR_KEY', 'ref_field': 'Sequence-Id', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'integer'},
                {'name': 'RENT_FCTR_CODE', 'ref_field': 'IN_CUST_BK', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'decimal'},
                {'name': 'DUMMY', 'ref_field': 'IN_DUMMY', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SOR_EMS_SRF_RENT_FCTR_CODE',
            sequence_config={'output_col': 'RENT_FCTR_KEY'},
            insert_else_update=True,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS", df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS)
        
        logger.info("Step: rename_EXP_SK")
        # Expression: rename_EXP_SK
        df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_SK = df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS
        __expr_renames = [
            ("NewLookupRow_LKP_DYN_SOR_EMS_SRF_RENT_FCTR_CODE", "SOR_CACHE_STATUS"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_SK = df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_SK.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_SK", df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_SK)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK")
        # Expression: apply_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK
        df_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK = df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXP_SK
        df_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK = df_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK.withColumn("OUT_TABLE_NAME", expr("'SSA_EMS_SRF_RENT_FCTR_CODE'"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["SOR_CACHE_STATUS", "RENT_FCTR_KEY", "RENT_FCTR_CODE", "DUMMY"]:
            if _col.lower() not in [x.lower() for x in df_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK.columns]:
                df_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK = df_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK", df_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK)
        
        logger.info("Step: read_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SSA_EMS_SRF_RENT_FCTR_CODE")
        # Reading Data From Source - read_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SSA_EMS_SRF_RENT_FCTR_CODE
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "source_db")
        query = f"""SELECT CUST_KEY as SURROGATE_KEY, 'S' as DUMMY  FROM SSA_EMS_CPM_CUST"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SSA_EMS_SRF_RENT_FCTR_CODE = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SSA_EMS_SRF_RENT_FCTR_CODE")
        # Lookup: apply_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SSA_EMS_SRF_RENT_FCTR_CODE
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK
        df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SSA_EMS_SRF_RENT_FCTR_CODE,
            name='MPLT_AGMT_EMS_RENT_FCTR_LKP_DYN_SSA_EMS_SRF_RENT_FCTR_CODE',
            join_predicates=[{'source_col': 'RENT_FCTR_KEY', 'lookup_col': 'SURROGATE_KEY'}],
            output_columns=['SURROGATE_KEY', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'SURROGATE_KEY', 'ref_field': 'RENT_FCTR_KEY', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'decimal'},
                {'name': 'DUMMY', 'ref_field': 'OUT_TABLE_NAME', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SSA_EMS_SRF_RENT_FCTR_CODE',
            sequence_config=None,
            insert_else_update=False,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK", df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK)
        
        logger.info("Step: rename_EXPTRANS1")
        # Expression: rename_EXPTRANS1
        df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS1 = df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_FCTR_EXP_SK
        __expr_renames = [
            ("NewLookupRow_LKP_DYN_SSA_EMS_SRF_RENT_FCTR_CODE", "SSA_CACHE_STATUS"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS1.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS1", df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1")
        # Expression: apply_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1
        df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_FCTR_rename_EXPTRANS1
        df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1.withColumn("V_AUG_IND", expr("CASE WHEN SOR_CACHE_STATUS = 1 THEN 'Y' ELSE 'N' END"))
        df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1.withColumn("OPR_IND", expr("'A'"))
        df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1.withColumn("LAST_REC_TXN_TYPE_CODE", expr("NULL"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["SOR_CACHE_STATUS", "RENT_FCTR_KEY", "RENT_FCTR_CODE"]:
            if _col.lower() not in [x.lower() for x in df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1.columns]:
                df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1", df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_FCTR")
        # Expression: apply_MPLT_AGMT_EMS_RENT_FCTR
        df_MPLT_AGMT_EMS_RENT_FCTR = df_MPLT_AGMT_EMS_RENT_FCTR_EXPTRANS1
        __expr_renames = [
            ("SOR_CACHE_STATUS", "OUT_DLPK_SOR_CACHE"),
            ("V_AUG_IND", "OUT_AUG_IND"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_RENT_FCTR = df_MPLT_AGMT_EMS_RENT_FCTR.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_FCTR", df_MPLT_AGMT_EMS_RENT_FCTR)
        
        logger.info("Step: input_MPLT_AGMT_EMS_RENT_RVW_CATG")
        # Expression: input_MPLT_AGMT_EMS_RENT_RVW_CATG
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_input = df_FILTRANS31
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_input = df_MPLT_AGMT_EMS_RENT_RVW_CATG_input.withColumn("IN_BK", expr("RENT_RVW_CATG_CODE"))
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_RVW_CATG_input", df_MPLT_AGMT_EMS_RENT_RVW_CATG_input)
        
        logger.info("Step: rename_EXP_NULL_BKEY")
        # Expression: rename_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_RENT_RVW_CATG_input
        __expr_renames = [
            ("IN_BK", "IN_BKEY"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_NULL_BKEY.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_NULL_BKEY)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_NULL_BKEY")
        # Expression: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_NULL_BKEY.withColumn("OUT_BKEY", expr("CASE WHEN IN_BKEY IS NULL THEN 'UNKNOWN' WHEN IN_BKEY = '' THEN 'UNKNOWN' ELSE IN_BKEY END"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_NULL_BKEY)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS")
        # Expression: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS.withColumn("IN_DUMMY", expr("NULL"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["OUT_BKEY"]:
            if _col.lower() not in [x.lower() for x in df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS.columns]:
                df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS", df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS)
        
        logger.info("Step: read_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SOR_EMS_RENT_RVW_CATG_CODE")
        # Reading Data From Source - read_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SOR_EMS_RENT_RVW_CATG_CODE
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "target")
        query = f"""SELECT RENT_RVW_CATG_KEY as RENT_RVW_CATG_KEY, RENT_RVW_CATG_CODE as RENT_RVW_CATG_CODE, NULL as DUMMY from SOR_EMS_RENT_RVW_CATG_CODE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SOR_EMS_RENT_RVW_CATG_CODE = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SOR_EMS_RENT_RVW_CATG_CODE")
        # Lookup: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SOR_EMS_RENT_RVW_CATG_CODE
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS
        df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SOR_EMS_RENT_RVW_CATG_CODE,
            name='MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SOR_EMS_RENT_RVW_CATG_CODE',
            join_predicates=[{'source_col': 'OUT_BKEY', 'lookup_col': 'RENT_RVW_CATG_CODE'}],
            output_columns=['RENT_RVW_CATG_KEY', 'RENT_RVW_CATG_CODE', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'RENT_RVW_CATG_KEY', 'ref_field': 'Sequence-Id', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'integer'},
                {'name': 'RENT_RVW_CATG_CODE', 'ref_field': 'OUT_BKEY', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'string'},
                {'name': 'DUMMY', 'ref_field': 'IN_DUMMY', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SOR_EMS_RENT_RVW_CATG_CODE',
            sequence_config={'output_col': 'RENT_RVW_CATG_KEY'},
            insert_else_update=True,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS", df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS)
        
        logger.info("Step: rename_EXP_SK")
        # Expression: rename_EXP_SK
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_SK = df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS
        __expr_renames = [
            ("NewLookupRow_LKP_DYN_SOR_EMS_RENT_RVW_CATG_CODE", "SOR_CACHE_STATUS"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_SK = df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_SK.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_SK", df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_SK)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK")
        # Expression: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK = df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXP_SK
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK.withColumn("OUT_TABLE_NAME", expr("'SSA_EMS_RENT_RVW_CATG_CODE'"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["SOR_CACHE_STATUS", "RENT_RVW_CATG_KEY", "RENT_RVW_CATG_CODE", "DUMMY"]:
            if _col.lower() not in [x.lower() for x in df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK.columns]:
                df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK", df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK)
        
        logger.info("Step: read_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SSA_EMS_RENT_RVW_CATG_CODE")
        # Reading Data From Source - read_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SSA_EMS_RENT_RVW_CATG_CODE
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "source_db")
        query = f"""SELECT CUST_KEY as SURROGATE_KEY, 'S' as DUMMY  FROM SSA_EMS_CPM_CUST"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SSA_EMS_RENT_RVW_CATG_CODE = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SSA_EMS_RENT_RVW_CATG_CODE")
        # Lookup: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SSA_EMS_RENT_RVW_CATG_CODE
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK
        df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SSA_EMS_RENT_RVW_CATG_CODE,
            name='MPLT_AGMT_EMS_RENT_RVW_CATG_LKP_DYN_SSA_EMS_RENT_RVW_CATG_CODE',
            join_predicates=[{'source_col': 'RENT_RVW_CATG_KEY', 'lookup_col': 'SURROGATE_KEY'}],
            output_columns=['SURROGATE_KEY', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'SURROGATE_KEY', 'ref_field': 'RENT_RVW_CATG_KEY', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'decimal'},
                {'name': 'DUMMY', 'ref_field': 'OUT_TABLE_NAME', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SSA_EMS_RENT_RVW_CATG_CODE',
            sequence_config=None,
            insert_else_update=False,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK", df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK)
        
        logger.info("Step: rename_EXPTRANS1")
        # Expression: rename_EXPTRANS1
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXPTRANS1 = df_mplt_lkp_chain_MPLT_AGMT_EMS_RENT_RVW_CATG_EXP_SK
        __expr_renames = [
            ("NewLookupRow_LKP_DYN_SSA_EMS_RENT_RVW_CATG_CODE", "SSA_CACHE_STATUS"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXPTRANS1.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXPTRANS1", df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1")
        # Expression: apply_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_RVW_CATG_rename_EXPTRANS1
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1.withColumn("V_AUG_IND", expr("CASE WHEN SOR_CACHE_STATUS = 1 THEN 'Y' ELSE 'N' END"))
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1.withColumn("OPR_IND", expr("'A'"))
        df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1.withColumn("LAST_REC_TXN_TYPE_CODE", expr("NULL"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["SOR_CACHE_STATUS", "RENT_RVW_CATG_KEY", "RENT_RVW_CATG_CODE"]:
            if _col.lower() not in [x.lower() for x in df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1.columns]:
                df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1 = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1", df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RENT_RVW_CATG")
        # Expression: apply_MPLT_AGMT_EMS_RENT_RVW_CATG
        df_MPLT_AGMT_EMS_RENT_RVW_CATG = df_MPLT_AGMT_EMS_RENT_RVW_CATG_EXPTRANS1
        __expr_renames = [
            ("SOR_CACHE_STATUS", "OUT_DLPK_SOR_CACHE"),
            ("V_AUG_IND", "OUT_AUG_IND"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_RENT_RVW_CATG = df_MPLT_AGMT_EMS_RENT_RVW_CATG.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_RENT_RVW_CATG", df_MPLT_AGMT_EMS_RENT_RVW_CATG)
        
        logger.info("Step: apply_FILTRANS32")
        # Filter: apply_FILTRANS32
        __fil_input = df_Union_Transformation
        df_FILTRANS32 = __fil_input.filter(expr("NOT ((CUST_APLY_BK IS NULL))"))
        ctx.register_df("df_FILTRANS32", df_FILTRANS32)

        logger.info("Step: apply_FILTRANS23")
        # Filter: apply_FILTRANS23
        __fil_input = df_MPLT_AGMT_EMS_RENT_FCTR
        df_FILTRANS23 = __fil_input.filter(expr("OUT_DLPK_SOR_CACHE = 1"))
        ctx.register_df("df_FILTRANS23", df_FILTRANS23)

        logger.info("Step: apply_FILTRANS24")
        # Filter: apply_FILTRANS24
        __fil_input = df_MPLT_AGMT_EMS_RENT_RVW_CATG
        df_FILTRANS24 = __fil_input.filter(expr("OUT_DLPK_SOR_CACHE = 1"))
        ctx.register_df("df_FILTRANS24", df_FILTRANS24)

        logger.info("Step: input_MPLT_AGMT_EMS_CPM_CUST_APLY")
        # Expression: input_MPLT_AGMT_EMS_CPM_CUST_APLY
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_input = df_FILTRANS32
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_input = df_MPLT_AGMT_EMS_CPM_CUST_APLY_input.withColumn("IN_CUST_APLY_BK", expr("CUST_APLY_BK"))
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY_input", df_MPLT_AGMT_EMS_CPM_CUST_APLY_input)
        
        logger.info("Step: rename_EXP_NULL_BKEY")
        # Expression: rename_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_CPM_CUST_APLY_input
        __expr_renames = [
            ("IN_CUST_APLY_BK", "IN_BKEY"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_NULL_BKEY.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_NULL_BKEY)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_NULL_BKEY")
        # Expression: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_NULL_BKEY = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_NULL_BKEY.withColumn("OUT_BKEY", expr("CASE WHEN ltrim(rtrim(IN_BKEY)) IS NULL THEN 'UNKNOWN' WHEN ltrim(rtrim(IN_BKEY)) = '' THEN 'UNKNOWN' ELSE IN_BKEY END"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_NULL_BKEY)
        
        logger.info("Step: rename_EXPTRANS")
        # Expression: rename_EXPTRANS
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_NULL_BKEY
        __expr_renames = [
            ("OUT_BKEY", "IN_CUST_APLY_BK"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS = df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS", df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS")
        # Expression: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS = df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS.withColumn("IN_CUST_KEY", expr("NULL"))
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS.withColumn("IN_HSE_SRVC_APLY_KEY", expr("NULL"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["IN_CUST_APLY_BK"]:
            if _col.lower() not in [x.lower() for x in df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS.columns]:
                df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS", df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS)
        
        logger.info("Step: read_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SOR_EMS_CPM_CUST_APLY")
        # Reading Data From Source - read_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SOR_EMS_CPM_CUST_APLY
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "target")
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SOR_EMS_CPM_CUST_APLY = lib.read_sql(spark, _conn, table="SOR_EMS_CPM_CUST_APLY")
        
        logger.info("Step: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SOR_EMS_CPM_CUST_APLY")
        # Lookup: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SOR_EMS_CPM_CUST_APLY
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS
        df_mplt_lkp_chain_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SOR_EMS_CPM_CUST_APLY,
            name='MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SOR_EMS_CPM_CUST_APLY',
            join_predicates=[{'source_col': 'IN_CUST_APLY_BK', 'lookup_col': 'CUST_APLY_BK'}],
            output_columns=['CUST_APLY_KEY', 'CUST_APLY_BK', 'CUST_KEY', 'HSE_SRVC_APLY_KEY'],
            lookup_output_fields=[
                {'name': 'CUST_APLY_KEY', 'ref_field': 'Sequence-Id', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'integer'},
                {'name': 'CUST_APLY_BK', 'ref_field': 'IN_CUST_APLY_BK', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'string'},
                {'name': 'CUST_KEY', 'ref_field': 'IN_CUST_KEY', 'ignore_in_compare': False, 'ignore_null_inputs': True, 'datatype': 'decimal'},
                {'name': 'HSE_SRVC_APLY_KEY', 'ref_field': 'IN_HSE_SRVC_APLY_KEY', 'ignore_in_compare': False, 'ignore_null_inputs': True, 'datatype': 'decimal'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SOR_EMS_CPM_CUST_APLY',
            sequence_config={'output_col': 'CUST_APLY_KEY'},
            insert_else_update=True,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS", df_mplt_lkp_chain_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS)
        
        logger.info("Step: rename_EXP_SK")
        # Expression: rename_EXP_SK
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_SK = df_mplt_lkp_chain_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS
        __expr_renames = [
            ("NewLookupRow_LKP_DYN_SOR_EMS_CPM_CUST_APLY", "SOR_CACHE_STATUS"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_SK = df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_SK.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_SK", df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_SK)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK")
        # Expression: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK = df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXP_SK
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK.withColumn("OUT_TABLE_NAME", expr("'SSA_EMS_CPM_CUST_APLY'"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["SOR_CACHE_STATUS", "CUST_APLY_KEY", "CUST_APLY_BK", "CUST_KEY", "HSE_SRVC_APLY_KEY"]:
            if _col.lower() not in [x.lower() for x in df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK.columns]:
                df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK", df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK)
        
        logger.info("Step: read_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SSA_EMS_CPM_CUST_APLY")
        # Reading Data From Source - read_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SSA_EMS_CPM_CUST_APLY
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "source_db")
        query = f"""SELECT CUST_APLY_KEY as SURROGATE_KEY, 'S' as DUMMY  FROM SSA_EMS_CPM_CUST_APLY"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SSA_EMS_CPM_CUST_APLY = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SSA_EMS_CPM_CUST_APLY")
        # Lookup: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SSA_EMS_CPM_CUST_APLY
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK
        df_mplt_lkp_chain_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SSA_EMS_CPM_CUST_APLY,
            name='MPLT_AGMT_EMS_CPM_CUST_APLY_LKP_DYN_SSA_EMS_CPM_CUST_APLY',
            join_predicates=[{'source_col': 'CUST_APLY_KEY', 'lookup_col': 'SURROGATE_KEY'}],
            output_columns=['SURROGATE_KEY', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'SURROGATE_KEY', 'ref_field': 'CUST_APLY_KEY', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'decimal'},
                {'name': 'DUMMY', 'ref_field': 'OUT_TABLE_NAME', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SSA_EMS_CPM_CUST_APLY',
            sequence_config=None,
            insert_else_update=False,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK", df_mplt_lkp_chain_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK)
        
        logger.info("Step: rename_EXPTRANS1")
        # Expression: rename_EXPTRANS1
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS1 = df_mplt_lkp_chain_MPLT_AGMT_EMS_CPM_CUST_APLY_EXP_SK
        __expr_renames = [
            ("NewLookupRow_LKP_DYN_SSA_EMS_CPM_CUST_APLY", "SSA_CACHE_STATUS"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS1 = df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS1.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS1", df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1")
        # Expression: apply_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1 = df_MPLT_AGMT_EMS_CPM_CUST_APLY_rename_EXPTRANS1
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1 = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1.withColumn("V_AUG_IND", expr("CASE WHEN SOR_CACHE_STATUS = 1 THEN 'Y' ELSE 'N' END"))
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1 = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1.withColumn("OPR_IND", expr("'A'"))
        df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1 = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1.withColumn("LAST_REC_TXN_TYPE_CODE", expr("NULL"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["SOR_CACHE_STATUS", "CUST_APLY_KEY", "CUST_APLY_BK", "CUST_KEY", "HSE_SRVC_APLY_KEY"]:
            if _col.lower() not in [x.lower() for x in df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1.columns]:
                df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1 = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1", df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_CPM_CUST_APLY")
        # Expression: apply_MPLT_AGMT_EMS_CPM_CUST_APLY
        df_MPLT_AGMT_EMS_CPM_CUST_APLY = df_MPLT_AGMT_EMS_CPM_CUST_APLY_EXPTRANS1
        __expr_renames = [
            ("SOR_CACHE_STATUS", "OUT_DLPK_SOR_CACHE"),
            ("V_AUG_IND", "OUT_AUG_IND"),
        ]
        for _old, _new in __expr_renames:
            df_MPLT_AGMT_EMS_CPM_CUST_APLY = df_MPLT_AGMT_EMS_CPM_CUST_APLY.drop(_new).withColumnRenamed(_old, _new)
        ctx.register_df("df_MPLT_AGMT_EMS_CPM_CUST_APLY", df_MPLT_AGMT_EMS_CPM_CUST_APLY)
        
        logger.info("Step: apply_EXPTRANS21")
        # Expression: apply_EXPTRANS21
        df_EXPTRANS21 = df_FILTRANS23
        df_EXPTRANS21 = df_EXPTRANS21.withColumn("LAST_REC_TXN_DATE", expr("current_timestamp()"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["OUT_DLPK_SOR_CACHE"]:
            if _col.lower() not in [x.lower() for x in df_EXPTRANS21.columns]:
                df_EXPTRANS21 = df_EXPTRANS21.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_EXPTRANS21", df_EXPTRANS21)
        
        logger.info("Step: apply_EXPTRANS24")
        # Expression: apply_EXPTRANS24
        df_EXPTRANS24 = df_FILTRANS24
        df_EXPTRANS24 = df_EXPTRANS24.withColumn("LAST_REC_TXN_DATE", expr("current_timestamp()"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["OUT_DLPK_SOR_CACHE"]:
            if _col.lower() not in [x.lower() for x in df_EXPTRANS24.columns]:
                df_EXPTRANS24 = df_EXPTRANS24.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_EXPTRANS24", df_EXPTRANS24)
        
        logger.info("Step: apply_FILTRANS21")
        # Filter: apply_FILTRANS21
        __fil_input = df_MPLT_AGMT_EMS_CPM_CUST_APLY
        df_FILTRANS21 = __fil_input.filter(expr("OUT_DLPK_SOR_CACHE = 1"))
        ctx.register_df("df_FILTRANS21", df_FILTRANS21)

        logger.info("Step: write_SSA_EMS_SRF_RENT_FCTR_CODE")
        # Write to Target: write_SSA_EMS_SRF_RENT_FCTR_CODE
        df_write = df_EXPTRANS21
        # Map source columns to target columns using connector field map (handles name
        # mismatches) — done BEFORE the _update_flag split so UPDATE/DELETE use target
        # column names in batch_update/batch_delete.
        _field_map = {"AGMT_IND": "OUT_AUG_IND"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col.lower() not in [x.lower() for x in df_write.columns] and _src_col.lower() in [x.lower() for x in df_write.columns]:
                # Drop any column that would conflict case-insensitively with the target name 
                for _c in list(df_write.columns):
                    if _c.lower() == _tgt_col.lower() and _c != _src_col:
                        df_write = df_write.drop(_c)
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("SOR_DATE", lit(None).cast(StringType()))
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['RENT_FCTR_KEY', 'RENT_FCTR_CODE', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'AGMT_IND', 'OPR_IND', 'SOR_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col.lower() in [x.lower() for x in df_write.columns]])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "SSA_EMS_SRF_RENT_FCTR_CODE", mode="append")

        logger.info("write_SSA_EMS_SRF_RENT_FCTR_CODE write completed")
        logger.info("Step: write_SSA_EMS_RENT_RVW_CATG_CODE")
        # Write to Target: write_SSA_EMS_RENT_RVW_CATG_CODE
        df_write = df_EXPTRANS24
        # Map source columns to target columns using connector field map (handles name
        # mismatches) — done BEFORE the _update_flag split so UPDATE/DELETE use target
        # column names in batch_update/batch_delete.
        _field_map = {"AGMT_IND": "OUT_AUG_IND"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col.lower() not in [x.lower() for x in df_write.columns] and _src_col.lower() in [x.lower() for x in df_write.columns]:
                # Drop any column that would conflict case-insensitively with the target name 
                for _c in list(df_write.columns):
                    if _c.lower() == _tgt_col.lower() and _c != _src_col:
                        df_write = df_write.drop(_c)
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("SOR_DATE", lit(None).cast(StringType()))
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['RENT_RVW_CATG_KEY', 'RENT_RVW_CATG_CODE', 'AGMT_IND', 'OPR_IND', 'SOR_DATE', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col.lower() in [x.lower() for x in df_write.columns]])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "SSA_EMS_RENT_RVW_CATG_CODE", mode="append")

        logger.info("write_SSA_EMS_RENT_RVW_CATG_CODE write completed")
        logger.info("Step: apply_EXPTRANS22")
        # Expression: apply_EXPTRANS22
        df_EXPTRANS22 = df_FILTRANS21
        df_EXPTRANS22 = df_EXPTRANS22.withColumn("LAST_REC_TXN_DATE", expr("current_timestamp()"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["OUT_DLPK_SOR_CACHE"]:
            if _col.lower() not in [x.lower() for x in df_EXPTRANS22.columns]:
                df_EXPTRANS22 = df_EXPTRANS22.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_EXPTRANS22", df_EXPTRANS22)
        
        logger.info("Step: write_SSA_EMS_CPM_CUST_APLY")
        # Write to Target: write_SSA_EMS_CPM_CUST_APLY
        df_write = df_EXPTRANS22
        # Map source columns to target columns using connector field map (handles name
        # mismatches) — done BEFORE the _update_flag split so UPDATE/DELETE use target
        # column names in batch_update/batch_delete.
        _field_map = {"AGMT_IND": "OUT_AUG_IND"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col.lower() not in [x.lower() for x in df_write.columns] and _src_col.lower() in [x.lower() for x in df_write.columns]:
                # Drop any column that would conflict case-insensitively with the target name 
                for _c in list(df_write.columns):
                    if _c.lower() == _tgt_col.lower() and _c != _src_col:
                        df_write = df_write.drop(_c)
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("CUST_BK", lit(None).cast(StringType()))
        df_write = df_write.withColumn("SOR_DATE", lit(None).cast(StringType()))
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['CUST_KEY', 'CUST_BK', 'AGMT_IND', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'OPR_IND', 'SOR_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col.lower() in [x.lower() for x in df_write.columns]])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "SSA_EMS_CPM_CUST", mode="append")

        logger.info("write_SSA_EMS_CPM_CUST_APLY write completed")
        
        metrics.complete()
        logger.info("Mapping M_EMS_SSAL2_TRANS_PAL_PRH_INTK_SCHD completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_EMS_SSAL2_TRANS_PAL_PRH_INTK_SCHD FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_EMS_SSAL2_TRANS_PAL_PRH_INTK_SCHD", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_EMS_SSAL2_TRANS_PAL_PRH_INTK_SCHD")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())