'''
* Script - M_EMS_SSAL2_TRANS_SEC_ORG_UNIT_COST_CTR.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_EMS_SSAL2_TRANS_SEC_ORG_UNIT_COST_CTR mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_EMS_SSAL2_TRANS_SEC_ORG_UNIT_COST_CTR")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_EMS_SSAL2_TRANS_SEC_ORG_UNIT_COST_CTR", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "SSA")

    v_snsh_date = ""
    v_init_flag = ""
    # Load mapping variables from the UTL_JOB_PARAM file (shared helper)
    _vars = lib.load_mapping_variables(config, [ "$$v_snsh_date",  "$$v_init_flag", ], logger)
    v_snsh_date = _vars.get("v_snsh_date", v_snsh_date)
    v_init_flag = _vars.get("v_init_flag", v_init_flag)
    
    try:
        logger.info("Step: read_EMS_SEC_ORG_UNIT_MGT_COST_CTR")
        # Reading Data From Source - read_EMS_SEC_ORG_UNIT_MGT_COST_CTR
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_EMS_SEC_ORG_UNIT_MGT_COST_CTR = lib.read_sql(spark, _conn, table="EMS_SEC_ORG_UNIT_MGT_COST_CTR")
        
        logger.info("Step: apply_SQ_EMS_SEC_ORG_UNIT_MGT_COST_CTR")
        # Source Qualifier: apply_SQ_EMS_SEC_ORG_UNIT_MGT_COST_CTR
        df_SQ_EMS_SEC_ORG_UNIT_MGT_COST_CTR = df_EMS_SEC_ORG_UNIT_MGT_COST_CTR
        df_SQ_EMS_SEC_ORG_UNIT_MGT_COST_CTR = lib.sq_output(
            input_df=df_SQ_EMS_SEC_ORG_UNIT_MGT_COST_CTR,
            port_cols={
                'COST_CTR_CODE': 'string',
                'BSNS_ACTV_CODE': 'string',
                'ORG_UNIT_KEY': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'LAST_REC_TXN_USER_ID': 'string',
                'COST_CTR_TNCY_TYPE_CODE': 'string',
            },
        )
        ctx.register_df("df_SQ_EMS_SEC_ORG_UNIT_MGT_COST_CTR", df_SQ_EMS_SEC_ORG_UNIT_MGT_COST_CTR)
        
        logger.info("Step: apply_EXPTRANS")
        # Expression: apply_EXPTRANS
        df_EXPTRANS = lib.expression(
            input_df=df_SQ_EMS_SEC_ORG_UNIT_MGT_COST_CTR,
            computed_columns=[
                {'name': 'DUMMY_HSE_EST_KEY', 'expr': 'NULL'},
                {'name': 'DUMMY_HSE_DSTR_KEY', 'expr': 'NULL'},
                {'name': 'DUMMY', 'expr': 'NULL'},
                {'name': 'DUMMY_DATE', 'expr': 'NULL'}
            ],
        )
        ctx.register_df("df_EXPTRANS", df_EXPTRANS)
        
        logger.info("Step: input_MPLT_AGMT_EMS_RVC_COST_CTR")
        # Expression: input_MPLT_AGMT_EMS_RVC_COST_CTR
        df_MPLT_AGMT_EMS_RVC_COST_CTR_input = lib.expression(
            input_df=df_EXPTRANS,
            computed_columns=[
                {'name': 'IN_COST_CTR_BSNS_ACTV_CODE', 'expr': 'BSNS_ACTV_CODE'},
                {'name': 'IN_COST_CTR_BK', 'expr': 'COST_CTR_CODE'}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR_input", df_MPLT_AGMT_EMS_RVC_COST_CTR_input)
        
        logger.info("Step: rename_EXP_NULL_BKEY")
        # Expression: rename_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXP_NULL_BKEY = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVC_COST_CTR_input,
            rename_columns=[
                ('IN_COST_CTR_BK', 'IN_SHORT_BKEY')
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXP_NULL_BKEY)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_NULL_BKEY")
        # Expression: apply_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_NULL_BKEY = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXP_NULL_BKEY,
            computed_columns=[
                {'name': 'OUT_BKEY', 'expr': "CASE WHEN ltrim(rtrim(IN_BKEY)) IS NULL THEN 'UNKNOWN' WHEN ltrim(rtrim(IN_BKEY)) = '' THEN 'UNKNOWN' ELSE IN_BKEY END"},
                {'name': 'OUT_SHORT_BKEY', 'expr': "CASE WHEN ltrim(rtrim(IN_SHORT_BKEY)) IS NULL THEN '?' WHEN ltrim(rtrim(IN_SHORT_BKEY)) = '' THEN '?' ELSE IN_SHORT_BKEY END"}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_NULL_BKEY)
        
        logger.info("Step: rename_EXPTRANS")
        # Expression: rename_EXPTRANS
        df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXPTRANS = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_NULL_BKEY,
            rename_columns=[
                ('OUT_SHORT_BKEY', 'IN_COST_CTR_CODE')
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXPTRANS", df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXPTRANS)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS")
        # Expression: apply_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS
        df_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXPTRANS,
            computed_columns=[
                {'name': 'DUMMY', 'expr': "'1'"}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS", df_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS)
        
        logger.info("Step: read_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SOR_RVC_COST_CTR")
        # Reading Data From Source - read_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SOR_RVC_COST_CTR
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "source_db")
        query = f"""SELECT
COST_CTR_KEY AS COST_CTR_KEY,
COST_CTR_CODE AS COST_CTR_CODE,
COST_CTR_BSNS_ACTV_CODE AS COST_CTR_BSNS_ACTV_CODE
FROM SOR_RVC_COST_CTR
WHERE COST_CTR_CODE IS NOT NULL"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SOR_RVC_COST_CTR = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SOR_RVC_COST_CTR")
        # Lookup: apply_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SOR_RVC_COST_CTR
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS
        df_mplt_lkp_chain_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SOR_RVC_COST_CTR,
            name='MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SOR_RVC_COST_CTR',
            join_predicates=[{'source_col': 'IN_COST_CTR_CODE', 'lookup_col': 'COST_CTR_CODE'}, {'source_col': 'IN_COST_CTR_BSNS_ACTV_CODE', 'lookup_col': 'COST_CTR_BSNS_ACTV_CODE'}],
            output_columns=['COST_CTR_KEY', 'COST_CTR_CODE', 'COST_CTR_BSNS_ACTV_CODE'],
            lookup_output_fields=[
                {'name': 'COST_CTR_KEY', 'ref_field': 'Sequence-Id', 'ignore_in_compare': False, 'ignore_null_inputs': True, 'datatype': 'integer'},
                {'name': 'COST_CTR_CODE', 'ref_field': 'IN_COST_CTR_CODE', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'string'},
                {'name': 'COST_CTR_BSNS_ACTV_CODE', 'ref_field': 'IN_COST_CTR_BSNS_ACTV_CODE', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SOR_RVC_COST_CTR',
            sequence_config={'output_col': 'COST_CTR_KEY'},
            insert_else_update=False,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS", df_mplt_lkp_chain_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS)
        
        logger.info("Step: rename_EXP_SK")
        # Expression: rename_EXP_SK
        df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXP_SK = lib.expression(
            input_df=df_mplt_lkp_chain_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS,
            rename_columns=[
                ('NewLookupRow_LKP_DYN_SOR_RVC_COST_CTR', 'SOR_CACHE_STATUS'),
                ('COST_CTR_KEY', 'SOR_COST_CTR_KEY')
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXP_SK", df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXP_SK)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK")
        # Expression: apply_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK
        df_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXP_SK,
            computed_columns=[
                {'name': 'OUT_TABLE_NAME', 'expr': "'SSA_RVC_COST_CTR'"},
                {'name': 'COST_CTR_KEY', 'expr': 'SOR_COST_CTR_KEY'}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK", df_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK)
        
        logger.info("Step: read_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SSA_RVC_COST_CTR")
        # Reading Data From Source - read_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SSA_RVC_COST_CTR
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "source_db")
        query = f"""SELECT COST_CTR_KEY as SURROGATE_KEY, 'S' as DUMMY  FROM SSA_RVC_COST_CTR"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SSA_RVC_COST_CTR = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SSA_RVC_COST_CTR")
        # Lookup: apply_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SSA_RVC_COST_CTR
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK
        df_mplt_lkp_chain_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SSA_RVC_COST_CTR,
            name='MPLT_AGMT_EMS_RVC_COST_CTR_LKP_DYN_SSA_RVC_COST_CTR',
            join_predicates=[{'source_col': 'COST_CTR_KEY', 'lookup_col': 'SURROGATE_KEY'}],
            output_columns=['SURROGATE_KEY', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'SURROGATE_KEY', 'ref_field': 'COST_CTR_KEY', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'decimal'},
                {'name': 'DUMMY', 'ref_field': 'OUT_TABLE_NAME', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SSA_RVC_COST_CTR',
            sequence_config=None,
            insert_else_update=False,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK", df_mplt_lkp_chain_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK)
        
        logger.info("Step: rename_EXPTRANS1")
        # Expression: rename_EXPTRANS1
        df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXPTRANS1 = lib.expression(
            input_df=df_mplt_lkp_chain_MPLT_AGMT_EMS_RVC_COST_CTR_EXP_SK,
            rename_columns=[
                ('NewLookupRow_LKP_DYN_SSA_RVC_COST_CTR', 'IN_DLPK_SSA_CACHE'),
                ('SOR_CACHE_STATUS', 'IN_DLPK_SOR_CACHE'),
                ('IN_COST_CTR_CODE', 'COST_CTR_CODE'),
                ('IN_COST_CTR_BSNS_ACTV_CODE', 'COST_CTR_BSNS_ACTV_CODE')
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXPTRANS1", df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS1")
        # Expression: apply_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS1
        df_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS1 = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVC_COST_CTR_rename_EXPTRANS1,
            computed_columns=[
                {'name': 'V_AUG_IND', 'expr': "CASE WHEN IN_DLPK_SOR_CACHE = 1 THEN 'Y' ELSE 'N' END"},
                {'name': 'OPR_IND', 'expr': "'A'"},
                {'name': 'LAST_REC_TXN_TYPE_CODE', 'expr': 'NULL'},
                {'name': 'DUMMY_KEY', 'expr': '0'}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS1", df_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVC_COST_CTR")
        # Expression: apply_MPLT_AGMT_EMS_RVC_COST_CTR
        df_MPLT_AGMT_EMS_RVC_COST_CTR = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVC_COST_CTR_EXPTRANS1,
            rename_columns=[
                ('IN_DLPK_SOR_CACHE', 'OUT_DLPK_SOR_CACHE'),
                ('V_AUG_IND', 'OUT_AUG_IND')
            ],
            pass_through_cols=['OUT_DLPK_SOR_CACHE', 'OUT_AUG_IND', 'OPR_IND', 'LAST_REC_TXN_TYPE_CODE', 'COST_CTR_KEY', 'COST_CTR_CODE', 'COST_CTR_BSNS_ACTV_CODE'],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVC_COST_CTR", df_MPLT_AGMT_EMS_RVC_COST_CTR)
        
        logger.info("Step: input_MPLT_AGMT_EMS_RVN_CLCT_OFFC")
        # Expression: input_MPLT_AGMT_EMS_RVN_CLCT_OFFC
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_input = lib.expression(
            input_df=df_EXPTRANS,
            computed_columns=[
                {'name': 'IN_CLCT_OFFC_BK', 'expr': 'ORG_UNIT_KEY'}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_input", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_input)
        
        logger.info("Step: rename_EXP_NULL_BKEY")
        # Expression: rename_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXP_NULL_BKEY = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_input,
            rename_columns=[
                ('IN_CLCT_OFFC_BK', 'IN_SHORT_BKEY')
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXP_NULL_BKEY)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_NULL_BKEY")
        # Expression: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_NULL_BKEY
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_NULL_BKEY = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXP_NULL_BKEY,
            computed_columns=[
                {'name': 'OUT_BKEY', 'expr': "CASE WHEN ltrim(rtrim(IN_BKEY)) IS NULL THEN 'UNKNOWN' WHEN ltrim(rtrim(IN_BKEY)) = '' THEN 'UNKNOWN' ELSE IN_BKEY END"},
                {'name': 'OUT_SHORT_BKEY', 'expr': "CASE WHEN ltrim(rtrim(IN_SHORT_BKEY)) IS NULL THEN '?' WHEN ltrim(rtrim(IN_SHORT_BKEY)) = '' THEN '?' ELSE IN_SHORT_BKEY END"}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_NULL_BKEY", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_NULL_BKEY)
        
        logger.info("Step: rename_EXPTRANS")
        # Expression: rename_EXPTRANS
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXPTRANS = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_NULL_BKEY,
            rename_columns=[
                ('OUT_SHORT_BKEY', 'IN_RVN_CLCT_OFFC_BK')
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXPTRANS", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXPTRANS)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS")
        # Expression: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXPTRANS,
            computed_columns=[
                {'name': 'RVN_CLCT_OFFC_KEY', 'expr': 'NULL'},
                {'name': 'DUMMY', 'expr': 'NULL'}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS)
        
        logger.info("Step: read_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SOR_EMS_RVC_RVN_CLCT_OFFC")
        # Reading Data From Source - read_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SOR_EMS_RVC_RVN_CLCT_OFFC
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "target")
        query = f"""SELECT
 CLCT_OFFC_KEY as  CLCT_OFFC_KEY , 
NULL as DUMMY, 
RVN_CLCT_OFFC_KEY  as RVN_CLCT_OFFC_KEY 
from SOR_EMS_RVC_RVN_CLCT_OFFC
where last_rec_txn_type_code is null"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SOR_EMS_RVC_RVN_CLCT_OFFC = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SOR_EMS_RVC_RVN_CLCT_OFFC")
        # Lookup: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SOR_EMS_RVC_RVN_CLCT_OFFC
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS
        df_mplt_lkp_chain_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SOR_EMS_RVC_RVN_CLCT_OFFC,
            name='MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SOR_EMS_RVC_RVN_CLCT_OFFC',
            join_predicates=[{'source_col': 'IN_RVN_CLCT_OFFC_BK', 'lookup_col': 'RVN_CLCT_OFFC_KEY'}],
            output_columns=['CLCT_OFFC_KEY', 'RVN_CLCT_OFFC_KEY', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'CLCT_OFFC_KEY', 'ref_field': 'Sequence-Id', 'ignore_in_compare': False, 'ignore_null_inputs': True, 'datatype': 'integer'},
                {'name': 'RVN_CLCT_OFFC_KEY', 'ref_field': 'IN_RVN_CLCT_OFFC_BK', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'string'},
                {'name': 'DUMMY', 'ref_field': 'DUMMY', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SOR_EMS_RVC_RVN_CLCT_OFFC',
            sequence_config={'output_col': 'CLCT_OFFC_KEY'},
            insert_else_update=False,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS", df_mplt_lkp_chain_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS)
        
        logger.info("Step: rename_EXP_SK")
        # Expression: rename_EXP_SK
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXP_SK = lib.expression(
            input_df=df_mplt_lkp_chain_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS,
            rename_columns=[
                ('IN_RVN_CLCT_OFFC_BK', 'IN_RVN_CLCT_OFFC_KEY'),
                ('NewLookupRow_LKP_DYN_SOR_EMS_RVC_RVN_CLCT_OFFC', 'SOR_CACHE_STATUS'),
                ('CLCT_OFFC_KEY', 'SOR_CLCT_OFFC_KEY')
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXP_SK", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXP_SK)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK")
        # Expression: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXP_SK,
            computed_columns=[
                {'name': 'OUT_TABLE_NAME', 'expr': "'SSA_EMS_RVC_RVN_CLCT_OFFC'"},
                {'name': 'CLCT_OFFC_KEY', 'expr': 'SOR_CLCT_OFFC_KEY'}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK)
        
        logger.info("Step: read_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SSA_EMS_RVC_RVN_CLCT_OFFC")
        # Reading Data From Source - read_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SSA_EMS_RVC_RVN_CLCT_OFFC
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "source_db")
        query = f"""SELECT 
CLCT_OFFC_KEY as SURROGATE_KEY, 
'S' as DUMMY  
FROM SSA_EMS_RVC_RVN_CLCT_OFFC"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SSA_EMS_RVC_RVN_CLCT_OFFC = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SSA_EMS_RVC_RVN_CLCT_OFFC")
        # Lookup: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SSA_EMS_RVC_RVN_CLCT_OFFC
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK
        df_mplt_lkp_chain_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SSA_EMS_RVC_RVN_CLCT_OFFC,
            name='MPLT_AGMT_EMS_RVN_CLCT_OFFC_LKP_DYN_SSA_EMS_RVC_RVN_CLCT_OFFC',
            join_predicates=[{'source_col': 'CLCT_OFFC_KEY', 'lookup_col': 'SURROGATE_KEY'}],
            output_columns=['SURROGATE_KEY', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'SURROGATE_KEY', 'ref_field': 'CLCT_OFFC_KEY', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'decimal'},
                {'name': 'DUMMY', 'ref_field': 'OUT_TABLE_NAME', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow_LKP_DYN_SSA_EMS_RVC_RVN_CLCT_OFFC',
            sequence_config=None,
            insert_else_update=False,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_mplt_lkp_chain_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK", df_mplt_lkp_chain_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK)
        
        logger.info("Step: rename_EXPTRANS1")
        # Expression: rename_EXPTRANS1
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXPTRANS1 = lib.expression(
            input_df=df_mplt_lkp_chain_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXP_SK,
            rename_columns=[
                ('SOR_CACHE_STATUS', 'IN_DLPK_SOR_CACHE'),
                ('IN_RVN_CLCT_OFFC_KEY', 'RVN_CLCT_OFFC_KEY'),
                ('NewLookupRow_LKP_DYN_SSA_EMS_RVC_RVN_CLCT_OFFC', 'IN_DLPK_SSA_CACHE')
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXPTRANS1", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS1")
        # Expression: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS1
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS1 = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_rename_EXPTRANS1,
            computed_columns=[
                {'name': 'V_AUG_IND', 'expr': "CASE WHEN IN_DLPK_SOR_CACHE = 1 THEN 'Y' ELSE 'N' END"},
                {'name': 'OPR_IND', 'expr': "'A'"},
                {'name': 'LAST_REC_TXN_TYPE_CODE', 'expr': 'NULL'},
                {'name': 'DUMMY_KEY', 'expr': '0'}
            ],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS1", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS1)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC")
        # Expression: apply_MPLT_AGMT_EMS_RVN_CLCT_OFFC
        df_MPLT_AGMT_EMS_RVN_CLCT_OFFC = lib.expression(
            input_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC_EXPTRANS1,
            rename_columns=[
                ('IN_DLPK_SOR_CACHE', 'OUT_DLPK_SOR_CACHE'),
                ('V_AUG_IND', 'OUT_AUG_IND')
            ],
            pass_through_cols=['OUT_DLPK_SOR_CACHE', 'OUT_AUG_IND', 'OPR_IND', 'LAST_REC_TXN_TYPE_CODE', 'CLCT_OFFC_KEY', 'RVN_CLCT_OFFC_KEY'],
        )
        ctx.register_df("df_MPLT_AGMT_EMS_RVN_CLCT_OFFC", df_MPLT_AGMT_EMS_RVN_CLCT_OFFC)
        
        logger.info("Step: apply_FILTRANS1")
        # Filter: apply_FILTRANS1
        df_FILTRANS1 = lib.filter(
            input_df=df_MPLT_AGMT_EMS_RVC_COST_CTR,
            rename_columns=[
                ('COST_CTR_BSNS_ACTV_CODE', 'COST_CTR_BSNS_ACTV_TYPE_CODE')
            ],
            condition='OUT_DLPK_SOR_CACHE = 1',
        )
        ctx.register_df("df_FILTRANS1", df_FILTRANS1)

        logger.info("Step: read_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD")
        # Reading Data From Source - read_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT 
SOR_EMS_SEC_ORG_UNIT_COST_CTR.SEC_ORG_UNIT_MGT_KEY as SEC_ORG_UNIT_MGT_KEY,
SOR_EMS_SEC_ORG_UNIT_COST_CTR.COST_CTR_KEY as COST_CTR_KEY
FROM SOR_EMS_SEC_ORG_UNIT_COST_CTR
WHERE SOR_EMS_SEC_ORG_UNIT_COST_CTR.END_DATE = TO_DATE ('99991231', 'YYYYMMDD')
and last_rec_txn_type_code is null"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD_0")
        # Lookup: merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD_0
        # Merge on common columns — drop lookup columns that duplicate non-key input columns. 
        # Matches are CASE-INSENSITIVE: SQ ports may be lowercase while Oracle lookup
        _cc = list(dict.fromkeys(c for c in df_EXPTRANS.columns if c.lower() in [x.lower() for x in df_MPLT_AGMT_EMS_RVC_COST_CTR.columns]))
        if _cc:
            __lkp_dup = [c for c in df_MPLT_AGMT_EMS_RVC_COST_CTR.columns if c.lower() in [x.lower() for x in df_EXPTRANS.columns] and c.lower() not in [x.lower() for x in _cc]]
            # Break attribute lineage on the merged side: when both inputs are built from the same source plan. 
            # Re-projecting with aliases gives this side fresh attribute IDs without changing rows or column names.
            __rhs = df_MPLT_AGMT_EMS_RVC_COST_CTR.drop(*__lkp_dup) if __lkp_dup else df_MPLT_AGMT_EMS_RVC_COST_CTR
            __rhs = __rhs.select(*[col(c).alias(c) for c in __rhs.columns])
            df_merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD_0 = df_EXPTRANS.join(
                __rhs,
                on=_cc, how="left"
            )
        else:
            logger.warning("No common columns between df_EXPTRANS and df_MPLT_AGMT_EMS_RVC_COST_CTR — using synthetic key join")
            __rhs = df_MPLT_AGMT_EMS_RVC_COST_CTR.withColumn("_join_key", lit(1))
            __rhs = __rhs.select(*[col(c).alias(c) for c in __rhs.columns])
            df_merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD_0 = df_EXPTRANS.withColumn("_join_key", lit(1)).join(
                __rhs,
                on="_join_key", how="left").drop("_join_key")
        ctx.register_df("df_merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD_0", df_merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD_0)
        
        logger.info("Step: apply_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD")
        # Lookup: apply_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD_0
        _lkp_input = _lkp_input.withColumn("IN_COST_CTR_KEY", col("COST_CTR_KEY"))
        df_lkp_merge_MPLT_AGMT_EMS_RVC_COST_CTR = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD,
            name='LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD',
            join_predicates=[{'source_col': 'IN_COST_CTR_KEY', 'lookup_col': 'COST_CTR_KEY'}],
            output_columns=['SEC_ORG_UNIT_MGT_KEY', 'COST_CTR_KEY'],
            lookup_output_fields=[
                {'name': 'SEC_ORG_UNIT_MGT_KEY', 'ref_field': 'Sequence-Id', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'integer'},
                {'name': 'COST_CTR_KEY', 'ref_field': 'COST_CTR_KEY', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'decimal'}
            ],
            new_lookup_row_col='NewLookupRow',
            sequence_config={'output_col': 'SEC_ORG_UNIT_MGT_KEY'},
            insert_else_update=False,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_lkp_merge_MPLT_AGMT_EMS_RVC_COST_CTR", df_lkp_merge_MPLT_AGMT_EMS_RVC_COST_CTR)
        
        logger.info("Step: apply_FILTRANS2")
        # Filter: apply_FILTRANS2
        df_FILTRANS2 = lib.filter(
            input_df=df_MPLT_AGMT_EMS_RVN_CLCT_OFFC,
            condition='OUT_DLPK_SOR_CACHE = 1',
        )
        ctx.register_df("df_FILTRANS2", df_FILTRANS2)

        logger.info("Step: apply_EXPTRANS12")
        # Expression: apply_EXPTRANS12
        df_EXPTRANS12 = lib.expression(
            input_df=df_FILTRANS1,
            computed_columns=[
                {'name': 'LAST_REC_TXN_DATE', 'expr': 'current_timestamp()'}
            ],
        )
        ctx.register_df("df_EXPTRANS12", df_EXPTRANS12)
        
        logger.info("Step: read_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR")
        # Reading Data From Source - read_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT 
SOR_EMS_SEC_ORG_UNIT_COST_CTR.SEC_ORG_UNIT_MGT_KEY as SEC_ORG_UNIT_MGT_KEY,
SOR_EMS_SEC_ORG_UNIT_COST_CTR.BGN_DATE as BGN_DATE, 
NULL as DUMMY, 
SOR_EMS_SEC_ORG_UNIT_COST_CTR.CLCT_OFFC_KEY as CLCT_OFFC_KEY, SOR_EMS_SEC_ORG_UNIT_COST_CTR.COST_CTR_KEY as COST_CTR_KEY,
SOR_EMS_SEC_ORG_UNIT_COST_CTR.COST_CTR_TNCY_TYPE_CODE as COST_CTR_TNCY_TYPE_CODE,
SOR_EMS_SEC_ORG_UNIT_COST_CTR.COST_CTR_CODE AS COST_CTR_CODE ,
SOR_EMS_SEC_ORG_UNIT_COST_CTR.BSNS_ACTV_CODE AS BSNS_ACTV_CODE,
SOR_EMS_SEC_ORG_UNIT_COST_CTR.ORG_UNIT_KEY AS ORG_UNIT_KEY
FROM SOR_EMS_SEC_ORG_UNIT_COST_CTR
WHERE SOR_EMS_SEC_ORG_UNIT_COST_CTR.END_DATE = TO_DATE ('99991231', 'YYYYMMDD')
and last_rec_txn_type_code is null"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: merge_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR_0")
        # Lookup: merge_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR_0
        # Merge on common columns — drop lookup columns that duplicate non-key input columns. 
        # Matches are CASE-INSENSITIVE: SQ ports may be lowercase while Oracle lookup
        _cc = list(dict.fromkeys(c for c in df_lkp_merge_MPLT_AGMT_EMS_RVC_COST_CTR.columns if c.lower() in [x.lower() for x in df_MPLT_AGMT_EMS_RVN_CLCT_OFFC.columns]))
        if _cc:
            __lkp_dup = [c for c in df_MPLT_AGMT_EMS_RVN_CLCT_OFFC.columns if c.lower() in [x.lower() for x in df_lkp_merge_MPLT_AGMT_EMS_RVC_COST_CTR.columns] and c.lower() not in [x.lower() for x in _cc]]
            # Break attribute lineage on the merged side: when both inputs are built from the same source plan. 
            # Re-projecting with aliases gives this side fresh attribute IDs without changing rows or column names.
            __rhs = df_MPLT_AGMT_EMS_RVN_CLCT_OFFC.drop(*__lkp_dup) if __lkp_dup else df_MPLT_AGMT_EMS_RVN_CLCT_OFFC
            __rhs = __rhs.select(*[col(c).alias(c) for c in __rhs.columns])
            df_merge_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR_0 = df_lkp_merge_MPLT_AGMT_EMS_RVC_COST_CTR.join(
                __rhs,
                on=_cc, how="left"
            )
        else:
            logger.warning("No common columns between df_lkp_merge_MPLT_AGMT_EMS_RVC_COST_CTR and df_MPLT_AGMT_EMS_RVN_CLCT_OFFC — using synthetic key join")
            __rhs = df_MPLT_AGMT_EMS_RVN_CLCT_OFFC.withColumn("_join_key", lit(1))
            __rhs = __rhs.select(*[col(c).alias(c) for c in __rhs.columns])
            df_merge_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR_0 = df_lkp_merge_MPLT_AGMT_EMS_RVC_COST_CTR.withColumn("_join_key", lit(1)).join(
                __rhs,
                on="_join_key", how="left").drop("_join_key")
        ctx.register_df("df_merge_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR_0", df_merge_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR_0)
        
        logger.info("Step: apply_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR")
        # Lookup: apply_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_merge_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR_0
        _lkp_input = _lkp_input.withColumn("IN_SEC_ORG_UNIT_MGT_KEY", col("SEC_ORG_UNIT_MGT_KEY"))
        _lkp_input = _lkp_input.withColumn("IN_DUMMY", col("DUMMY"))
        _lkp_input = _lkp_input.withColumn("IN_COST_CTR_TNCY_TYPE_CODE", col("COST_CTR_TNCY_TYPE_CODE"))
        _lkp_input = _lkp_input.withColumn("IN_COST_CTR_CODE", col("COST_CTR_CODE"))
        _lkp_input = _lkp_input.withColumn("IN_COST_CTR_BSNS_ACTV_TYPE_CODE", col("COST_CTR_BSNS_ACTV_CODE"))
        _lkp_input = _lkp_input.withColumn("IN_RVN_CLCT_OFFC_KEY", col("RVN_CLCT_OFFC_KEY"))
        _lkp_input = _lkp_input.withColumn("IN_CLCT_OFFC_KEY", col("CLCT_OFFC_KEY"))
        df_lkp_merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR,
            name='LKP_DYN_SOR_EMS_SEC_OU_MGT_COST_CTR',
            join_predicates=[{'source_col': 'IN_SEC_ORG_UNIT_MGT_KEY', 'lookup_col': 'SEC_ORG_UNIT_MGT_KEY'}],
            output_columns=['SEC_ORG_UNIT_MGT_KEY', 'COST_CTR_KEY', 'CLCT_OFFC_KEY', 'BGN_DATE', 'COST_CTR_CODE', 'BSNS_ACTV_CODE', 'ORG_UNIT_KEY', 'COST_CTR_TNCY_TYPE_CODE', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'SEC_ORG_UNIT_MGT_KEY', 'ref_field': 'SEC_ORG_UNIT_MGT_KEY', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'integer'},
                {'name': 'COST_CTR_KEY', 'ref_field': 'IN_COST_CTR_KEY', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'decimal'},
                {'name': 'CLCT_OFFC_KEY', 'ref_field': 'CLCT_OFFC_KEY', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'decimal'},
                {'name': 'BGN_DATE', 'ref_field': 'DUMMY_DATE', 'ignore_in_compare': True, 'ignore_null_inputs': True, 'datatype': 'date/time'},
                {'name': 'COST_CTR_CODE', 'ref_field': 'COST_CTR_CODE', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'},
                {'name': 'BSNS_ACTV_CODE', 'ref_field': 'COST_CTR_BSNS_ACTV_CODE', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'},
                {'name': 'ORG_UNIT_KEY', 'ref_field': 'RVN_CLCT_OFFC_KEY', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'},
                {'name': 'COST_CTR_TNCY_TYPE_CODE', 'ref_field': 'COST_CTR_TNCY_TYPE_CODE', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'},
                {'name': 'DUMMY', 'ref_field': 'DUMMY', 'ignore_in_compare': True, 'ignore_null_inputs': True, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow',
            sequence_config=None,
            insert_else_update=True,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_lkp_merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD", df_lkp_merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD)
        
        logger.info("Step: apply_EXPTRANS1")
        # Expression: apply_EXPTRANS1
        df_EXPTRANS1 = lib.expression(
            input_df=df_FILTRANS2,
            computed_columns=[
                {'name': 'LAST_REC_TXN_DATE', 'expr': 'current_timestamp()'}
            ],
        )
        ctx.register_df("df_EXPTRANS1", df_EXPTRANS1)
        
        logger.info("Step: write_SSA_RVC_COST_CTR")
        # Write to Target: write_SSA_RVC_COST_CTR
        lib.write_target(
            spark=spark,
            df=df_EXPTRANS12,
            conn=conn_target,
            table='SSA_RVC_COST_CTR',
            mode='append',
            source_columns=[
                'COST_CTR_KEY',
                'COST_CTR_CODE',
                'COST_CTR_BSNS_ACTV_TYPE_CODE',
                'OUT_AUG_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
                'OPR_IND',
                None,
            ],
            target_columns=[
                'COST_CTR_KEY',
                'COST_CTR_CODE',
                'COST_CTR_BSNS_ACTV_CODE',
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
                'OPR_IND',
                'SOR_DATE',
            ],
            config=config,
        )

        logger.info("write_SSA_RVC_COST_CTR write completed")
        logger.info("Step: apply_FILTRANS")
        # Filter: apply_FILTRANS
        df_FILTRANS = lib.filter(
            input_df=df_lkp_merge_LKP_SOR_EMS_SEC_ORG_UNIT_COST_CTR_SCD,
            rename_columns=[
                ('ORG_UNIT_KEY', 'RVN_CLCT_OFFC_KEY'),
                ('BSNS_ACTV_CODE', 'COST_CTR_BSNS_ACTV_TYPE_CODE')
            ],
            condition="NewLookupRow > 0 OR LAST_REC_TXN_TYPE_CODE = 'D'",
        )
        ctx.register_df("df_FILTRANS", df_FILTRANS)

        logger.info("Step: write_SSA_EMS_RVN_CLCT_OFFC")
        # Write to Target: write_SSA_EMS_RVN_CLCT_OFFC
        lib.write_target(
            spark=spark,
            df=df_EXPTRANS1,
            conn=conn_target,
            table='SSA_EMS_RVC_RVN_CLCT_OFFC',
            mode='append',
            source_columns=[
                'CLCT_OFFC_KEY',
                'RVN_CLCT_OFFC_KEY',
                'LAST_REC_TXN_DATE',
                'OUT_AUG_IND',
                'OPR_IND',
                None,
                'LAST_REC_TXN_TYPE_CODE',
            ],
            target_columns=[
                'CLCT_OFFC_KEY',
                'RVN_CLCT_OFFC_KEY',
                'LAST_REC_TXN_DATE',
                'AGMT_IND',
                'OPR_IND',
                'SOR_DATE',
                'LAST_REC_TXN_TYPE_CODE',
            ],
            config=config,
        )

        logger.info("write_SSA_EMS_RVN_CLCT_OFFC write completed")
        logger.info("Step: apply_EXPTRANS11")
        # Expression: apply_EXPTRANS11
        df_EXPTRANS11 = lib.expression(
            input_df=df_FILTRANS,
            computed_columns=[
                {'name': 'SNAPSHOT_DATE', 'expr': "to_date('$$v_snsh_date','yyyyMMdd')"},
                {'name': 'IN_CACHE_STATUS', 'expr': 'NewLookupRow'},
                {'name': 'v_SSAL2_TBL_NAME', 'expr': "'SSA_EMS_SEC_ORG_UNIT_COST_CTR'"},
                {'name': 'V_AGMT_IND', 'expr': "'N'"},
                {'name': 'DELETE_IND', 'expr': "CASE WHEN LAST_REC_TXN_TYPE_CODE = 'D' THEN 'Y' ELSE 'N' END"},
                {'name': 'LST_UPT_DTIME', 'expr': 'NULL'},
                {'name': 'INIT_FLAG', 'expr': "'$$v_init_flag'"}
            ],
            substitutions={'$$v_snsh_date': v_snsh_date, '$$v_init_flag': v_init_flag},
        )
        ctx.register_df("df_EXPTRANS11", df_EXPTRANS11)
        
        logger.info("Step: read_LKP_DYN_SSA_EMS_SEC_OU_MGT_COST_CTR")
        # Reading Data From Source - read_LKP_DYN_SSA_EMS_SEC_OU_MGT_COST_CTR
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SEC_ORG_UNIT_MGT_KEY AS SURROGATE_KEY,
 'S' AS DUMMY  
FROM SSA_EMS_SEC_ORG_UNIT_COST_CTR"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_LKP_DYN_SSA_EMS_SEC_OU_MGT_COST_CTR = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DYN_SSA_EMS_SEC_OU_MGT_COST_CTR")
        # Lookup: apply_LKP_DYN_SSA_EMS_SEC_OU_MGT_COST_CTR
        # Dynamic lookup (applyInPandas state machine; RDD fallback when pyarrow
        # is unavailable). NewLookupRow: 1 = insert, 2 = update, 0 = no change.
        _lkp_input = df_EXPTRANS11
        _lkp_input = _lkp_input.withColumn("IN_SURROGATE_KEY", col("SEC_ORG_UNIT_MGT_KEY"))
        _lkp_input = _lkp_input.withColumn("IN_DUMMY", col("v_SSAL2_TBL_NAME"))
        df_lkp_merge_FILTRANS = lib.dynamic_lookup(
            spark=spark,
            input_df=_lkp_input,
            lookup_df=df_LKP_DYN_SSA_EMS_SEC_OU_MGT_COST_CTR,
            name='LKP_DYN_SSA_EMS_SEC_OU_MGT_COST_CTR',
            join_predicates=[{'source_col': 'IN_SURROGATE_KEY', 'lookup_col': 'SURROGATE_KEY'}],
            output_columns=['SURROGATE_KEY', 'DUMMY'],
            lookup_output_fields=[
                {'name': 'SURROGATE_KEY', 'ref_field': 'SEC_ORG_UNIT_MGT_KEY', 'ignore_in_compare': True, 'ignore_null_inputs': False, 'datatype': 'decimal'},
                {'name': 'DUMMY', 'ref_field': 'v_SSAL2_TBL_NAME', 'ignore_in_compare': False, 'ignore_null_inputs': False, 'datatype': 'string'}
            ],
            new_lookup_row_col='NewLookupRow',
            sequence_config=None,
            insert_else_update=False,
            update_else_insert=False,
            update_condition='TRUE',
            output_old_value_on_update=False,
            case_sensitive_string_comparison=False,
            lookup_policy='Report Error',
            order_by_columns=[],
            config=config,
        )
        ctx.register_df("df_lkp_merge_FILTRANS", df_lkp_merge_FILTRANS)
        
        logger.info("Step: nullinput_MPLT_DLKP_CACHE_STATUS1")
        # Expression: nullinput_MPLT_DLKP_CACHE_STATUS1
        df_MPLT_DLKP_CACHE_STATUS1_nullinput = lib.expression(
            input_df=df_lkp_merge_FILTRANS,
            computed_columns=[
                {'name': 'IN_TABLE_NAME', 'expr': 'NULL'}
            ],
        )
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_nullinput", df_MPLT_DLKP_CACHE_STATUS1_nullinput)
        
        logger.info("Step: input_MPLT_DLKP_CACHE_STATUS1")
        # Expression: input_MPLT_DLKP_CACHE_STATUS1
        df_MPLT_DLKP_CACHE_STATUS1_input = lib.expression(
            input_df=df_MPLT_DLKP_CACHE_STATUS1_nullinput,
            computed_columns=[
                {'name': 'IN_SOR_DATE', 'expr': 'BGN_DATE'},
                {'name': 'IN_V_DLKP_SSA_CACHE_STATUS', 'expr': 'NewLookupRow'},
                {'name': 'IN_V_DLKP_SOR_CACHE_STATUS', 'expr': 'IN_CACHE_STATUS'},
                {'name': 'IN_AGMT_IND', 'expr': 'V_AGMT_IND'},
                {'name': 'IN_V_DEL_IND', 'expr': 'DELETE_IND'},
                {'name': 'IN_V_INIT_IND', 'expr': 'INIT_FLAG'},
                {'name': 'IN_V_LAST_UPDATE_DATE', 'expr': 'LST_UPT_DTIME'},
                {'name': 'IN_V_SNAPSHOT_DATE', 'expr': 'SNAPSHOT_DATE'}
            ],
        )
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_input", df_MPLT_DLKP_CACHE_STATUS1_input)
        
        logger.info("Step: rename_EXPTRANS2")
        # Expression: rename_EXPTRANS2
        df_MPLT_DLKP_CACHE_STATUS1_rename_EXPTRANS2 = lib.expression(
            input_df=df_MPLT_DLKP_CACHE_STATUS1_input,
            rename_columns=[
                ('IN_V_DEL_IND', 'IN_DEL_FLAG'),
                ('IN_V_DLKP_SOR_CACHE_STATUS', 'IN_DLK_SOR_CACHE_STATUS'),
                ('IN_V_SNAPSHOT_DATE', 'SNAPSHOT_DATE'),
                ('IN_AGMT_IND', 'AGMT_IND'),
                ('IN_TABLE_NAME', 'TABLE_NAME'),
                ('IN_V_DLKP_SSA_CACHE_STATUS', 'IN_DLKP_SSA_CACHE_STATUS')
            ],
        )
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_rename_EXPTRANS2", df_MPLT_DLKP_CACHE_STATUS1_rename_EXPTRANS2)
        
        logger.info("Step: apply_MPLT_DLKP_CACHE_STATUS_EXPTRANS2")
        # Expression: apply_MPLT_DLKP_CACHE_STATUS_EXPTRANS2
        df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2 = lib.expression(
            input_df=df_MPLT_DLKP_CACHE_STATUS1_rename_EXPTRANS2,
            computed_columns=[
                {'name': 'UPDATE_STRATEGY_STATUS', 'expr': "CASE WHEN IN_DLK_SOR_CACHE_STATUS = 1 THEN 'DD_INSERT' ELSE CASE WHEN IN_DLKP_SSA_CACHE_STATUS = 1 THEN 'DD_INSERT' ELSE 'DD_UPDATE' END END"},
                {'name': 'NEW_FLAG', 'expr': 'CASE WHEN IN_DLK_SOR_CACHE_STATUS = 1 THEN 1 ELSE 0 END'},
                {'name': 'CHG_FLAG', 'expr': 'CASE WHEN IN_DLK_SOR_CACHE_STATUS = 2 THEN 1 ELSE 0 END'},
                {'name': 'DEL_FLAG', 'expr': "CASE WHEN IN_DEL_FLAG = 'Y' THEN 1 WHEN IN_DEL_FLAG = 'y' THEN 1 ELSE 0 END"}
            ],
        )
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2", df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2)
        
        logger.info("Step: rename_EXP_SSAL2_TRANSFORM2")
        # Expression: rename_EXP_SSAL2_TRANSFORM2
        df_MPLT_DLKP_CACHE_STATUS1_rename_EXP_SSAL2_TRANSFORM2 = lib.expression(
            input_df=df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2,
            rename_columns=[
                ('IN_SOR_DATE', 'SOR_DATE'),
                ('IN_V_INIT_IND', 'INIT_FLAG'),
                ('IN_V_LAST_UPDATE_DATE', 'LAST_UPDATE_DATE')
            ],
        )
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_rename_EXP_SSAL2_TRANSFORM2", df_MPLT_DLKP_CACHE_STATUS1_rename_EXP_SSAL2_TRANSFORM2)
        
        logger.info("Step: apply_MPLT_DLKP_CACHE_STATUS_EXP_SSAL2_TRANSFORM2")
        # Expression: apply_MPLT_DLKP_CACHE_STATUS_EXP_SSAL2_TRANSFORM2
        df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2 = lib.expression(
            input_df=df_MPLT_DLKP_CACHE_STATUS1_rename_EXP_SSAL2_TRANSFORM2,
            computed_columns=[
                {'name': 'CDC_FLAG', 'expr': 'CASE WHEN 1 = NEW_FLAG THEN 1 WHEN 1 = CHG_FLAG THEN 1 WHEN 1 = DEL_FLAG THEN 1 ELSE 0 END'},
                {'name': 'V_OPR_IND', 'expr': "CASE WHEN NEW_FLAG = 1 THEN 'B' ELSE CASE WHEN CHG_FLAG = 1 THEN 'EB' ELSE CASE WHEN DEL_FLAG = 1 THEN 'E' ELSE NULL END END END"},
                {'name': 'OPR_IND', 'expr': 'V_OPR_IND'},
                {'name': 'AGMT_IND', 'expr': "'N'"},
                {'name': 'BGN_DATE', 'expr': "CASE WHEN V_OPR_IND='B' AND INIT_FLAG = 'Y' THEN to_date('19000101','yyyyMMdd') ELSE SNAPSHOT_DATE END"},
                {'name': 'END_DATE', 'expr': "CASE WHEN DEL_FLAG = 1 THEN CASE WHEN INIT_FLAG = 'Y' THEN CASE WHEN LAST_UPDATE_DATE IS NULL THEN date_add(SNAPSHOT_DATE, CAST(-1 AS INT)) ELSE LAST_UPDATE_DATE END ELSE date_add(SNAPSHOT_DATE, CAST(-1 AS INT)) END ELSE CASE WHEN NEW_FLAG = 1 THEN to_date('99991231','yyyyMMdd') ELSE CASE WHEN CHG_FLAG = 1 THEN date_add(SNAPSHOT_DATE, CAST(-1 AS INT)) ELSE NULL END END END"},
                {'name': 'LAST_REC_TXN_DATE', 'expr': 'current_timestamp()'},
                {'name': 'LAST_REC_TXN_TYPE_CODE', 'expr': "CASE WHEN DEL_FLAG = 1 THEN 'D' ELSE NULL END"}
            ],
        )
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2", df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2)
        
        logger.info("Step: rename_EXPTRANS")
        # Expression: rename_EXPTRANS
        df_MPLT_DLKP_CACHE_STATUS1_rename_EXPTRANS = lib.expression(
            input_df=df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2,
            rename_columns=[
                ('AGMT_IND', 'IN_AGMT_IND'),
                ('OPR_IND', 'IN_OPR_IND')
            ],
        )
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_rename_EXPTRANS", df_MPLT_DLKP_CACHE_STATUS1_rename_EXPTRANS)
        
        logger.info("Step: apply_MPLT_DLKP_CACHE_STATUS_EXPTRANS")
        # Expression: apply_MPLT_DLKP_CACHE_STATUS_EXPTRANS
        df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS = lib.expression(
            input_df=df_MPLT_DLKP_CACHE_STATUS1_rename_EXPTRANS,
            computed_columns=[
                {'name': 'OUT_V_OPR_IND', 'expr': "CASE WHEN IN_AGMT_IND = 'Y' THEN 'A' ELSE IN_OPR_IND END"},
                {'name': 'OUT_BGN_DATE', 'expr': "CASE WHEN IN_OPR_IND='B' AND DEL_FLAG = 1 THEN to_date('19000101','yyyyMMdd') ELSE BGN_DATE END"}
            ],
        )
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS", df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS)
        
        logger.info("Step: join_output_MPLT_DLKP_CACHE_STATUS1_0")
        # Lookup: join_output_MPLT_DLKP_CACHE_STATUS1_0
        # Merge on common columns — drop lookup columns that duplicate non-key input columns. 
        # Matches are CASE-INSENSITIVE: SQ ports may be lowercase while Oracle lookup
        _cc = list(dict.fromkeys(c for c in df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS.columns if c.lower() in [x.lower() for x in df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2.columns]))
        if _cc:
            __lkp_dup = [c for c in df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2.columns if c.lower() in [x.lower() for x in df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS.columns] and c.lower() not in [x.lower() for x in _cc]]
            # Break attribute lineage on the merged side: when both inputs are built from the same source plan. 
            # Re-projecting with aliases gives this side fresh attribute IDs without changing rows or column names.
            __rhs = df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2.drop(*__lkp_dup) if __lkp_dup else df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2
            __rhs = __rhs.select(*[col(c).alias(c) for c in __rhs.columns])
            df_MPLT_DLKP_CACHE_STATUS1_merge_output_0 = df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS.join(
                __rhs,
                on=_cc, how="left"
            )
        else:
            logger.warning("No common columns between df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS and df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2 — using synthetic key join")
            __rhs = df_MPLT_DLKP_CACHE_STATUS1_EXP_SSAL2_TRANSFORM2.withColumn("_join_key", lit(1))
            __rhs = __rhs.select(*[col(c).alias(c) for c in __rhs.columns])
            df_MPLT_DLKP_CACHE_STATUS1_merge_output_0 = df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS.withColumn("_join_key", lit(1)).join(
                __rhs,
                on="_join_key", how="left").drop("_join_key")
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_merge_output_0", df_MPLT_DLKP_CACHE_STATUS1_merge_output_0)
        
        logger.info("Step: join_output_MPLT_DLKP_CACHE_STATUS1_1")
        # Lookup: join_output_MPLT_DLKP_CACHE_STATUS1_1
        # Merge on common columns — drop lookup columns that duplicate non-key input columns. 
        # Matches are CASE-INSENSITIVE: SQ ports may be lowercase while Oracle lookup
        _cc = list(dict.fromkeys(c for c in df_MPLT_DLKP_CACHE_STATUS1_merge_output_0.columns if c.lower() in [x.lower() for x in df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2.columns]))
        if _cc:
            __lkp_dup = [c for c in df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2.columns if c.lower() in [x.lower() for x in df_MPLT_DLKP_CACHE_STATUS1_merge_output_0.columns] and c.lower() not in [x.lower() for x in _cc]]
            # Break attribute lineage on the merged side: when both inputs are built from the same source plan. 
            # Re-projecting with aliases gives this side fresh attribute IDs without changing rows or column names.
            __rhs = df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2.drop(*__lkp_dup) if __lkp_dup else df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2
            __rhs = __rhs.select(*[col(c).alias(c) for c in __rhs.columns])
            df_MPLT_DLKP_CACHE_STATUS1_merge_output_1 = df_MPLT_DLKP_CACHE_STATUS1_merge_output_0.join(
                __rhs,
                on=_cc, how="left"
            )
        else:
            logger.warning("No common columns between df_MPLT_DLKP_CACHE_STATUS1_merge_output_0 and df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2 — using synthetic key join")
            __rhs = df_MPLT_DLKP_CACHE_STATUS1_EXPTRANS2.withColumn("_join_key", lit(1))
            __rhs = __rhs.select(*[col(c).alias(c) for c in __rhs.columns])
            df_MPLT_DLKP_CACHE_STATUS1_merge_output_1 = df_MPLT_DLKP_CACHE_STATUS1_merge_output_0.withColumn("_join_key", lit(1)).join(
                __rhs,
                on="_join_key", how="left").drop("_join_key")
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1_merge_output_1", df_MPLT_DLKP_CACHE_STATUS1_merge_output_1)
        
        logger.info("Step: apply_MPLT_DLKP_CACHE_STATUS1")
        # Expression: apply_MPLT_DLKP_CACHE_STATUS1
        df_MPLT_DLKP_CACHE_STATUS1 = lib.expression(
            input_df=df_MPLT_DLKP_CACHE_STATUS1_merge_output_1,
            rename_columns=[
                ('LAST_REC_TXN_DATE', 'OUT_V_LAST_REC_TXN_DATE'),
                ('LAST_REC_TXN_TYPE_CODE', 'OUT_V_LAST_REC_TXN_TYPE_CODE'),
                ('SOR_DATE', 'OUT_SOR_DATE'),
                ('BGN_DATE', 'OUT_V_BGN_DATE'),
                ('END_DATE', 'OUT_V_END_DATE'),
                ('AGMT_IND', 'OUT_AGMT_IND'),
                ('TABLE_NAME', 'OUT_TABLE_NAME'),
                ('UPDATE_STRATEGY_STATUS', 'OUT_V_UPD_STRATEGY_STATUS')
            ],
            pass_through_cols=['OUT_V_UPD_STRATEGY_STATUS', 'OUT_V_BGN_DATE', 'OUT_V_END_DATE', 'OUT_V_LAST_REC_TXN_DATE', 'OUT_V_LAST_REC_TXN_TYPE_CODE', 'OUT_V_OPR_IND', 'OUT_TABLE_NAME', 'OUT_AGMT_IND', 'OUT_SOR_DATE'],
        )
        ctx.register_df("df_MPLT_DLKP_CACHE_STATUS1", df_MPLT_DLKP_CACHE_STATUS1)
        
        logger.info("Step: apply_UPD_SSAL2_MSTR11")
        # Update Strategy: apply_UPD_SSAL2_MSTR11
        # Strategy: OUT_V_UPD_STRATEGY_STATUS
        df_UPD_SSAL2_MSTR11 = lib.update_strategy(
            input_df=df_MPLT_DLKP_CACHE_STATUS1,
            strategy_field='OUT_V_UPD_STRATEGY_STATUS',
        )
        ctx.register_df("df_UPD_SSAL2_MSTR11", df_UPD_SSAL2_MSTR11)
        
        logger.info("Step: write_SSA_EMS_SEC_ORG_UNIT_COST_CTR")
        # Write to Target: write_SSA_EMS_SEC_ORG_UNIT_COST_CTR
        lib.write_target(
            spark=spark,
            df=df_UPD_SSAL2_MSTR11,
            conn=conn_target,
            table='SSA_EMS_SEC_ORG_UNIT_COST_CTR',
            mode='append',
            source_columns=[
                'SEC_ORG_UNIT_MGT_KEY',
                'COST_CTR_KEY',
                'CLCT_OFFC_KEY',
                'COST_CTR_TNCY_TYPE_KEY',
                'COST_CTR_CODE',
                'COST_CTR_BSNS_ACTV_TYPE_CODE',
                'RVN_CLCT_OFFC_KEY',
                'OUT_V_BGN_DATE',
                'OUT_V_END_DATE',
                'OUT_LAST_REC_TXN_TYPE_CODE',
                'OUT_LAST_REC_TXN_DATE',
                'OUT_AGMT_IND',
                'OUT_OPR_IND',
                'OUT_SOR_DATE',
            ],
            target_columns=[
                'SEC_ORG_UNIT_MGT_KEY',
                'COST_CTR_KEY',
                'CLCT_OFFC_KEY',
                'COST_CTR_TNCY_TYPE_CODE',
                'COST_CTR_CODE',
                'BSNS_ACTV_CODE',
                'ORG_UNIT_KEY',
                'BGN_DATE',
                'END_DATE',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
                'AGMT_IND',
                'OPR_IND',
                'SOR_DATE',
            ],
            delete_keys=['sec_org_unit_mgt_key', 'cost_ctr_key', 'clct_offc_key', 'cost_ctr_tncy_type_code', 'cost_ctr_code', 'bsns_actv_code', 'org_unit_key', 'bgn_date', 'end_date', 'last_rec_txn_type_code', 'last_rec_txn_date', 'agmt_ind', 'opr_ind', 'sor_date'],
            has_update_flag=True,
            config=config,
        )

        logger.info("write_SSA_EMS_SEC_ORG_UNIT_COST_CTR write completed")
        
        metrics.complete()
        logger.info("Mapping M_EMS_SSAL2_TRANS_SEC_ORG_UNIT_COST_CTR completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_EMS_SSAL2_TRANS_SEC_ORG_UNIT_COST_CTR FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_EMS_SSAL2_TRANS_SEC_ORG_UNIT_COST_CTR", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_EMS_SSAL2_TRANS_SEC_ORG_UNIT_COST_CTR")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())