'''
* Script - M_S5_SOR_LOAD_EMS_HSM_UNIT_FOR_UPDATE_END.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_S5_SOR_LOAD_EMS_HSM_UNIT_FOR_UPDATE_END mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_S5_SOR_LOAD_EMS_HSM_UNIT_FOR_UPDATE_END")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_S5_SOR_LOAD_EMS_HSM_UNIT_FOR_UPDATE_END", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "SSA")

    
    try:
        logger.info("Step: read_SSA_HSM_UNIT")
        # Reading Data From Source - read_SSA_HSM_UNIT
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_HSM_UNIT = lib.read_sql(spark, _conn, table="SSA_HSM_UNIT")
        
        logger.info("Step: apply_SQ_SSA_HSM_UNIT")
        # Source Qualifier: apply_SQ_SSA_HSM_UNIT
        df_SQ_SSA_HSM_UNIT = df_SSA_HSM_UNIT
        df_SQ_SSA_HSM_UNIT = df_SQ_SSA_HSM_UNIT.filter(expr("OPR_IND = 'E'"))
        # Select only SQ output ports (matches Informatica behavior) — missing ports become lit(None)
        _port_cols = ["UNIT_ADDR_CODE", "UNIT_CATG_CODE", "AGMT_IND", "UNIT_TYPE_CODE", "LAST_REC_TXN_TYPE_CODE", "UNIT_NUM", "LAST_REC_TXN_DATE", "UNIT_CNV_REF_IND", "UNIT_SHRD_IND", "UNIT_IFA_AREA", "UNIT_LVNG_AREA", "UNIT_TAKE_OVER_DATE", "UNIT_GFA_AREA", "UNIT_SFA_AREA", "UNIT_BWA_AREA", "BLK_KEY", "UNIT_KEY", "UNIT_FLR_NUM", "OPR_IND", "SOR_DATE", "EMMS_UNIT_KEY", "BLK_BK_1"]
        df_SQ_SSA_HSM_UNIT = df_SQ_SSA_HSM_UNIT.select([col(c) if c.lower() in [x.lower() for x in df_SQ_SSA_HSM_UNIT.columns] else lit(None).alias(c) for c in _port_cols])
        ctx.register_df("df_SQ_SSA_HSM_UNIT", df_SQ_SSA_HSM_UNIT)
        
        logger.info("Step: write_SOR_HSM_UNIT")
        # Write to Target: write_SOR_HSM_UNIT
        df_write = df_SQ_SSA_HSM_UNIT
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("UNIT_ADDR_CODE", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_CATG_CODE", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_TYPE_CODE", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_NUM", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_CNV_REF_IND", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_SHRD_IND", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_IFA_AREA", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_LVNG_AREA", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_TAKE_OVER_DATE", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_GFA_AREA", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_SFA_AREA", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_BWA_AREA", lit(None).cast(StringType()))
        df_write = df_write.withColumn("BLK_KEY", lit(None).cast(StringType()))
        df_write = df_write.withColumn("UNIT_FLR_NUM", lit(None).cast(StringType()))
        df_write = df_write.withColumn("EMMS_UNIT_KEY", lit(None).cast(StringType()))
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['UNIT_ADDR_CODE', 'UNIT_CATG_CODE', 'UNIT_TYPE_CODE', 'UNIT_NUM', 'UNIT_CNV_REF_IND', 'UNIT_SHRD_IND', 'UNIT_IFA_AREA', 'UNIT_LVNG_AREA', 'UNIT_TAKE_OVER_DATE', 'UNIT_GFA_AREA', 'UNIT_SFA_AREA', 'UNIT_BWA_AREA', 'BLK_KEY', 'UNIT_KEY', 'UNIT_FLR_NUM', 'AGMT_IND', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'EMMS_UNIT_KEY']
        df_write = df_write.select(*[col for col in _target_cols if col.lower() in [x.lower() for x in df_write.columns]])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "SOR_HSM_UNIT", mode="append")

        logger.info("write_SOR_HSM_UNIT write completed")
        
        metrics.complete()
        logger.info("Mapping M_S5_SOR_LOAD_EMS_HSM_UNIT_FOR_UPDATE_END completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_S5_SOR_LOAD_EMS_HSM_UNIT_FOR_UPDATE_END FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_S5_SOR_LOAD_EMS_HSM_UNIT_FOR_UPDATE_END", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_S5_SOR_LOAD_EMS_HSM_UNIT_FOR_UPDATE_END")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())