'''
* Script - M_S5_SOR_LOAD_EMS_TAM_RAS_HIST_FOR_UPDATE_END.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_S5_SOR_LOAD_EMS_TAM_RAS_HIST_FOR_UPDATE_END mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_S5_SOR_LOAD_EMS_TAM_RAS_HIST_FOR_UPDATE_END")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_S5_SOR_LOAD_EMS_TAM_RAS_HIST_FOR_UPDATE_END", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "SSA")

    
    try:
        logger.info("Step: read_SSA_EMS_TAM_RAS_HIST_STS")
        # Reading Data From Source - read_SSA_EMS_TAM_RAS_HIST_STS
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_EMS_TAM_RAS_HIST_STS = lib.read_sql(spark, _conn, table="SSA_EMS_TAM_RAS_HIST")
        
        logger.info("Step: read_SSA_EMS_TAM_RAS_HIST")
        # Reading Data From Source - read_SSA_EMS_TAM_RAS_HIST
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_EMS_TAM_RAS_HIST = lib.read_sql(spark, _conn, table="SSA_EMS_TAM_RAS_HIST")
        
        logger.info("Step: apply_SQ_SSA_EMS_TAM_RAS_HIST_STS")
        # Source Qualifier: apply_SQ_SSA_EMS_TAM_RAS_HIST_STS
        df_SQ_SSA_EMS_TAM_RAS_HIST_STS = df_SSA_EMS_TAM_RAS_HIST_STS
        df_SQ_SSA_EMS_TAM_RAS_HIST_STS = lib.sq_output(
            input_df=df_SQ_SSA_EMS_TAM_RAS_HIST_STS,
            port_cols={
                'RAS_HIST_KEY': 'decimal',
                'BGN_DATE': 'date/time',
                'END_DATE': 'date/time',
                'CUST_KEY': 'decimal',
                'HSE_SRVC_APLY_KEY': 'decimal',
                'HSE_UNIT_CODE_ADDR': 'string',
                'RAS_RENT_FCTR_CODE': 'decimal',
                'ORIG_RAS_RENT_FCTR_CODE': 'decimal',
                'RAS_CNFRM_DATE': 'date/time',
                'RAS_RENT_BGN_DATE': 'date/time',
                'RAS_RENT_END_DATE': 'date/time',
                'RAS_TNCY_TYPE_CODE': 'string',
                'RAS_CNCL_IND': 'string',
                'RAS_CNCL_DATE': 'date/time',
                'RAS_CNCL_USER_ID': 'string',
                'RAS_UPD_CNT': 'decimal',
                'RAS_RENT_BGN_DATE_IND': 'string',
                'RAS_RENT_PRCS_IND': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'OPR_IND': 'string',
                'SOR_DATE': 'date/time',
            },
            filter_condition="OPR_IND = 'E' OR OPR_IND = 'EB'",
        )
        ctx.register_df("df_SQ_SSA_EMS_TAM_RAS_HIST_STS", df_SQ_SSA_EMS_TAM_RAS_HIST_STS)
        
        logger.info("Step: apply_SQ_SSA_EMS_TAM_RAS_HIST")
        # Source Qualifier: apply_SQ_SSA_EMS_TAM_RAS_HIST
        df_SQ_SSA_EMS_TAM_RAS_HIST = df_SSA_EMS_TAM_RAS_HIST
        df_SQ_SSA_EMS_TAM_RAS_HIST = lib.sq_output(
            input_df=df_SQ_SSA_EMS_TAM_RAS_HIST,
            port_cols={
                'RAS_HIST_KEY': 'decimal',
                'RAS_HIST_BK': 'string',
                'RAS_HIST_REC_KEY': 'decimal',
                'AGMT_IND': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'OPR_IND': 'string',
                'SOR_DATE': 'date/time',
            },
            filter_condition="OPR_IND = 'E'",
        )
        ctx.register_df("df_SQ_SSA_EMS_TAM_RAS_HIST", df_SQ_SSA_EMS_TAM_RAS_HIST)
        
        logger.info("Step: write_SOR_EMS_TAM_RAS_HIST_STS")
        # Write to Target: write_SOR_EMS_TAM_RAS_HIST_STS
        lib.write_target(
            spark=spark,
            df=df_SQ_SSA_EMS_TAM_RAS_HIST_STS,
            conn=conn_target,
            table='SOR_EMS_TAM_RAS_HIST_STS',
            mode='append',
            source_columns=[
                'RAS_HIST_KEY',
                'SOR_DATE',
                'END_DATE',
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                'LAST_REC_TXN_DATE',
            ],
            target_columns=[
                'RAS_HIST_KEY',
                'BGN_DATE',
                'END_DATE',
                'CUST_KEY',
                'HSE_SRVC_APLY_KEY',
                'HSE_UNIT_CODE_ADDR',
                'RAS_RENT_FCTR_CODE',
                'ORIG_RAS_RENT_FCTR_CODE',
                'RAS_CNFRM_DATE',
                'RAS_RENT_BGN_DATE',
                'RAS_RENT_END_DATE',
                'RAS_TNCY_TYPE_CODE',
                'RAS_CNCL_IND',
                'RAS_CNCL_DATE',
                'RAS_CNCL_USER_ID',
                'RAS_UPD_CNT',
                'RAS_RENT_BGN_DATE_IND',
                'RAS_RENT_PRCS_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            config=config,
        )

        logger.info("write_SOR_EMS_TAM_RAS_HIST_STS write completed")
        logger.info("Step: write_SOR_EMS_TAM_RAS_HIST")
        # Write to Target: write_SOR_EMS_TAM_RAS_HIST
        lib.write_target(
            spark=spark,
            df=df_SQ_SSA_EMS_TAM_RAS_HIST,
            conn=conn_target,
            table='SOR_EMS_TAM_RAS_HIST',
            mode='append',
            source_columns=[
                'RAS_HIST_KEY',
                None,
                None,
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            target_columns=[
                'RAS_HIST_KEY',
                'RAS_HIST_BK',
                'RAS_HIST_REC_KEY',
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            config=config,
        )

        logger.info("write_SOR_EMS_TAM_RAS_HIST write completed")
        
        metrics.complete()
        logger.info("Mapping M_S5_SOR_LOAD_EMS_TAM_RAS_HIST_FOR_UPDATE_END completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_S5_SOR_LOAD_EMS_TAM_RAS_HIST_FOR_UPDATE_END FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_S5_SOR_LOAD_EMS_TAM_RAS_HIST_FOR_UPDATE_END", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_S5_SOR_LOAD_EMS_TAM_RAS_HIST_FOR_UPDATE_END")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())