'''
* Script - M_S5_SOR_LOAD_EMS_RFX_UNIT_RENT_SCHD_FOR_INSERT.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_S5_SOR_LOAD_EMS_RFX_UNIT_RENT_SCHD_FOR_INSERT mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_S5_SOR_LOAD_EMS_RFX_UNIT_RENT_SCHD_FOR_INSERT")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_S5_SOR_LOAD_EMS_RFX_UNIT_RENT_SCHD_FOR_INSERT", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "SSA")

    
    try:
        logger.info("Step: read_SSA_EMS_RFX_UNIT_RENT_SCHD")
        # Reading Data From Source - read_SSA_EMS_RFX_UNIT_RENT_SCHD
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_EMS_RFX_UNIT_RENT_SCHD = lib.read_sql(spark, _conn, table="SSA_EMS_RFX_UNIT_RENT_SCHD")
        
        logger.info("Step: read_SSA_EMS_RFX_UNIT_RENT_SCHD_STS")
        # Reading Data From Source - read_SSA_EMS_RFX_UNIT_RENT_SCHD_STS
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_EMS_RFX_UNIT_RENT_SCHD_STS = lib.read_sql(spark, _conn, table="SSA_EMS_RFX_UNIT_RENT_SCHD_STS")
        
        logger.info("Step: apply_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD")
        # Source Qualifier: apply_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD
        df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD = df_SSA_EMS_RFX_UNIT_RENT_SCHD
        df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD = lib.sq_output(
            input_df=df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD,
            port_cols={
                'UNIT_RENT_SCHD_KEY': 'decimal',
                'UNIT_RENT_SCHD_BK': 'string',
                'UNIT_KEY': 'string',
                'AGMT_IND': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'OPR_IND': 'string',
                'SOR_DATE': 'date/time',
            },
            filter_condition="OPR_IND = 'B' OR OPR_IND = 'A'",
        )
        ctx.register_df("df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD", df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD)
        
        logger.info("Step: apply_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD_STS")
        # Source Qualifier: apply_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD_STS
        df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD_STS = df_SSA_EMS_RFX_UNIT_RENT_SCHD_STS
        df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD_STS = lib.sq_output(
            input_df=df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD_STS,
            port_cols={
                'UNIT_RENT_SCHD_KEY': 'decimal',
                'BGN_DATE': 'date/time',
                'END_DATE': 'date/time',
                'EST_KEY': 'string',
                'BLK_KEY': 'string',
                'UNIT_IFA_AREA': 'decimal',
                'UNIT_ENV_CODE': 'string',
                'TNT_RENT_CODE_CATG_CODE': 'string',
                'UNIT_NET_RENT_AMT': 'decimal',
                'UNIT_NET_RATE_AMT': 'decimal',
                'UNIT_MKT_MGT_FEE_AMT': 'decimal',
                'UNIT_MKT_RATE_AMT': 'decimal',
                'TNT_RENT_CODE': 'string',
                'UNIT_INCLS_RENT_AMT': 'decimal',
                'RENT_CODE_CHNG_BGN_DATE': 'date/time',
                'TOT_SHR_UNIT_CNT': 'decimal',
                'SHR_UNIT_SEQ_NUM': 'decimal',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'OPR_IND': 'string',
                'SOR_DATE': 'date/time',
            },
            filter_condition="OPR_IND = 'B' OR OPR_IND = 'EB' OR OPR_IND = 'DA'",
        )
        ctx.register_df("df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD_STS", df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD_STS)
        
        logger.info("Step: write_SOR_EMS_RFX_UNIT_RENT_SCHD")
        # Write to Target: write_SOR_EMS_RFX_UNIT_RENT_SCHD
        lib.write_target(
            spark=spark,
            df=df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD,
            conn=conn_target,
            table='SOR_EMS_RFX_UNIT_RENT_SCHD',
            mode='append',
            source_columns=[
                'UNIT_RENT_SCHD_KEY',
                'UNIT_RENT_SCHD_BK',
                'UNIT_KEY',
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            target_columns=[
                'UNIT_RENT_SCHD_KEY',
                'UNIT_RENT_SCHD_BK',
                'UNIT_KEY',
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            config=config,
        )

        logger.info("write_SOR_EMS_RFX_UNIT_RENT_SCHD write completed")
        logger.info("Step: apply_EXP_SOR_LOAD_DATE")
        # Expression: apply_EXP_SOR_LOAD_DATE
        df_EXP_SOR_LOAD_DATE = lib.expression(
            input_df=df_SQ_SSA_EMS_RFX_UNIT_RENT_SCHD_STS,
            computed_columns=[
                {'name': 'OUT_END_DATE', 'expr': "CASE WHEN OPR_IND = 'EB' THEN CASE WHEN LAST_REC_TXN_TYPE_CODE IS NULL THEN to_date('99991231','yyyyMMdd') ELSE END_DATE END ELSE END_DATE END"}
            ],
        )
        ctx.register_df("df_EXP_SOR_LOAD_DATE", df_EXP_SOR_LOAD_DATE)
        
        logger.info("Step: write_SOR_EMS_RFX_UNIT_RENT_SCHD_STS")
        # Write to Target: write_SOR_EMS_RFX_UNIT_RENT_SCHD_STS
        lib.write_target(
            spark=spark,
            df=df_EXP_SOR_LOAD_DATE,
            conn=conn_target,
            table='SOR_EMS_RFX_UNIT_RENT_SCHD',
            mode='append',
            source_columns=[
                'UNIT_RENT_SCHD_KEY',
                None,
                None,
                None,
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            target_columns=[
                'UNIT_RENT_SCHD_KEY',
                'UNIT_RENT_SCHD_BK',
                'UNIT_KEY',
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            config=config,
        )

        logger.info("write_SOR_EMS_RFX_UNIT_RENT_SCHD_STS write completed")
        
        metrics.complete()
        logger.info("Mapping M_S5_SOR_LOAD_EMS_RFX_UNIT_RENT_SCHD_FOR_INSERT completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_S5_SOR_LOAD_EMS_RFX_UNIT_RENT_SCHD_FOR_INSERT FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_S5_SOR_LOAD_EMS_RFX_UNIT_RENT_SCHD_FOR_INSERT", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_S5_SOR_LOAD_EMS_RFX_UNIT_RENT_SCHD_FOR_INSERT")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())