'''
* Script - M_S5_SSAL2_TRANSFORM_EMS_HSM_HOMES_BLK.py
* @date    2026-07-02
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
from pyspark.sql import DataFrame
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None) -> bool:
    """
    Execute the M_S5_SSAL2_TRANSFORM_EMS_HSM_HOMES_BLK mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
    
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_S5_SSAL2_TRANSFORM_EMS_HSM_HOMES_BLK")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_S5_SSAL2_TRANSFORM_EMS_HSM_HOMES_BLK", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_oracle = lib.get_db_config(config, "oracle-defaults")
    conn_source = lib.get_db_config(config, "SSA")
    conn_target = lib.get_db_config(config, "SSA")

    v_snsh_date = ""
    v_init_flag = ""
    # Load mapping variables from job_params or UTL_JOB_PARAM file
    if job_params:
        for _var, _val in job_params.items():
            _clean = _var.replace("$", "")
            if _clean in [ "v_snsh_date",  "v_init_flag", ]:
                if _clean == "v_snsh_date":
                    v_snsh_date = _val
                if _clean == "v_init_flag":
                    v_init_flag = _val
                logger.info("Loaded %s=%s from job_params", _var, _val)
    else:
        try:
            _param_obj = objects.get("UTL_JOB_PARAM", {})
            if isinstance(_param_obj, dict):
                _param_path = lib._resolve_path(_param_obj.get('path', '/tmp/UTL_JOB_PARAM'))
            with open(_param_path, "r") as _f:
                for _line in _f:
                    _line = _line.strip()
                    for _var in [ "$$v_snsh_date",  "$$v_init_flag", ]:
                        if _line.startswith(_var + "="):
                            _val = _line.split("=", 1)[1]
                            _clean = _var.replace("$", "")
                            if _clean == "v_snsh_date":
                                v_snsh_date = _val
                            if _clean == "v_init_flag":
                                v_init_flag = _val
                            logger.info("Loaded %s=%s from %s", _var, _val, _param_path)
        except Exception:
            logger.warning("UTL_JOB_PARAM not found, using default values")
    
    try:
        logger.info("Step: read_EMS_HSM_HOMES_BLK")
        # Reading Data From Source - read_EMS_HSM_HOMES_BLK
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_src_1 = lib.read_sql(spark, _conn, table="EMS_HSM_HOMES_BLK")
        
        logger.info("Step: apply_SQ_EMS_HSM_HOMES_BLK")
        # Source Qualifier: apply_SQ_EMS_HSM_HOMES_BLK
        df_sq_2 = df_src_1
        # Select only SQ output ports (matches Informatica behavior)
        df_sq_2 = df_sq_2.select("HOMES_PROJ_CODE", "HOMES_PROJ_PHASE_CODE", "HOMES_BLK_ID", "HOMES_DOM_TYPE_CODE", "HSE_BLK_STRY_NUM", "DTL_REC_RMK_TEXT", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID")
        ctx.register_df("df_sq_2", df_sq_2)
        
        logger.info("Step: apply_EXPTRANS")
        # Expression: apply_EXPTRANS
        df_exp_3 = df_sq_2
        df_exp_3 = df_exp_3.withColumn("DUMMY_DATE", expr("NULL"))
        df_exp_3 = df_exp_3.withColumn("HOMES_PROJ_CODE_V", expr("CASE WHEN (HOMES_PROJ_CODE IS NULL) THEN ' ' ELSE HOMES_PROJ_CODE END"))
        df_exp_3 = df_exp_3.withColumn("HOMES_PROJ_PHASE_CODE_V", expr("CASE WHEN (HOMES_PROJ_PHASE_CODE IS NULL) THEN ' ' ELSE HOMES_PROJ_PHASE_CODE END"))
        df_exp_3 = df_exp_3.withColumn("HOMES_BLK_ID_V", expr("CASE WHEN (HOMES_BLK_ID IS NULL) THEN ' ' ELSE HOMES_BLK_ID END"))
        df_exp_3 = df_exp_3.withColumn("HOMES_PROJ_BK", expr("rpad(HOMES_PROJ_CODE_V,6,' ') || rpad(HOMES_PROJ_PHASE_CODE_V,3,' ')"))
        df_exp_3 = df_exp_3.withColumn("HOMES_BLK_BK", expr("rpad(HOMES_PROJ_CODE_V,6,' ') || rpad(HOMES_PROJ_PHASE_CODE_V,3,' ') || rpad(HOMES_BLK_ID_V,6,' ')"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["HOMES_PROJ_CODE", "HOMES_PROJ_PHASE_CODE", "HOMES_BLK_ID", "HOMES_DOM_TYPE_CODE", "HSE_BLK_STRY_NUM", "DTL_REC_RMK_TEXT", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID"]:
            if _col not in df_exp_3.columns:
                df_exp_3 = df_exp_3.withColumn(_col, lit(None))
        # Select only mapping output ports (prevents column leakage)
        df_exp_3 = df_exp_3.select("HOMES_PROJ_CODE", "HOMES_PROJ_PHASE_CODE", "HOMES_BLK_ID", "HOMES_DOM_TYPE_CODE", "HSE_BLK_STRY_NUM", "DTL_REC_RMK_TEXT", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "LAST_REC_TXN_USER_ID", "HOMES_BLK_BK", "HOMES_PROJ_BK", "DUMMY_DATE")
        ctx.register_df("df_exp_3", df_exp_3)
        
        logger.info("Step: input_MPLT_AGMT_EMS_HSM_HOMES_PROJ")
        # Expression: input_MPLT_AGMT_EMS_HSM_HOMES_PROJ
        df_mplt_input_4 = df_exp_3
        df_mplt_input_4 = df_mplt_input_4.withColumn("IN_HOMES_PROJ_BK", expr("HOMES_PROJ_BK"))
        ctx.register_df("df_mplt_input_4", df_mplt_input_4)
        
        logger.info("Step: apply_mplt_EXP_NULL_BKEY")
        # Expression: apply_mplt_EXP_NULL_BKEY
        df_mplt_expr_5 = df_mplt_input_4
        df_mplt_expr_5 = df_mplt_expr_5.withColumn("OUT_BKEY", expr("CASE WHEN ltrim(rtrim(IN_HOMES_PROJ_BK)) = NULL THEN 'UNKNOWN' WHEN ltrim(rtrim(IN_HOMES_PROJ_BK)) = '' THEN 'UNKNOWN' ELSE IN_HOMES_PROJ_BK END"))
        ctx.register_df("df_mplt_expr_5", df_mplt_expr_5)
        
        logger.info("Step: apply_mplt_EXPTRANS")
        # Expression: apply_mplt_EXPTRANS
        df_mplt_expr_6 = df_mplt_expr_5
        df_mplt_expr_6 = df_mplt_expr_6.withColumn("IN_HOMES_PROJ_BK", expr("OUT_BKEY"))
        df_mplt_expr_6 = df_mplt_expr_6.withColumn("IN_HOMES_PROJ_CODE", expr("NULL"))
        df_mplt_expr_6 = df_mplt_expr_6.withColumn("IN_HOMES_PROJ_PHASE_CODE", expr("NULL"))
        ctx.register_df("df_mplt_expr_6", df_mplt_expr_6)
        
        logger.info("Step: read_mplt_LKP_DYN_SOR_EMS_HSM_HOMES_PROJ")
        # Reading Data From Source - read_mplt_LKP_DYN_SOR_EMS_HSM_HOMES_PROJ
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "target")
        df_mplt_lkp_7 = lib.read_sql(spark, _conn, table="SOR_EMS_HSM_HOMES_PROJ")
        
        logger.info("Step: apply_mplt_LKP_DYN_SOR_EMS_HSM_HOMES_PROJ")
        # Lookup: apply_mplt_LKP_DYN_SOR_EMS_HSM_HOMES_PROJ
        # Join condition: HOMES_PROJ_BK=HOMES_PROJ_BK        
        df_mplt_join_8 = df_mplt_expr_6.join(
            broadcast(df_mplt_lkp_7),
            (df_mplt_expr_6["HOMES_PROJ_BK"] == df_mplt_lkp_7["HOMES_PROJ_BK"]),
            "left"
        )
        ctx.register_df("df_mplt_join_8", df_mplt_join_8)
        
        logger.info("Step: apply_mplt_EXP_SK")
        # Expression: apply_mplt_EXP_SK
        df_mplt_expr_9 = df_mplt_join_8
        df_mplt_expr_9 = df_mplt_expr_9.withColumn("SOR_CACHE_STATUS", expr("NewLookupRow"))
        df_mplt_expr_9 = df_mplt_expr_9.withColumn("OUT_TABLE_NAME", expr("'SSA_EMS_HSM_HOMES_PROJ'"))
        ctx.register_df("df_mplt_expr_9", df_mplt_expr_9)
        
        logger.info("Step: read_mplt_LKP_DYN_SSA_EMS_HSM_HOMES_PROJ")
        # Reading Data From Source - read_mplt_LKP_DYN_SSA_EMS_HSM_HOMES_PROJ
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "source_db")
        query = f"""SELECT HOMES_PROJ_KEY AS SURROGATE_KEY, 'S' AS DUMMY  FROM SSA_EMS_HSM_HOMES_PROJ"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_mplt_lkp_10 = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_mplt_LKP_DYN_SSA_EMS_HSM_HOMES_PROJ")
        # Lookup: apply_mplt_LKP_DYN_SSA_EMS_HSM_HOMES_PROJ
        # Join condition: HOMES_PROJ_KEY=SURROGATE_KEY        
        df_mplt_join_11 = df_mplt_expr_9.join(
            broadcast(df_mplt_lkp_10),
            (df_mplt_expr_9["HOMES_PROJ_KEY"] == df_mplt_lkp_10["SURROGATE_KEY"]),
            "left"
        )
        ctx.register_df("df_mplt_join_11", df_mplt_join_11)
        
        logger.info("Step: apply_mplt_EXPTRANS1")
        # Expression: apply_mplt_EXPTRANS1
        df_mplt_expr_12 = df_mplt_join_11
        df_mplt_expr_12 = df_mplt_expr_12.withColumn("IN_DLPK_SOR_CACHE", expr("SOR_CACHE_STATUS"))
        df_mplt_expr_12 = df_mplt_expr_12.withColumn("V_AUG_IND", expr("CASE WHEN SOR_CACHE_STATUS = 1 THEN 'Y' ELSE 'N' END"))
        df_mplt_expr_12 = df_mplt_expr_12.withColumn("OPR_IND", expr("'A'"))
        df_mplt_expr_12 = df_mplt_expr_12.withColumn("LAST_REC_TXN_TYPE_CODE", expr("NULL"))
        ctx.register_df("df_mplt_expr_12", df_mplt_expr_12)
        
        logger.info("Step: apply_MPLT_AGMT_EMS_HSM_HOMES_PROJ")
        # Expression: apply_MPLT_AGMT_EMS_HSM_HOMES_PROJ
        df_mplt_13 = df_mplt_expr_12
        ctx.register_df("df_mplt_13", df_mplt_13)
        
        logger.info("Step: apply_FILTRANS21")
        # Filter: apply_FILTRANS21
        df_fil_14 = df_mplt_13.filter(expr("SOR_CACHE_STATUS = 1"))
        ctx.register_df("df_fil_14", df_fil_14)
        
        logger.info("Step: read_LKP_DYN_SOR_EMS_HSM_HOMES_BLK")
        # Reading Data From Source - read_LKP_DYN_SOR_EMS_HSM_HOMES_BLK
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_lkp_15 = lib.read_sql(spark, _conn, table="SOR_EMS_HSM_HOMES_BLK")
        
        logger.info("Step: apply_LKP_DYN_SOR_EMS_HSM_HOMES_BLK")
        # Lookup: apply_LKP_DYN_SOR_EMS_HSM_HOMES_BLK
        # Join condition: IN_HOMES_BLK_BK=HOMES_BLK_BK        
        df_lkp_result_16 = df_mplt_13.join(
            broadcast(df_lkp_15),
            (df_mplt_13["IN_HOMES_BLK_BK"] == df_lkp_15["HOMES_BLK_BK"]),
            "left"
        )
        ctx.register_df("df_lkp_result_16", df_lkp_result_16)
        
        logger.info("Step: write_SSA_EMS_HSM_HOMES_PROJ")
        # Write to Target: write_SSA_EMS_HSM_HOMES_PROJ
        df_write = df_fil_14
        # Cast columns to match target schema data types
        if "homes_proj_bk" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_proj_bk":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "homes_proj_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_proj_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "homes_proj_phase_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_proj_phase_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "agmt_ind" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "agmt_ind":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_type_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_type_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        if "opr_ind" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "opr_ind":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "sor_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "sor_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("LAST_REC_TXN_DATE", lit(None).cast(StringType()))
        df_write = df_write.withColumn("SOR_DATE", lit(None).cast(StringType()))
        # Map source columns to target columns using connector field map (handles name mismatches)
        _field_map = {"AGMT_IND": "V_AUG_IND", "HOMES_PROJ_BK": "HOMES_PROJ_BK", "HOMES_PROJ_CODE": "HOMES_PROJ_CODE", "HOMES_PROJ_KEY": "HOMES_PROJ_KEY", "HOMES_PROJ_PHASE_CODE": "HOMES_PROJ_PHASE_CODE", "LAST_REC_TXN_TYPE_CODE": "LAST_REC_TXN_TYPE_CODE", "OPR_IND": "OPR_IND"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col not in df_write.columns and _src_col in df_write.columns:
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['HOMES_PROJ_KEY', 'HOMES_PROJ_BK', 'HOMES_PROJ_CODE', 'HOMES_PROJ_PHASE_CODE', 'AGMT_IND', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'OPR_IND', 'SOR_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col in df_write.columns])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "SSA_EMS_HSM_HOMES_PROJ", mode="append")

        logger.info("write_SSA_EMS_HSM_HOMES_PROJ write completed")
        logger.info("Step: apply_FILTRANS")
        # Filter: apply_FILTRANS
        df_fil_17 = df_lkp_result_16.filter(expr("NewLookupRow > 0 OR LAST_REC_TXN_TYPE_CODE = 'D'"))
        ctx.register_df("df_fil_17", df_fil_17)
        
        logger.info("Step: read_LKP_DYN_SOR_EMS_HSM_HOMES_BLK_STS")
        # Reading Data From Source - read_LKP_DYN_SOR_EMS_HSM_HOMES_BLK_STS
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT SOR_EMS_HSM_HOMES_BLK_STS.BGN_DATE as BGN_DATE, SOR_EMS_HSM_HOMES_BLK_STS.HOMES_DOM_TYPE_CODE as HOMES_DOM_TYPE_CODE, SOR_EMS_HSM_HOMES_BLK_STS.BLK_STRY_NUM as BLK_STRY_NUM, SOR_EMS_HSM_HOMES_BLK_STS.DTL_REC_RMK_TEXT as DTL_REC_RMK_TEXT, SOR_EMS_HSM_HOMES_BLK_STS.HOMES_BLK_KEY as HOMES_BLK_KEY FROM SOR_EMS_HSM_HOMES_BLK_STS
WHERE SOR_EMS_HSM_HOMES_BLK_STS.END_DATE = TO_DATE ('99991231', 'YYYYMMDD')"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_lkp_18 = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DYN_SOR_EMS_HSM_HOMES_BLK_STS")
        # Lookup: apply_LKP_DYN_SOR_EMS_HSM_HOMES_BLK_STS
        # Join condition: IN_HOMES_BLK_KEY=HOMES_BLK_KEY        
        df_lkp_result_19 = df_lkp_result_16.join(
            broadcast(df_lkp_18),
            (df_lkp_result_16["IN_HOMES_BLK_KEY"] == df_lkp_18["HOMES_BLK_KEY"]),
            "left"
        )
        ctx.register_df("df_lkp_result_19", df_lkp_result_19)
        
        logger.info("Step: apply_EXPTRANS1")
        # Expression: apply_EXPTRANS1
        df_exp_20 = df_fil_17
        _expr = """to_date('$$v_snsh_date','yyyyMMdd')"""
        _expr = _expr.replace("$$v_snsh_date", str(v_snsh_date))
        _expr = _expr.replace("$$v_init_flag", str(v_init_flag))
        df_exp_20 = df_exp_20.withColumn("SNAPSHOT_DATE", expr(_expr))
        df_exp_20 = df_exp_20.withColumn("IN_CACHE_STATUS", expr("NewLookupRow"))
        df_exp_20 = df_exp_20.withColumn("v_SSAL2_TBL_NAME", expr("'SSA_EMS_HSM_HOMES_BLK'"))
        df_exp_20 = df_exp_20.withColumn("AGMT_IND", expr("'N'"))
        df_exp_20 = df_exp_20.withColumn("DELETE_IND", expr("CASE WHEN LAST_REC_TXN_TYPE_CODE = 'D' THEN 'Y' ELSE 'N' END"))
        df_exp_20 = df_exp_20.withColumn("LST_UPT_DTIME", expr("NULL"))
        _expr = """'$$v_init_flag'"""
        _expr = _expr.replace("$$v_snsh_date", str(v_snsh_date))
        _expr = _expr.replace("$$v_init_flag", str(v_init_flag))
        df_exp_20 = df_exp_20.withColumn("INIT_FLAG", expr(_expr))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        # Select only mapping output ports (prevents column leakage)
        df_exp_20 = df_exp_20.select("SNAPSHOT_DATE", "IN_CACHE_STATUS", "v_SSAL2_TBL_NAME", "AGMT_IND", "DELETE_IND", "LST_UPT_DTIME", "INIT_FLAG")
        ctx.register_df("df_exp_20", df_exp_20)
        
        logger.info("Step: apply_FILTRANS1")
        # Filter: apply_FILTRANS1
        df_fil_21 = df_lkp_result_19.filter(expr("NewLookupRow > 0 OR LAST_REC_TXN_TYPE_CODE = 'D'"))
        ctx.register_df("df_fil_21", df_fil_21)
        
        logger.info("Step: read_LKP_DYN_SSA_EMS_HSM_HOMES_BLK")
        # Reading Data From Source - read_LKP_DYN_SSA_EMS_HSM_HOMES_BLK
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT HOMES_BLK_KEY AS SURROGATE_KEY, 'S' AS DUMMY  FROM SSA_EMS_HSM_HOMES_BLK"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_lkp_22 = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DYN_SSA_EMS_HSM_HOMES_BLK")
        # Lookup: apply_LKP_DYN_SSA_EMS_HSM_HOMES_BLK
        # Join condition: IN_SURROGATE_KEY=SURROGATE_KEY        
        df_lkp_result_23 = df_exp_20.join(
            broadcast(df_lkp_22),
            (df_exp_20["IN_SURROGATE_KEY"] == df_lkp_22["SURROGATE_KEY"]),
            "left"
        )
        ctx.register_df("df_lkp_result_23", df_lkp_result_23)
        
        logger.info("Step: apply_EXPTRANS11")
        # Expression: apply_EXPTRANS11
        df_exp_24 = df_fil_21
        _expr = """to_date('$$v_snsh_date','yyyyMMdd')"""
        _expr = _expr.replace("$$v_snsh_date", str(v_snsh_date))
        _expr = _expr.replace("$$v_init_flag", str(v_init_flag))
        df_exp_24 = df_exp_24.withColumn("SNAPSHOT_DATE", expr(_expr))
        df_exp_24 = df_exp_24.withColumn("IN_CACHE_STATUS", expr("NewLookupRow"))
        df_exp_24 = df_exp_24.withColumn("v_SSAL2_TBL_NAME", expr("'SSA_EMS_HSM_HOMES_BLK_STS'"))
        df_exp_24 = df_exp_24.withColumn("AGMT_IND", expr("'N'"))
        df_exp_24 = df_exp_24.withColumn("DELETE_IND", expr("CASE WHEN LAST_REC_TXN_TYPE_CODE = 'D' THEN 'Y' ELSE 'N' END"))
        df_exp_24 = df_exp_24.withColumn("LST_UPT_DTIME", expr("NULL"))
        _expr = """'$$v_init_flag'"""
        _expr = _expr.replace("$$v_snsh_date", str(v_snsh_date))
        _expr = _expr.replace("$$v_init_flag", str(v_init_flag))
        df_exp_24 = df_exp_24.withColumn("INIT_FLAG", expr(_expr))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        # Select only mapping output ports (prevents column leakage)
        df_exp_24 = df_exp_24.select("SNAPSHOT_DATE", "IN_CACHE_STATUS", "v_SSAL2_TBL_NAME", "AGMT_IND", "DELETE_IND", "LST_UPT_DTIME", "INIT_FLAG")
        ctx.register_df("df_exp_24", df_exp_24)
        
        logger.info("Step: join_MPLT_DLKP_CACHE_STATUS_0")
        # Lookup: join_MPLT_DLKP_CACHE_STATUS_0
        # Merge parallel DataFrames on their common columns
        _common_cols = [c for c in df_lkp_result_23.columns if c in df_exp_20.columns]
        df_mplt_merge_25 = df_lkp_result_23.join(
            df_exp_20,
            on=_common_cols,
            how="left"
        )
        ctx.register_df("df_mplt_merge_25", df_mplt_merge_25)
        
        logger.info("Step: input_MPLT_DLKP_CACHE_STATUS")
        # Expression: input_MPLT_DLKP_CACHE_STATUS
        df_mplt_input_26 = df_mplt_merge_25
        df_mplt_input_26 = df_mplt_input_26.withColumn("IN_V_SNAPSHOT_DATE", expr("SNAPSHOT_DATE"))
        df_mplt_input_26 = df_mplt_input_26.withColumn("IN_V_DLKP_SOR_CACHE_STATUS", expr("IN_CACHE_STATUS"))
        df_mplt_input_26 = df_mplt_input_26.withColumn("IN_AGMT_IND", expr("AGMT_IND"))
        df_mplt_input_26 = df_mplt_input_26.withColumn("IN_V_DEL_IND", expr("DELETE_IND"))
        df_mplt_input_26 = df_mplt_input_26.withColumn("IN_V_INIT_IND", expr("INIT_FLAG"))
        df_mplt_input_26 = df_mplt_input_26.withColumn("IN_V_LAST_UPDATE_DATE", expr("LST_UPT_DTIME"))
        df_mplt_input_26 = df_mplt_input_26.withColumn("IN_V_DLKP_SSA_CACHE_STATUS", expr("NewLookupRow"))
        ctx.register_df("df_mplt_input_26", df_mplt_input_26)
        
        logger.info("Step: apply_mplt_EXPTRANS2")
        # Expression: apply_mplt_EXPTRANS2
        df_mplt_expr_27 = df_mplt_input_26
        df_mplt_expr_27 = df_mplt_expr_27.withColumn("IN_DEL_FLAG", expr("IN_V_DEL_IND"))
        df_mplt_expr_27 = df_mplt_expr_27.withColumn("UPDATE_STRATEGY_STATUS", expr("CASE WHEN IN_V_DLKP_SOR_CACHE_STATUS = 1 THEN DD_INSERT ELSE CASE WHEN IN_V_DLKP_SSA_CACHE_STATUS = 1 THEN DD_INSERT ELSE DD_UPDATE END END"))
        df_mplt_expr_27 = df_mplt_expr_27.withColumn("AGMT_IND", expr("IN_AGMT_IND"))
        df_mplt_expr_27 = df_mplt_expr_27.withColumn("TABLE_NAME", expr("IN_TABLE_NAME"))
        df_mplt_expr_27 = df_mplt_expr_27.withColumn("NEW_FLAG", expr("CASE WHEN IN_V_DLKP_SOR_CACHE_STATUS = 1 THEN 1 ELSE 0 END"))
        df_mplt_expr_27 = df_mplt_expr_27.withColumn("CHG_FLAG", expr("CASE WHEN IN_V_DLKP_SOR_CACHE_STATUS = 2 THEN 1 ELSE 0 END"))
        df_mplt_expr_27 = df_mplt_expr_27.withColumn("DEL_FLAG", expr("CASE WHEN IN_V_DEL_IND = 'Y' THEN 1 WHEN IN_V_DEL_IND = 'y' THEN 1 ELSE 0 END"))
        df_mplt_expr_27 = df_mplt_expr_27.withColumn("SNAPSHOT_DATE", expr("IN_V_SNAPSHOT_DATE"))
        ctx.register_df("df_mplt_expr_27", df_mplt_expr_27)
        
        logger.info("Step: apply_mplt_EXP_SSAL2_TRANSFORM2")
        # Expression: apply_mplt_EXP_SSAL2_TRANSFORM2
        df_mplt_expr_28 = df_mplt_input_26
        df_mplt_expr_28 = df_mplt_expr_28.withColumn("CDC_FLAG", expr("CASE WHEN 1 = NEW_FLAG THEN 1 WHEN 1 = CHG_FLAG THEN 1 WHEN 1 = DEL_FLAG THEN 1 ELSE 0 END"))
        df_mplt_expr_28 = df_mplt_expr_28.withColumn("SOR_DATE", expr("IN_SOR_DATE"))
        df_mplt_expr_28 = df_mplt_expr_28.withColumn("OPR_IND", expr("V_OPR_IND"))
        df_mplt_expr_28 = df_mplt_expr_28.withColumn("AGMT_IND", expr("'N'"))
        df_mplt_expr_28 = df_mplt_expr_28.withColumn("BGN_DATE", expr("CASE WHEN V_OPR_IND='B' AND IN_V_INIT_IND = 'Y' THEN to_date('19000101','yyyyMMdd') ELSE SNAPSHOT_DATE END"))
        df_mplt_expr_28 = df_mplt_expr_28.withColumn("END_DATE", expr("CASE WHEN DEL_FLAG = 1 THEN CASE WHEN IN_V_INIT_IND = 'Y' THEN CASE WHEN IN_V_LAST_UPDATE_DATE = NULL THEN date_add(SNAPSHOT_DATE, CAST(-1 AS INT)) ELSE IN_V_LAST_UPDATE_DATE END ELSE date_add(SNAPSHOT_DATE, CAST(-1 AS INT)) END ELSE CASE WHEN NEW_FLAG = 1 THEN to_date('99991231','yyyyMMdd') ELSE CASE WHEN CHG_FLAG = 1 THEN date_add(SNAPSHOT_DATE, CAST(-1 AS INT)) ELSE NULL END END END"))
        df_mplt_expr_28 = df_mplt_expr_28.withColumn("LAST_REC_TXN_DATE", expr("current_timestamp()"))
        df_mplt_expr_28 = df_mplt_expr_28.withColumn("LAST_REC_TXN_TYPE_CODE", expr("CASE WHEN DEL_FLAG = 1 THEN 'D' ELSE NULL END"))
        ctx.register_df("df_mplt_expr_28", df_mplt_expr_28)
        
        logger.info("Step: apply_mplt_EXPTRANS")
        # Expression: apply_mplt_EXPTRANS
        df_mplt_expr_29 = df_mplt_expr_27
        df_mplt_expr_29 = df_mplt_expr_29.withColumn("OUT_V_OPR_IND", expr("CASE WHEN AGMT_IND = 'Y' THEN 'A' ELSE OPR_IND END"))
        df_mplt_expr_29 = df_mplt_expr_29.withColumn("OUT_BGN_DATE", expr("CASE WHEN OPR_IND='B' AND DEL_FLAG = 1 THEN to_date('19000101','yyyyMMdd') ELSE BGN_DATE END"))
        ctx.register_df("df_mplt_expr_29", df_mplt_expr_29)
        
        logger.info("Step: join_output_MPLT_DLKP_CACHE_STATUS_0")
        # Lookup: join_output_MPLT_DLKP_CACHE_STATUS_0
        # Merge parallel DataFrames on their common columns
        _common_cols = [c for c in df_mplt_expr_29.columns if c in df_mplt_expr_28.columns]
        df_mplt_merge_30 = df_mplt_expr_29.join(
            df_mplt_expr_28,
            on=_common_cols,
            how="left"
        )
        ctx.register_df("df_mplt_merge_30", df_mplt_merge_30)
        
        logger.info("Step: join_output_MPLT_DLKP_CACHE_STATUS_1")
        # Lookup: join_output_MPLT_DLKP_CACHE_STATUS_1
        # Merge parallel DataFrames on their common columns
        _common_cols = [c for c in df_mplt_merge_30.columns if c in df_mplt_expr_27.columns]
        df_mplt_merge_31 = df_mplt_merge_30.join(
            df_mplt_expr_27,
            on=_common_cols,
            how="left"
        )
        ctx.register_df("df_mplt_merge_31", df_mplt_merge_31)
        
        logger.info("Step: apply_MPLT_DLKP_CACHE_STATUS")
        # Expression: apply_MPLT_DLKP_CACHE_STATUS
        df_mplt_32 = df_mplt_merge_31
        ctx.register_df("df_mplt_32", df_mplt_32)
        
        logger.info("Step: read_LKP_DYN_SSA_EMS_HSM_HOMES_BLK_STS")
        # Reading Data From Source - read_LKP_DYN_SSA_EMS_HSM_HOMES_BLK_STS
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        query = f"""SELECT HOMES_BLK_KEY AS SURROGATE_KEY, 'S' AS DUMMY  FROM SSA_EMS_HSM_HOMES_BLK_STS"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        query = query.replace("$$v_init_flag", v_init_flag)
        df_lkp_33 = lib.read_sql(spark, _conn, query=query)
        
        logger.info("Step: apply_LKP_DYN_SSA_EMS_HSM_HOMES_BLK_STS")
        # Lookup: apply_LKP_DYN_SSA_EMS_HSM_HOMES_BLK_STS
        # Join condition: IN_SURROGATE_KEY=SURROGATE_KEY        
        df_lkp_result_34 = df_fil_21.join(
            broadcast(df_lkp_33),
            (df_fil_21["IN_SURROGATE_KEY"] == df_lkp_33["SURROGATE_KEY"]),
            "left"
        )
        ctx.register_df("df_lkp_result_34", df_lkp_result_34)
        
        logger.info("Step: apply_UPD_SSAL2_MSTR1")
        # Update Strategy: apply_UPD_SSAL2_MSTR1
        # Strategy: OUT_V_UPD_STRATEGY_STATUS
        df_upd_35 = df_fil_17.withColumn("_update_strategy", lit("INSERT"))
        ctx.register_df("df_upd_35", df_upd_35)
        
        logger.info("Step: join_MPLT_DLKP_CACHE_STATUS1_0")
        # Lookup: join_MPLT_DLKP_CACHE_STATUS1_0
        # Merge parallel DataFrames on their common columns
        _common_cols = [c for c in df_lkp_result_34.columns if c in df_exp_24.columns]
        df_mplt_merge_36 = df_lkp_result_34.join(
            df_exp_24,
            on=_common_cols,
            how="left"
        )
        ctx.register_df("df_mplt_merge_36", df_mplt_merge_36)
        
        logger.info("Step: join_MPLT_DLKP_CACHE_STATUS1_1")
        # Lookup: join_MPLT_DLKP_CACHE_STATUS1_1
        # Merge parallel DataFrames on their common columns
        _common_cols = [c for c in df_mplt_merge_36.columns if c in df_fil_21.columns]
        df_mplt_merge_37 = df_mplt_merge_36.join(
            df_fil_21,
            on=_common_cols,
            how="left"
        )
        ctx.register_df("df_mplt_merge_37", df_mplt_merge_37)
        
        logger.info("Step: input_MPLT_DLKP_CACHE_STATUS1")
        # Expression: input_MPLT_DLKP_CACHE_STATUS1
        df_mplt_input_38 = df_mplt_merge_37
        df_mplt_input_38 = df_mplt_input_38.withColumn("IN_V_SNAPSHOT_DATE", expr("SNAPSHOT_DATE"))
        df_mplt_input_38 = df_mplt_input_38.withColumn("IN_V_DLKP_SOR_CACHE_STATUS", expr("IN_CACHE_STATUS"))
        df_mplt_input_38 = df_mplt_input_38.withColumn("IN_V_DEL_IND", expr("DELETE_IND"))
        df_mplt_input_38 = df_mplt_input_38.withColumn("IN_V_INIT_IND", expr("INIT_FLAG"))
        df_mplt_input_38 = df_mplt_input_38.withColumn("IN_V_LAST_UPDATE_DATE", expr("LST_UPT_DTIME"))
        df_mplt_input_38 = df_mplt_input_38.withColumn("IN_V_DLKP_SSA_CACHE_STATUS", expr("NewLookupRow"))
        df_mplt_input_38 = df_mplt_input_38.withColumn("IN_SOR_DATE", expr("BGN_DATE"))
        ctx.register_df("df_mplt_input_38", df_mplt_input_38)
        
        logger.info("Step: apply_mplt_EXPTRANS2")
        # Expression: apply_mplt_EXPTRANS2
        df_mplt_expr_39 = df_mplt_input_38
        df_mplt_expr_39 = df_mplt_expr_39.withColumn("IN_DEL_FLAG", expr("IN_V_DEL_IND"))
        df_mplt_expr_39 = df_mplt_expr_39.withColumn("UPDATE_STRATEGY_STATUS", expr("CASE WHEN IN_V_DLKP_SOR_CACHE_STATUS = 1 THEN DD_INSERT ELSE CASE WHEN IN_V_DLKP_SSA_CACHE_STATUS = 1 THEN DD_INSERT ELSE DD_UPDATE END END"))
        df_mplt_expr_39 = df_mplt_expr_39.withColumn("AGMT_IND", expr("IN_AGMT_IND"))
        df_mplt_expr_39 = df_mplt_expr_39.withColumn("TABLE_NAME", expr("IN_TABLE_NAME"))
        df_mplt_expr_39 = df_mplt_expr_39.withColumn("NEW_FLAG", expr("CASE WHEN IN_V_DLKP_SOR_CACHE_STATUS = 1 THEN 1 ELSE 0 END"))
        df_mplt_expr_39 = df_mplt_expr_39.withColumn("CHG_FLAG", expr("CASE WHEN IN_V_DLKP_SOR_CACHE_STATUS = 2 THEN 1 ELSE 0 END"))
        df_mplt_expr_39 = df_mplt_expr_39.withColumn("DEL_FLAG", expr("CASE WHEN IN_V_DEL_IND = 'Y' THEN 1 WHEN IN_V_DEL_IND = 'y' THEN 1 ELSE 0 END"))
        df_mplt_expr_39 = df_mplt_expr_39.withColumn("SNAPSHOT_DATE", expr("IN_V_SNAPSHOT_DATE"))
        ctx.register_df("df_mplt_expr_39", df_mplt_expr_39)
        
        logger.info("Step: apply_mplt_EXP_SSAL2_TRANSFORM2")
        # Expression: apply_mplt_EXP_SSAL2_TRANSFORM2
        df_mplt_expr_40 = df_mplt_input_38
        df_mplt_expr_40 = df_mplt_expr_40.withColumn("CDC_FLAG", expr("CASE WHEN 1 = NEW_FLAG THEN 1 WHEN 1 = CHG_FLAG THEN 1 WHEN 1 = DEL_FLAG THEN 1 ELSE 0 END"))
        df_mplt_expr_40 = df_mplt_expr_40.withColumn("SOR_DATE", expr("IN_SOR_DATE"))
        df_mplt_expr_40 = df_mplt_expr_40.withColumn("OPR_IND", expr("V_OPR_IND"))
        df_mplt_expr_40 = df_mplt_expr_40.withColumn("AGMT_IND", expr("'N'"))
        df_mplt_expr_40 = df_mplt_expr_40.withColumn("BGN_DATE", expr("CASE WHEN V_OPR_IND='B' AND IN_V_INIT_IND = 'Y' THEN to_date('19000101','yyyyMMdd') ELSE SNAPSHOT_DATE END"))
        df_mplt_expr_40 = df_mplt_expr_40.withColumn("END_DATE", expr("CASE WHEN DEL_FLAG = 1 THEN CASE WHEN IN_V_INIT_IND = 'Y' THEN CASE WHEN IN_V_LAST_UPDATE_DATE = NULL THEN date_add(SNAPSHOT_DATE, CAST(-1 AS INT)) ELSE IN_V_LAST_UPDATE_DATE END ELSE date_add(SNAPSHOT_DATE, CAST(-1 AS INT)) END ELSE CASE WHEN NEW_FLAG = 1 THEN to_date('99991231','yyyyMMdd') ELSE CASE WHEN CHG_FLAG = 1 THEN date_add(SNAPSHOT_DATE, CAST(-1 AS INT)) ELSE NULL END END END"))
        df_mplt_expr_40 = df_mplt_expr_40.withColumn("LAST_REC_TXN_DATE", expr("current_timestamp()"))
        df_mplt_expr_40 = df_mplt_expr_40.withColumn("LAST_REC_TXN_TYPE_CODE", expr("CASE WHEN DEL_FLAG = 1 THEN 'D' ELSE NULL END"))
        ctx.register_df("df_mplt_expr_40", df_mplt_expr_40)
        
        logger.info("Step: apply_mplt_EXPTRANS")
        # Expression: apply_mplt_EXPTRANS
        df_mplt_expr_41 = df_mplt_expr_39
        df_mplt_expr_41 = df_mplt_expr_41.withColumn("OUT_V_OPR_IND", expr("CASE WHEN AGMT_IND = 'Y' THEN 'A' ELSE OPR_IND END"))
        df_mplt_expr_41 = df_mplt_expr_41.withColumn("OUT_BGN_DATE", expr("CASE WHEN OPR_IND='B' AND DEL_FLAG = 1 THEN to_date('19000101','yyyyMMdd') ELSE BGN_DATE END"))
        ctx.register_df("df_mplt_expr_41", df_mplt_expr_41)
        
        logger.info("Step: join_output_MPLT_DLKP_CACHE_STATUS1_0")
        # Lookup: join_output_MPLT_DLKP_CACHE_STATUS1_0
        # Merge parallel DataFrames on their common columns
        _common_cols = [c for c in df_mplt_expr_41.columns if c in df_mplt_expr_40.columns]
        df_mplt_merge_42 = df_mplt_expr_41.join(
            df_mplt_expr_40,
            on=_common_cols,
            how="left"
        )
        ctx.register_df("df_mplt_merge_42", df_mplt_merge_42)
        
        logger.info("Step: join_output_MPLT_DLKP_CACHE_STATUS1_1")
        # Lookup: join_output_MPLT_DLKP_CACHE_STATUS1_1
        # Merge parallel DataFrames on their common columns
        _common_cols = [c for c in df_mplt_merge_42.columns if c in df_mplt_expr_39.columns]
        df_mplt_merge_43 = df_mplt_merge_42.join(
            df_mplt_expr_39,
            on=_common_cols,
            how="left"
        )
        ctx.register_df("df_mplt_merge_43", df_mplt_merge_43)
        
        logger.info("Step: apply_MPLT_DLKP_CACHE_STATUS1")
        # Expression: apply_MPLT_DLKP_CACHE_STATUS1
        df_mplt_44 = df_mplt_merge_43
        ctx.register_df("df_mplt_44", df_mplt_44)
        
        logger.info("Step: write_SSA_EMS_HSM_HOMES_BLK")
        # Write to Target: write_SSA_EMS_HSM_HOMES_BLK
        df_write = df_upd_35
        # Cast columns to match target schema data types
        if "homes_blk_bk" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_blk_bk":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "homes_proj_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_proj_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "homes_proj_phase_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_proj_phase_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "homes_blk_id" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_blk_id":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "agmt_ind" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "agmt_ind":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_type_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_type_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        if "opr_ind" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "opr_ind":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "sor_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "sor_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("SOR_DATE", lit(None).cast(StringType()))
        # Map source columns to target columns using connector field map (handles name mismatches)
        _field_map = {"AGMT_IND": "OUT_AGMT_IND", "HOMES_BLK_BK": "HOMES_BLK_BK", "HOMES_BLK_ID": "HOMES_BLK_ID", "HOMES_BLK_KEY": "HOMES_BLK_KEY", "HOMES_PROJ_CODE": "HOMES_PROJ_CODE", "HOMES_PROJ_KEY": "HOMES_PROJ_KEY", "HOMES_PROJ_PHASE_CODE": "HOMES_PROJ_PHASE_CODE", "LAST_REC_TXN_DATE": "OUT_LAST_REC_TXN_DATE", "LAST_REC_TXN_TYPE_CODE": "OUT_LAST_REC_TXN_TYPE_CODE", "OPR_IND": "OUT_OPR_IND"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col not in df_write.columns and _src_col in df_write.columns:
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['HOMES_BLK_KEY', 'HOMES_BLK_BK', 'HOMES_PROJ_KEY', 'HOMES_PROJ_CODE', 'HOMES_PROJ_PHASE_CODE', 'HOMES_BLK_ID', 'AGMT_IND', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'OPR_IND', 'SOR_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col in df_write.columns])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "SSA_EMS_HSM_HOMES_BLK", mode="append")

        logger.info("write_SSA_EMS_HSM_HOMES_BLK write completed")
        logger.info("Step: apply_UPD_SSAL2_MSTR11")
        # Update Strategy: apply_UPD_SSAL2_MSTR11
        # Strategy: OUT_V_UPD_STRATEGY_STATUS
        df_upd_45 = df_fil_21.withColumn("_update_strategy", lit("INSERT"))
        ctx.register_df("df_upd_45", df_upd_45)
        
        logger.info("Step: write_SSA_EMS_HSM_HOMES_BLK_STS")
        # Write to Target: write_SSA_EMS_HSM_HOMES_BLK_STS
        df_write = df_upd_45
        # Cast columns to match target schema data types
        if "homes_blk_bk" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_blk_bk":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "homes_proj_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_proj_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "homes_proj_phase_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_proj_phase_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "homes_blk_id" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "homes_blk_id":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "agmt_ind" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "agmt_ind":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_type_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_type_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        if "opr_ind" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "opr_ind":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "sor_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "sor_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("HOMES_BLK_BK", lit(None).cast(StringType()))
        df_write = df_write.withColumn("HOMES_PROJ_KEY", lit(None).cast(StringType()))
        df_write = df_write.withColumn("HOMES_PROJ_CODE", lit(None).cast(StringType()))
        df_write = df_write.withColumn("HOMES_PROJ_PHASE_CODE", lit(None).cast(StringType()))
        df_write = df_write.withColumn("HOMES_BLK_ID", lit(None).cast(StringType()))
        df_write = df_write.withColumn("AGMT_IND", lit(None).cast(StringType()))
        # Map source columns to target columns using connector field map (handles name mismatches)
        _field_map = {"BGN_DATE": "OUT_V_BGN_DATE", "BLK_STRY_NUM": "BLK_STRY_NUM", "DTL_REC_RMK_TEXT": "DTL_REC_RMK_TEXT", "END_DATE": "OUT_V_END_DATE", "HOMES_BLK_KEY": "HOMES_BLK_KEY", "HOMES_DOM_TYPE_CODE": "HOMES_DOM_TYPE_CODE", "LAST_REC_TXN_DATE": "OUT_LAST_REC_TXN_DATE", "LAST_REC_TXN_TYPE_CODE": "OUT_LAST_REC_TXN_TYPE_CODE", "OPR_IND": "OUT_OPR_IND", "SOR_DATE": "OUT_SOR_DATE"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col not in df_write.columns and _src_col in df_write.columns:
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['HOMES_BLK_KEY', 'HOMES_BLK_BK', 'HOMES_PROJ_KEY', 'HOMES_PROJ_CODE', 'HOMES_PROJ_PHASE_CODE', 'HOMES_BLK_ID', 'AGMT_IND', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE', 'OPR_IND', 'SOR_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col in df_write.columns])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "SSA_EMS_HSM_HOMES_BLK", mode="append")

        logger.info("write_SSA_EMS_HSM_HOMES_BLK_STS write completed")
        
        metrics.complete()
        logger.info("Mapping M_S5_SSAL2_TRANSFORM_EMS_HSM_HOMES_BLK completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_S5_SSAL2_TRANSFORM_EMS_HSM_HOMES_BLK FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_S5_SSAL2_TRANSFORM_EMS_HSM_HOMES_BLK", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_S5_SSAL2_TRANSFORM_EMS_HSM_HOMES_BLK")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        return 0 if success else 1
    finally:
        spark.stop()


if __name__ == "__main__":
    main()