'''
* Script - M_S5_SSAL2_TRANSFORM_EMS_RFX_ALCT_STD.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_S5_SSAL2_TRANSFORM_EMS_RFX_ALCT_STD mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_S5_SSAL2_TRANSFORM_EMS_RFX_ALCT_STD")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_S5_SSAL2_TRANSFORM_EMS_RFX_ALCT_STD", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()


    v_snsh_date = ""
    v_init_flag = ""
    # Load mapping variables from the UTL_JOB_PARAM file (shared helper)
    _vars = lib.load_mapping_variables(config, [ "$$v_snsh_date",  "$$v_init_flag", ], logger)
    v_snsh_date = _vars.get("v_snsh_date", v_snsh_date)
    v_init_flag = _vars.get("v_init_flag", v_init_flag)
    
    try:
        logger.info("Step: read_EMS_RFX_PRH_ALCT_STD")
        # Reading Data From Source - read_EMS_RFX_PRH_ALCT_STD
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_EMS_RFX_PRH_ALCT_STD = lib.read_sql(spark, _conn, table="EMS_RFX_PRH_ALCT_STD")
        
        logger.info("Step: apply_SQ_EMS_RFX_PRH_ALCT_STD")
        # Source Qualifier: apply_SQ_EMS_RFX_PRH_ALCT_STD
        df_SQ_EMS_RFX_PRH_ALCT_STD = df_EMS_RFX_PRH_ALCT_STD
        df_SQ_EMS_RFX_PRH_ALCT_STD = lib.sq_output(
            input_df=df_SQ_EMS_RFX_PRH_ALCT_STD,
            port_cols={
                'HSE_EST_KEY': 'string',
                'HSE_BLK_KEY': 'string',
                'HSE_UNIT_IFA_AREA': 'decimal',
                'HSE_UNIT_ENV_CODE': 'string',
                'TNT_RENT_CODE_CATG_CODE': 'string',
                'HSE_UNIT_ALCT_STD_TYPE_CODE': 'string',
                'HSE_UNIT_TYPE_CODE': 'string',
                'MAX_HSE_UNIT_HEAD_CNT': 'decimal',
                'MIN_HSE_UNIT_HEAD_CNT': 'decimal',
                'TLT_TYPE_CODE': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'LAST_REC_TXN_USER_ID': 'string',
            },
        )
        ctx.register_df("df_SQ_EMS_RFX_PRH_ALCT_STD", df_SQ_EMS_RFX_PRH_ALCT_STD)
        
        logger.info("Step: apply_EXPTRANS")
        # Expression: apply_EXPTRANS
        df_EXPTRANS = lib.expression(
            input_df=df_SQ_EMS_RFX_PRH_ALCT_STD,
            computed_columns=[
                {'name': 'DUMMY_DATE', 'expr': 'NULL'},
                {'name': 'HSE_EST_KEY_V', 'expr': "CASE WHEN (HSE_EST_KEY IS NULL) THEN ' ' ELSE HSE_EST_KEY END"},
                {'name': 'HSE_BLK_KEY_V', 'expr': "CASE WHEN (HSE_BLK_KEY IS NULL) THEN ' ' ELSE HSE_BLK_KEY END"},
                {'name': 'HSE_UNIT_IFA_AREA_V', 'expr': "CASE WHEN (HSE_UNIT_IFA_AREA IS NULL) THEN ' ' ELSE cast(HSE_UNIT_IFA_AREA as string) END"},
                {'name': 'HSE_UNIT_ENV_CODE_V', 'expr': "CASE WHEN (HSE_UNIT_ENV_CODE IS NULL) THEN ' ' ELSE HSE_UNIT_ENV_CODE END"},
                {'name': 'TNT_RENT_CODE_CATG_CODE_V', 'expr': "CASE WHEN (TNT_RENT_CODE_CATG_CODE IS NULL) THEN ' ' ELSE TNT_RENT_CODE_CATG_CODE END"},
                {'name': 'HSE_UNIT_ALCT_STD_TYPE_CODE_V', 'expr': "CASE WHEN (HSE_UNIT_ALCT_STD_TYPE_CODE IS NULL) THEN ' ' ELSE HSE_UNIT_ALCT_STD_TYPE_CODE END"},
                {'name': 'HSE_UNIT_TYPE_CODE_V', 'expr': "CASE WHEN (HSE_UNIT_TYPE_CODE IS NULL) THEN ' ' ELSE HSE_UNIT_TYPE_CODE END"},
                {'name': 'ALCT_STD_BK', 'expr': "rpad(HSE_EST_KEY_V,4,' ') || rpad(HSE_BLK_KEY_V,5,' ') || rpad(HSE_UNIT_IFA_AREA_V,9,' ') || rpad(HSE_UNIT_ENV_CODE_V,10,' ') || rpad(TNT_RENT_CODE_CATG_CODE_V,4,' ') || rpad(HSE_UNIT_ALCT_STD_TYPE_CODE_V, 1, ' ') || rpad(HSE_UNIT_TYPE_CODE_V, 3, ' ')"}
            ],
        )
        ctx.register_df("df_EXPTRANS", df_EXPTRANS)
        
        
        metrics.complete()
        logger.info("Mapping M_S5_SSAL2_TRANSFORM_EMS_RFX_ALCT_STD completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_S5_SSAL2_TRANSFORM_EMS_RFX_ALCT_STD FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_S5_SSAL2_TRANSFORM_EMS_RFX_ALCT_STD", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_S5_SSAL2_TRANSFORM_EMS_RFX_ALCT_STD")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())