'''
* Script - M_S5_SOR_LOAD_EMS_HSP_TNT_INCM_DCLR_FOR_INSERT.py
* @date    2026-07-02
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
from pyspark.sql import DataFrame
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None) -> bool:
    """
    Execute the M_S5_SOR_LOAD_EMS_HSP_TNT_INCM_DCLR_FOR_INSERT mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
    
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_S5_SOR_LOAD_EMS_HSP_TNT_INCM_DCLR_FOR_INSERT")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_S5_SOR_LOAD_EMS_HSP_TNT_INCM_DCLR_FOR_INSERT", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_oracle = lib.get_db_config(config, "oracle-defaults")
    conn_source = lib.get_db_config(config, "SSA")
    conn_target = lib.get_db_config(config, "SSA")

    
    try:
        logger.info("Step: read_SSA_EMS_HSP_TNT_INCM_DCLR")
        # Reading Data From Source - read_SSA_EMS_HSP_TNT_INCM_DCLR
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_src_1 = lib.read_sql(spark, _conn, table="SSA_EMS_HSP_TNT_INCM_DCLR")
        
        logger.info("Step: read_SSA_EMS_HSP_TNT_INCM_DCLR_STS")
        # Reading Data From Source - read_SSA_EMS_HSP_TNT_INCM_DCLR_STS
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_src_2 = lib.read_sql(spark, _conn, table="SSA_EMS_HSP_TNT_INCM_DCLR")
        
        logger.info("Step: apply_SQ_SSA_EMS_HSP_TNT_INCM_DCLR")
        # Source Qualifier: apply_SQ_SSA_EMS_HSP_TNT_INCM_DCLR
        df_sq_3 = df_src_1
        df_sq_3 = df_sq_3.filter(expr("OPR_IND = 'B' OR OPR_IND = 'A'"))
        # Select only SQ output ports (matches Informatica behavior)
        df_sq_3 = df_sq_3.select("INCM_DCLR_KEY", "INCM_DCLR_BK", "HSP_REC_KEY", "AGMT_IND", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "OPR_IND", "SOR_DATE")
        ctx.register_df("df_sq_3", df_sq_3)
        
        logger.info("Step: apply_SQ_SSA_EMS_HSP_TNT_INCM_DCLR_STS")
        # Source Qualifier: apply_SQ_SSA_EMS_HSP_TNT_INCM_DCLR_STS
        df_sq_4 = df_src_2
        df_sq_4 = df_sq_4.filter(expr("OPR_IND = 'B' OR OPR_IND = 'EB' OR OPR_IND = 'DA'"))
        # Select only SQ output ports (matches Informatica behavior)
        df_sq_4 = df_sq_4.select("INCM_DCLR_KEY", "BGN_DATE", "END_DATE", "UNIT_KEY", "HSP_RVW_YEAR", "HSP_STS_CODE", "HSP_IDF_STS_IND", "HSP_REF_PHRM_IND", "HSP_OPT_NOT_DCLR_IND", "HSP_FRST_PRN_IND", "FMLY_SIZE_NUM", "HSHLD_INCM_AMT", "HSP_RENT_FCTR_CODE", "HSP_RENT_BGN_DATE", "HSP_RENT_END_DATE", "HSP_RENT_CHNG_RSN_CODE", "HSP_RENT_CHNG_RSN_TEXT", "HSP_RMK_TEXT", "RENT_RVW_CATG_CODE", "RENT_RVW_CATG_BGN_DATE", "HSP_CASE_TYPE_CODE", "HSP_EXTRC_DATE", "TNCY_AGRMT_KEY", "LAST_REC_TXN_TYPE_CODE", "LAST_REC_TXN_DATE", "IMG_DOC_KEY", "IMG_MINS_KEY", "ORIG_HSE_SRVC_APLY_KEY", "OPR_IND", "SOR_DATE", "EXTR_RENT_DTL_FRST_PRN_IND", "EXTR_RENT_FRST_PRN_IND")
        ctx.register_df("df_sq_4", df_sq_4)
        
        logger.info("Step: write_SOR_EMS_HSP_TNT_INCM_DCLR")
        # Write to Target: write_SOR_EMS_HSP_TNT_INCM_DCLR
        df_write = df_sq_3
        # Cast columns to match target schema data types
        if "incm_dclr_bk" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "incm_dclr_bk":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "agmt_ind" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "agmt_ind":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_type_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_type_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        # Map source columns to target columns using connector field map (handles name mismatches)
        _field_map = {"AGMT_IND": "AGMT_IND", "HSP_REC_KEY": "HSP_REC_KEY", "INCM_DCLR_BK": "INCM_DCLR_BK", "INCM_DCLR_KEY": "INCM_DCLR_KEY", "LAST_REC_TXN_DATE": "LAST_REC_TXN_DATE", "LAST_REC_TXN_TYPE_CODE": "LAST_REC_TXN_TYPE_CODE"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col not in df_write.columns and _src_col in df_write.columns:
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['INCM_DCLR_KEY', 'INCM_DCLR_BK', 'HSP_REC_KEY', 'AGMT_IND', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col in df_write.columns])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "SOR_EMS_HSP_TNT_INCM_DCLR", mode="append")

        logger.info("write_SOR_EMS_HSP_TNT_INCM_DCLR write completed")
        logger.info("Step: apply_EXP_SOR_LOAD_DATE")
        # Expression: apply_EXP_SOR_LOAD_DATE
        df_exp_5 = df_sq_4
        df_exp_5 = df_exp_5.withColumn("OUT_END_DATE", expr("CASE WHEN OPR_IND = 'EB' THEN CASE WHEN LAST_REC_TXN_TYPE_CODE = NULL THEN to_date('99991231','yyyyMMdd') ELSE END_DATE END ELSE END_DATE END"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        # Select only mapping output ports (prevents column leakage)
        df_exp_5 = df_exp_5.select("OUT_END_DATE")
        ctx.register_df("df_exp_5", df_exp_5)
        
        logger.info("Step: join_target_SOR_EMS_HSP_TNT_INCM_DCLR_STS_0")
        # Lookup: join_target_SOR_EMS_HSP_TNT_INCM_DCLR_STS_0
        # Merge parallel DataFrames on their common columns
        _common_cols = [c for c in df_sq_4.columns if c in df_exp_5.columns]
        df_tgt_merge_6 = df_sq_4.join(
            df_exp_5,
            on=_common_cols,
            how="left"
        )
        ctx.register_df("df_tgt_merge_6", df_tgt_merge_6)
        
        logger.info("Step: write_SOR_EMS_HSP_TNT_INCM_DCLR_STS")
        # Write to Target: write_SOR_EMS_HSP_TNT_INCM_DCLR_STS
        df_write = df_tgt_merge_6
        # Cast columns to match target schema data types
        if "incm_dclr_bk" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "incm_dclr_bk":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "agmt_ind" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "agmt_ind":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_type_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_type_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "last_rec_txn_date" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "last_rec_txn_date":
                    df_write = df_write.withColumn(c, col(c).cast(DateType()))
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("INCM_DCLR_BK", lit(None).cast(StringType()))
        df_write = df_write.withColumn("HSP_REC_KEY", lit(None).cast(StringType()))
        df_write = df_write.withColumn("AGMT_IND", lit(None).cast(StringType()))
        # Map source columns to target columns using connector field map (handles name mismatches)
        _field_map = {"BGN_DATE": "BGN_DATE", "END_DATE": "OUT_END_DATE", "EXTR_RENT_DTL_FRST_PRN_IND": "EXTR_RENT_DTL_FRST_PRN_IND", "EXTR_RENT_FRST_PRN_IND": "EXTR_RENT_FRST_PRN_IND", "FMLY_SIZE_NUM": "FMLY_SIZE_NUM", "HSHLD_INCM_AMT": "HSHLD_INCM_AMT", "HSP_CASE_TYPE_CODE": "HSP_CASE_TYPE_CODE", "HSP_EXTRC_DATE": "HSP_EXTRC_DATE", "HSP_FRST_PRN_IND": "HSP_FRST_PRN_IND", "HSP_IDF_STS_IND": "HSP_IDF_STS_IND", "HSP_OPT_NOT_DCLR_IND": "HSP_OPT_NOT_DCLR_IND", "HSP_REF_PHRM_IND": "HSP_REF_PHRM_IND", "HSP_RENT_BGN_DATE": "HSP_RENT_BGN_DATE", "HSP_RENT_CHNG_RSN_CODE": "HSP_RENT_CHNG_RSN_CODE", "HSP_RENT_CHNG_RSN_TEXT": "HSP_RENT_CHNG_RSN_TEXT", "HSP_RENT_END_DATE": "HSP_RENT_END_DATE", "HSP_RENT_FCTR_CODE": "HSP_RENT_FCTR_CODE", "HSP_RMK_TEXT": "HSP_RMK_TEXT", "HSP_RVW_YEAR": "HSP_RVW_YEAR", "HSP_STS_CODE": "HSP_STS_CODE", "IMG_DOC_KEY": "IMG_DOC_KEY", "IMG_MINS_KEY": "IMG_MINS_KEY", "INCM_DCLR_KEY": "INCM_DCLR_KEY", "LAST_REC_TXN_DATE": "LAST_REC_TXN_DATE", "LAST_REC_TXN_TYPE_CODE": "LAST_REC_TXN_TYPE_CODE", "ORIG_HSE_SRVC_APLY_KEY": "ORIG_HSE_SRVC_APLY_KEY", "RENT_RVW_CATG_BGN_DATE": "RENT_RVW_CATG_BGN_DATE", "RENT_RVW_CATG_CODE": "RENT_RVW_CATG_CODE", "TNCY_AGRMT_KEY": "TNCY_AGRMT_KEY", "UNIT_KEY": "UNIT_KEY"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col not in df_write.columns and _src_col in df_write.columns:
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['INCM_DCLR_KEY', 'INCM_DCLR_BK', 'HSP_REC_KEY', 'AGMT_IND', 'LAST_REC_TXN_TYPE_CODE', 'LAST_REC_TXN_DATE']
        df_write = df_write.select(*[col for col in _target_cols if col in df_write.columns])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "SOR_EMS_HSP_TNT_INCM_DCLR", mode="append")

        logger.info("write_SOR_EMS_HSP_TNT_INCM_DCLR_STS write completed")
        
        metrics.complete()
        logger.info("Mapping M_S5_SOR_LOAD_EMS_HSP_TNT_INCM_DCLR_FOR_INSERT completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_S5_SOR_LOAD_EMS_HSP_TNT_INCM_DCLR_FOR_INSERT FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_S5_SOR_LOAD_EMS_HSP_TNT_INCM_DCLR_FOR_INSERT", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_S5_SOR_LOAD_EMS_HSP_TNT_INCM_DCLR_FOR_INSERT")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        return 0 if success else 1
    finally:
        spark.stop()


if __name__ == "__main__":
    main()