'''
* Script - M_S5_SOR_LOAD_EMS_RAL_RAES_AIP_FOR_INSERT.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_S5_SOR_LOAD_EMS_RAL_RAES_AIP_FOR_INSERT mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_S5_SOR_LOAD_EMS_RAL_RAES_AIP_FOR_INSERT")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_S5_SOR_LOAD_EMS_RAL_RAES_AIP_FOR_INSERT", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "SSA")

    
    try:
        logger.info("Step: read_SSA_EMS_RAL_RAES_AIP")
        # Reading Data From Source - read_SSA_EMS_RAL_RAES_AIP
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_EMS_RAL_RAES_AIP = lib.read_sql(spark, _conn, table="SSA_EMS_RAL_RAES_AIP")
        
        logger.info("Step: read_SSA_EMS_RAL_RAES_AIP_STS")
        # Reading Data From Source - read_SSA_EMS_RAL_RAES_AIP_STS
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_EMS_RAL_RAES_AIP_STS = lib.read_sql(spark, _conn, table="SSA_EMS_RAL_RAES_AIP_STS")
        
        logger.info("Step: apply_SQ_SSA_EMS_RAL_RAES_AIP")
        # Source Qualifier: apply_SQ_SSA_EMS_RAL_RAES_AIP
        df_SQ_SSA_EMS_RAL_RAES_AIP = df_SSA_EMS_RAL_RAES_AIP
        df_SQ_SSA_EMS_RAL_RAES_AIP = lib.sq_output(
            input_df=df_SQ_SSA_EMS_RAL_RAES_AIP,
            port_cols={
                'AIP_KEY': 'decimal',
                'AIP_BK': 'string',
                'RAES_APLY_KEY': 'decimal',
                'HSE_SRVC_APLY_NUM': 'string',
                'AGMT_IND': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'OPR_IND': 'string',
                'SOR_DATE': 'date/time',
            },
            filter_condition="OPR_IND = 'B' OR OPR_IND = 'A'",
        )
        ctx.register_df("df_SQ_SSA_EMS_RAL_RAES_AIP", df_SQ_SSA_EMS_RAL_RAES_AIP)
        
        logger.info("Step: apply_SQ_SSA_EMS_RAL_RAES_AIP_STS")
        # Source Qualifier: apply_SQ_SSA_EMS_RAL_RAES_AIP_STS
        df_SQ_SSA_EMS_RAL_RAES_AIP_STS = df_SSA_EMS_RAL_RAES_AIP_STS
        df_SQ_SSA_EMS_RAL_RAES_AIP_STS = lib.sq_output(
            input_df=df_SQ_SSA_EMS_RAL_RAES_AIP_STS,
            port_cols={
                'AIP_KEY': 'decimal',
                'BGN_DATE': 'date/time',
                'END_DATE': 'date/time',
                'RAES_APRV_DATE': 'date/time',
                'RAES_APRV_STS_CODE': 'string',
                'ALWN_BGN_DATE': 'date/time',
                'ALWN_END_DATE': 'date/time',
                'AIP_REF_NUM': 'string',
                'AIP_ISS_DATE': 'date/time',
                'AIP_END_DATE': 'date/time',
                'TA_CMNC_DATE': 'date/time',
                'TA_TRMT_DATE': 'date/time',
                'LES_APRV_DATE': 'date/time',
                'PYMT_APRV_DATE': 'date/time',
                'PRH_OPT_DATE': 'date/time',
                'RMDR_LTR_BU_DATE': 'date/time',
                'RNW_BU_DATE': 'date/time',
                'SHR_NUM': 'decimal',
                'TOT_RENT_AMT': 'decimal',
                'HA_ALWN_AMT': 'decimal',
                'SPCL_GRNT_IND': 'string',
                'SPCL_GRNT_ALWN_AMT': 'decimal',
                'CSSA_IND': 'string',
                'CSSA_REF_NUM': 'string',
                'CSSA_RNTL_SPLM_AMT': 'decimal',
                'TA_AGNT_FEE_AMT': 'decimal',
                'TA_DPST_AMT': 'decimal',
                'TA_STMP_DUTY_AMT': 'decimal',
                'BANK_BRCH_CODE': 'string',
                'BANK_CODE': 'string',
                'BANK_ACCT_NUM': 'string',
                'PYMT_MTHD_TYPE_CODE': 'string',
                'RAES_APRV_HOME_FLAT_NUM': 'string',
                'RAES_APRV_HOME_FLR_NUM': 'string',
                'RAES_APRV_HOME_BLK_NUM': 'string',
                'RAES_APRV_HOME_BLDG_NAME': 'string',
                'RAES_APRV_HOME_STRT_NAME': 'string',
                'RAES_APRV_HOME_DSTR_CODE': 'string',
                'RAES_APRV_HOME_DSTR_NAME': 'string',
                'RAES_APRV_HOME_CODE_ADDR': 'string',
                'RAES_APRV_HOME_PHONE_NUM': 'string',
                'RAES_APRV_PRH_BU_DATE': 'date/time',
                'RAES_APRV_EAS_IND': 'string',
                'RAES_APRV_EAS_ALWN_AMT': 'decimal',
                'RAES_APRV_APLY_RENT_PYMT_AMT': 'decimal',
                'RAES_APRV_ACCT_HLDR_NAME_1': 'string',
                'RAES_APRV_ACCT_HLDR_NAME_2': 'string',
                'RAES_APRV_ACCT_HLDR_NAME_3': 'string',
                'RAES_APRV_ACCT_HLDR_NAME_4': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'OPR_IND': 'string',
                'SOR_DATE': 'date/time',
            },
            filter_condition="OPR_IND = 'B' OR OPR_IND = 'EB' OR OPR_IND = 'DA'",
        )
        ctx.register_df("df_SQ_SSA_EMS_RAL_RAES_AIP_STS", df_SQ_SSA_EMS_RAL_RAES_AIP_STS)
        
        logger.info("Step: write_SOR_EMS_RAL_RAES_AIP")
        # Write to Target: write_SOR_EMS_RAL_RAES_AIP
        lib.write_target(
            spark=spark,
            df=df_SQ_SSA_EMS_RAL_RAES_AIP,
            conn=conn_target,
            table='SOR_EMS_RAL_RAES_AIP',
            mode='append',
            source_columns=[
                'AIP_KEY',
                'AIP_BK',
                'RAES_APLY_KEY',
                'HSE_SRVC_APLY_NUM',
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            target_columns=[
                'AIP_KEY',
                'AIP_BK',
                'RAES_APLY_KEY',
                'HSE_SRVC_APLY_NUM',
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            config=config,
        )

        logger.info("write_SOR_EMS_RAL_RAES_AIP write completed")
        logger.info("Step: apply_EXP_SOR_LOAD_DATE")
        # Expression: apply_EXP_SOR_LOAD_DATE
        df_EXP_SOR_LOAD_DATE = lib.expression(
            input_df=df_SQ_SSA_EMS_RAL_RAES_AIP_STS,
            computed_columns=[
                {'name': 'OUT_END_DATE', 'expr': "CASE WHEN OPR_IND = 'EB' THEN CASE WHEN LAST_REC_TXN_TYPE_CODE IS NULL THEN to_date('99991231','yyyyMMdd') ELSE END_DATE END ELSE END_DATE END"}
            ],
        )
        ctx.register_df("df_EXP_SOR_LOAD_DATE", df_EXP_SOR_LOAD_DATE)
        
        logger.info("Step: write_SOR_EMS_RAL_RAES_AIP_STS")
        # Write to Target: write_SOR_EMS_RAL_RAES_AIP_STS
        lib.write_target(
            spark=spark,
            df=df_EXP_SOR_LOAD_DATE,
            conn=conn_target,
            table='SOR_EMS_RAL_RAES_AIP_STS',
            mode='append',
            source_columns=[
                'AIP_KEY',
                'BGN_DATE',
                'OUT_END_DATE',
                'RAES_APRV_DATE',
                'RAES_APRV_STS_CODE',
                'ALWN_BGN_DATE',
                'ALWN_END_DATE',
                'AIP_REF_NUM',
                'AIP_ISS_DATE',
                'AIP_END_DATE',
                'TA_CMNC_DATE',
                'TA_TRMT_DATE',
                'LES_APRV_DATE',
                'PYMT_APRV_DATE',
                'PRH_OPT_DATE',
                'RMDR_LTR_BU_DATE',
                'RNW_BU_DATE',
                'SHR_NUM',
                'TOT_RENT_AMT',
                'HA_ALWN_AMT',
                'SPCL_GRNT_IND',
                'SPCL_GRNT_ALWN_AMT',
                'CSSA_IND',
                'CSSA_REF_NUM',
                'CSSA_RNTL_SPLM_AMT',
                'TA_AGNT_FEE_AMT',
                'TA_DPST_AMT',
                'TA_STMP_DUTY_AMT',
                'BANK_BRCH_CODE',
                'BANK_CODE',
                'BANK_ACCT_NUM',
                'PYMT_MTHD_TYPE_CODE',
                'RAES_APRV_HOME_FLAT_NUM',
                'RAES_APRV_HOME_FLR_NUM',
                'RAES_APRV_HOME_BLK_NUM',
                'RAES_APRV_HOME_BLDG_NAME',
                'RAES_APRV_HOME_STRT_NAME',
                'RAES_APRV_HOME_DSTR_CODE',
                'RAES_APRV_HOME_DSTR_NAME',
                'RAES_APRV_HOME_CODE_ADDR',
                'RAES_APRV_HOME_PHONE_NUM',
                'RAES_APRV_PRH_BU_DATE',
                'RAES_APRV_EAS_IND',
                'RAES_APRV_EAS_ALWN_AMT',
                'RAES_APRV_APLY_RENT_PYMT_AMT',
                'RAES_APRV_ACCT_HLDR_NAME_1',
                'RAES_APRV_ACCT_HLDR_NAME_2',
                'RAES_APRV_ACCT_HLDR_NAME_3',
                'RAES_APRV_ACCT_HLDR_NAME_4',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            target_columns=[
                'AIP_KEY',
                'BGN_DATE',
                'END_DATE',
                'RAES_APRV_DATE',
                'RAES_APRV_STS_CODE',
                'ALWN_BGN_DATE',
                'ALWN_END_DATE',
                'AIP_REF_NUM',
                'AIP_ISS_DATE',
                'AIP_END_DATE',
                'TA_CMNC_DATE',
                'TA_TRMT_DATE',
                'LES_APRV_DATE',
                'PYMT_APRV_DATE',
                'PRH_OPT_DATE',
                'RMDR_LTR_BU_DATE',
                'RNW_BU_DATE',
                'SHR_NUM',
                'TOT_RENT_AMT',
                'HA_ALWN_AMT',
                'SPCL_GRNT_IND',
                'SPCL_GRNT_ALWN_AMT',
                'CSSA_IND',
                'CSSA_REF_NUM',
                'CSSA_RNTL_SPLM_AMT',
                'TA_AGNT_FEE_AMT',
                'TA_DPST_AMT',
                'TA_STMP_DUTY_AMT',
                'BANK_BRCH_CODE',
                'BANK_CODE',
                'BANK_ACCT_NUM',
                'PYMT_MTHD_TYPE_CODE',
                'RAES_APRV_HOME_FLAT_NUM',
                'RAES_APRV_HOME_FLR_NUM',
                'RAES_APRV_HOME_BLK_NUM',
                'RAES_APRV_HOME_BLDG_NAME',
                'RAES_APRV_HOME_STRT_NAME',
                'RAES_APRV_HOME_DSTR_CODE',
                'RAES_APRV_HOME_DSTR_NAME',
                'RAES_APRV_HOME_CODE_ADDR',
                'RAES_APRV_HOME_PHONE_NUM',
                'RAES_APRV_PRH_BU_DATE',
                'RAES_APRV_EAS_IND',
                'RAES_APRV_EAS_ALWN_AMT',
                'RAES_APRV_APLY_RENT_PYMT_AMT',
                'RAES_APRV_ACCT_HLDR_NAME_1',
                'RAES_APRV_ACCT_HLDR_NAME_2',
                'RAES_APRV_ACCT_HLDR_NAME_3',
                'RAES_APRV_ACCT_HLDR_NAME_4',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            config=config,
        )

        logger.info("write_SOR_EMS_RAL_RAES_AIP_STS write completed")
        
        metrics.complete()
        logger.info("Mapping M_S5_SOR_LOAD_EMS_RAL_RAES_AIP_FOR_INSERT completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_S5_SOR_LOAD_EMS_RAL_RAES_AIP_FOR_INSERT FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_S5_SOR_LOAD_EMS_RAL_RAES_AIP_FOR_INSERT", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_S5_SOR_LOAD_EMS_RAL_RAES_AIP_FOR_INSERT")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())