'''
* Script - M_SOR_LOAD_NHS_APLY_VET_RSLT_INS.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None,
                session_sqls=None) -> bool:
    """
    Execute the M_SOR_LOAD_NHS_APLY_VET_RSLT_INS mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
        session_sqls: The session's Target Pre/Post SQL dict 
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_SOR_LOAD_NHS_APLY_VET_RSLT_INS")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_SOR_LOAD_NHS_APLY_VET_RSLT_INS", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_target = lib.get_db_config(config, "SSA")

    
    try:
        logger.info("Step: read_SSA_NHS_APLY_VET_RSLT_STS")
        # Reading Data From Source - read_SSA_NHS_APLY_VET_RSLT_STS
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_NHS_APLY_VET_RSLT_STS = lib.read_sql(spark, _conn, table="SSA_NHS_APLY_VET_RSLT_STS")
        
        logger.info("Step: read_SSA_NHS_APLY_VET_RSLT")
        # Reading Data From Source - read_SSA_NHS_APLY_VET_RSLT
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "SSA")
        df_SSA_NHS_APLY_VET_RSLT = lib.read_sql(spark, _conn, table="SSA_NHS_APLY_VET_RSLT")
        
        logger.info("Step: apply_SQ_SSA_NHS_APLY_VET_RSLT_STS")
        # Source Qualifier: apply_SQ_SSA_NHS_APLY_VET_RSLT_STS
        df_SQ_SSA_NHS_APLY_VET_RSLT_STS = df_SSA_NHS_APLY_VET_RSLT_STS
        df_SQ_SSA_NHS_APLY_VET_RSLT_STS = lib.sq_output(
            input_df=df_SQ_SSA_NHS_APLY_VET_RSLT_STS,
            port_cols={
                'APLY_VET_RSLT_KEY': 'decimal',
                'BGN_DATE': 'date/time',
                'END_DATE': 'date/time',
                'DUP_CHK_RSLT_CODE': 'string',
                'ELGBL_CHK_RSLT_CODE': 'string',
                'RLTN_CHK_RSLT_CODE': 'string',
                'ITGRTY_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_A_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_G_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_J_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_K_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_L_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_N_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_S_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_T_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_U_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_W_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_Y_DUP_CHK_RSLT_CODE': 'string',
                'HSE_BNFT_Z_DUP_CHK_RSLT_CODE': 'string',
                'APLY_VET_OVRL_RSLT_CODE': 'string',
                'APLY_VET_OVRD_RSLT_CODE': 'string',
                'HO_RCMD_RSN_TEXT': 'string',
                'HO_RCMD_OTHR_RSN_TEXT': 'string',
                'HO_RMK_TEXT': 'string',
                'DUP_SBMT_CHK_IND': 'string',
                'RPRIOR_RQR_IND': 'string',
                'APLY_VET_STS_CODE': 'string',
                'DUP_SBMT_CHK_RSLT_CODE': 'string',
                'EFAS_CHK_RSLT_CODE': 'string',
                'APLY_VET_SCRN_ID': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'OPR_IND': 'string',
                'SOR_DATE': 'date/time',
            },
            filter_condition="OPR_IND = 'B' OR OPR_IND = 'EB' OR OPR_IND = 'DA'",
        )
        ctx.register_df("df_SQ_SSA_NHS_APLY_VET_RSLT_STS", df_SQ_SSA_NHS_APLY_VET_RSLT_STS)
        
        logger.info("Step: apply_SQ_SSA_NHS_APLY_VET_RSLT")
        # Source Qualifier: apply_SQ_SSA_NHS_APLY_VET_RSLT
        df_SQ_SSA_NHS_APLY_VET_RSLT = df_SSA_NHS_APLY_VET_RSLT
        df_SQ_SSA_NHS_APLY_VET_RSLT = lib.sq_output(
            input_df=df_SQ_SSA_NHS_APLY_VET_RSLT,
            port_cols={
                'APLY_VET_RSLT_KEY': 'decimal',
                'HOS_APLY_KEY': 'decimal',
                'NHS_APLY_VET_SEQ_NUM': 'decimal',
                'NHS_APLY_VET_STG_CODE': 'string',
                'AGMT_IND': 'string',
                'LAST_REC_TXN_TYPE_CODE': 'string',
                'LAST_REC_TXN_DATE': 'date/time',
                'OPR_IND': 'string',
                'SOR_DATE': 'date/time',
            },
            filter_condition="OPR_IND = 'B' OR OPR_IND = 'A'",
        )
        ctx.register_df("df_SQ_SSA_NHS_APLY_VET_RSLT", df_SQ_SSA_NHS_APLY_VET_RSLT)
        
        logger.info("Step: apply_EXP_SOR_LOAD_DATE")
        # Expression: apply_EXP_SOR_LOAD_DATE
        df_EXP_SOR_LOAD_DATE = lib.expression(
            input_df=df_SQ_SSA_NHS_APLY_VET_RSLT_STS,
            computed_columns=[
                {'name': 'OUT_END_DATE', 'expr': "CASE WHEN OPR_IND = 'EB' THEN CASE WHEN LAST_REC_TXN_TYPE_CODE IS NULL THEN to_date('99991231','yyyyMMdd') ELSE END_DATE END ELSE END_DATE END"}
            ],
        )
        ctx.register_df("df_EXP_SOR_LOAD_DATE", df_EXP_SOR_LOAD_DATE)
        
        logger.info("Step: write_SOR_NHS_APLY_VET_RSLT")
        # Write to Target: write_SOR_NHS_APLY_VET_RSLT
        lib.write_target(
            spark=spark,
            df=df_SQ_SSA_NHS_APLY_VET_RSLT,
            conn=conn_target,
            table='SOR_NHS_APLY_VET_RSLT',
            mode='append',
            source_columns=[
                'APLY_VET_RSLT_KEY',
                'HOS_APLY_KEY',
                'NHS_APLY_VET_SEQ_NUM',
                'NHS_APLY_VET_STG_CODE',
                'AGMT_IND',
                None,
                'LAST_REC_TXN_DATE',
            ],
            target_columns=[
                'APLY_VET_RSLT_KEY',
                'HOS_APLY_KEY',
                'NHS_APLY_VET_SEQ_NUM',
                'NHS_APLY_VET_STG_CODE',
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            config=config,
        )

        logger.info("write_SOR_NHS_APLY_VET_RSLT write completed")
        logger.info("Step: write_SOR_NHS_APLY_VET_RSLT_STS")
        # Write to Target: write_SOR_NHS_APLY_VET_RSLT_STS
        lib.write_target(
            spark=spark,
            df=df_EXP_SOR_LOAD_DATE,
            conn=conn_target,
            table='SOR_NHS_APLY_VET_RSLT',
            mode='append',
            source_columns=[
                'APLY_VET_RSLT_KEY',
                None,
                None,
                None,
                None,
                None,
                'LAST_REC_TXN_DATE',
            ],
            target_columns=[
                'APLY_VET_RSLT_KEY',
                'HOS_APLY_KEY',
                'NHS_APLY_VET_SEQ_NUM',
                'NHS_APLY_VET_STG_CODE',
                'AGMT_IND',
                'LAST_REC_TXN_TYPE_CODE',
                'LAST_REC_TXN_DATE',
            ],
            config=config,
        )

        logger.info("write_SOR_NHS_APLY_VET_RSLT_STS write completed")
        
        metrics.complete()
        logger.info("Mapping M_SOR_LOAD_NHS_APLY_VET_RSLT_INS completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_SOR_LOAD_NHS_APLY_VET_RSLT_INS FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_SOR_LOAD_NHS_APLY_VET_RSLT_INS", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_SOR_LOAD_NHS_APLY_VET_RSLT_INS")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())