"""
Workflow Orchestration: WF_GMS_DDS_APLY_DLY
Auto-generated by ASL Informatica XML to PySpark Converter
"""
import os, sys
import env.runtime_lib as lib

lib.init_logger("wf_gms_dds_aply_dly")
logger = lib.get_logger("wf_gms_dds_aply_dly")

# Auto-discover mapping modules
MAPPING_FUNCTIONS = lib.discover_mappings()


# =============================================================================
# WORKFLOW EXECUTION PLAN  (DAG – topological order with parallel branches)
# =============================================================================

EXECUTION_PLAN = [
  {
    "type": "parallel_group",
    "steps": [
      {
        "type": "session",
        "name": "S_GMS_ETL_DPA_TRUNCATE",
        "mapping_name": "M_UTL_DPA_TRUNCATE"
      },
      {
        "type": "session",
        "name": "S_GMS_ETL_PARAM_SETUP",
        "mapping_name": "M_UTL_PARAM_SETUP"
      }
    ]
  },
  {
    "type": "worklet",
    "name": "WL_GMS_DDS_SUM",
    "plan": [
      {
        "type": "parallel_group",
        "steps": [
          {
            "type": "session",
            "name": "S_DPA_SUM_FACT_GMS_DLY_MSD_SMRY",
            "mapping_name": "M_DPA_SUM_FACT_GMS_DLY_MSD_SMRY"
          },
          {
            "type": "session",
            "name": "S_DPA_SUM_FACT_GMS_DLY_DOG_RGSTR",
            "mapping_name": "M_DPA_SUM_FACT_GMS_DLY_DOG_RGSTR"
          },
          {
            "type": "session",
            "name": "S_DPA_SUM_FACT_GMS_DLY_MSD_INCDT",
            "mapping_name": "M_DPA_SUM_FACT_GMS_DLY_MSD_INCDT"
          }
        ]
      }
    ]
  },
  {
    "type": "worklet",
    "name": "WL_GMS_DDS_APLY",
    "plan": [
      {
        "type": "parallel_group",
        "steps": [
          {
            "type": "session",
            "name": "S_DDS_APL_FACT_GMS_DLY_DOG_RGSTR",
            "mapping_name": "M_DDS_APL_FACT_GMS_DLY_DOG_RGSTR"
          },
          {
            "type": "session",
            "name": "S_DDS_APL_FACT_GMS_DLY_MSD_SMRY",
            "mapping_name": "M_DDS_APL_FACT_GMS_DLY_MSD_SMRY"
          },
          {
            "type": "session",
            "name": "S_DDS_APL_FACT_GMS_DLY_MSD_INCDT",
            "mapping_name": "M_DDS_APL_FACT_GMS_DLY_MSD_INCDT"
          }
        ]
      }
    ]
  },
  {
    "type": "task",
    "name": "T_MAIL_SUCCESS"
  }
]

TASK_INFO = {
  "T_MAIL_FAIL": {
    "type": "email",
    "subject": "CIS - Session Fail: %s",
    "text": "The caption session failed to complete\r\n\r\nFolder Name: %n\r\nSession Name: %s\r\nSession Status: %e\r\n%b\r\n%c\r\n%i\r\n\r\nAttached please find the error log for your investigation.\r\n\r\n%g",
    "user": "xxx@test.aaa"
  },
  "T_MAIL_SUCCESS": {
    "type": "email",
    "subject": "CIS - Workflow Success: WF_GMS_DDS_APLY_DLY",
    "text": "The captioned workflow completed sucessfully.",
    "user": "xxx@test.aaa"
  }
}


def run_workflow(config=None, fail_fast=True):
    """Execute the workflow via the shared runtime library runner."""
    if config is None:
        config = lib.load_config("env/config.yml")
    return lib.run_workflow(
        execution_plan=EXECUTION_PLAN,
        mapping_functions=MAPPING_FUNCTIONS,
        workflow_name="WF_GMS_DDS_APLY_DLY",
        task_info=TASK_INFO,
        config=config,
        fail_fast=fail_fast,
        metrics_cls=lib.MappingMetrics,
    )


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", "-c", default="env/config.yml")
    parser.add_argument("--continue-on-error", action="store_true")
    args = parser.parse_args()
    config = lib.load_config(args.config)
    result = run_workflow(config=config, fail_fast=not args.continue_on_error)
    return 0 if result["status"] == "SUCCESS" else 1


if __name__ == "__main__":
    main()