'''
* Script - M_DDS_APLY_DMNS_DSTR.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
from pyspark.sql import DataFrame
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None) -> bool:
    """
    Execute the M_DDS_APLY_DMNS_DSTR mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
    
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_DDS_APLY_DMNS_DSTR")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_DDS_APLY_DMNS_DSTR", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_oracle = lib.get_db_config(config, "oracle-defaults")
    conn_source = lib.get_db_config(config, "DPA")
    conn_target = lib.get_db_config(config, "DPA")

    
    try:
        logger.info("Step: read_DPA_DMNS_DSTR")
        # Reading Data From Source - read_DPA_DMNS_DSTR
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        df_DPA_DMNS_DSTR = lib.read_sql(spark, _conn, table="DPA_DMNS_DSTR")
        
        logger.info("Step: apply_SQ_DPA_DMNS_DSTR")
        # Source Qualifier: apply_SQ_DPA_DMNS_DSTR
        df_SQ_DPA_DMNS_DSTR = df_DPA_DMNS_DSTR
        # Select only SQ output ports (matches Informatica behavior)
        df_SQ_DPA_DMNS_DSTR = df_SQ_DPA_DMNS_DSTR.select("DMNS_DSTR_KEY", "RGN_CODE", "RGN_NAME", "DSTR_CODE", "DSTR_NAME", "RGN_DISP_SEQ_NUM", "DSTR_DISP_SEQ_NUM")
        ctx.register_df("df_SQ_DPA_DMNS_DSTR", df_SQ_DPA_DMNS_DSTR)
        
        logger.info("Step: write_DDS_DMNS_DSTR")
        # Write to Target: write_DDS_DMNS_DSTR
        df_write = df_SQ_DPA_DMNS_DSTR
        # Cast columns to match target schema data types
        if "rgn_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "rgn_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "rgn_name" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "rgn_name":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "dstr_code" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "dstr_code":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        if "dstr_name" in [c.lower() for c in df_write.columns]:
            for c in df_write.columns:
                if c.lower() == "dstr_name":
                    df_write = df_write.withColumn(c,
                        when(col(c).cast(DecimalType(38,0)).isNotNull(),
                             col(c).cast(DecimalType(38,0)).cast(StringType()))
                        .otherwise(col(c).cast(StringType())))
        # Map source columns to target columns using connector field map (handles name mismatches)
        _field_map = {"DMNS_DSTR_KEY": "DMNS_DSTR_KEY", "DSTR_CODE": "DSTR_CODE", "DSTR_DISP_SEQ_NUM": "DSTR_DISP_SEQ_NUM", "DSTR_NAME": "DSTR_NAME", "RGN_CODE": "RGN_CODE", "RGN_DISP_SEQ_NUM": "RGN_DISP_SEQ_NUM", "RGN_NAME": "RGN_NAME"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col not in df_write.columns and _src_col in df_write.columns:
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['DMNS_DSTR_KEY', 'RGN_CODE', 'RGN_NAME', 'DSTR_CODE', 'DSTR_NAME', 'RGN_DISP_SEQ_NUM', 'DSTR_DISP_SEQ_NUM']
        df_write = df_write.select(*[col for col in _target_cols if col in df_write.columns])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "DDS_DMNS_DSTR", mode="append")

        logger.info("write_DDS_DMNS_DSTR write completed")
        
        metrics.complete()
        logger.info("Mapping M_DDS_APLY_DMNS_DSTR completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_DDS_APLY_DMNS_DSTR FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_DDS_APLY_DMNS_DSTR", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_DDS_APLY_DMNS_DSTR")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        return 0 if success else 1
    finally:
        spark.stop()


if __name__ == "__main__":
    main()