'''
* Script - M_DPA_SUMMARIZE_DMNS_CNTR_STG.py
* @author Auto-generated by ASL Informatica XML to PySpark Converter
* @version 1.0
* @par Remarks
*   This code is auto-generated. Please review the business rules before productionizing.
'''

import env.runtime_lib as lib
# Save builtins before pyspark.sql.functions shadows max/min with column versions
_builtin_max = max
_builtin_min = min
from pyspark.sql.functions import *
from pyspark.sql.types import *

# =============================================================================
# MAPPING LOGIC
# =============================================================================

def run_mapping(ctx: lib.SparkContext = None, metrics=None, job_params=None) -> bool:
    """
    Execute the M_DPA_SUMMARIZE_DMNS_CNTR_STG mapping transformations.

    All initialization (logging, config, spark session, connections) happens
    lazily inside this function, so importing the module has no side effects.
    
    Args:
        ctx: Optional SparkContext for session and DataFrame registry
        metrics: Optional metrics tracker (or NullMetrics if not provided)
        job_params: Optional dict of job parameters loaded by workflow
    
    Returns:
        bool: True if successful
    """
    lib.init_logger()
    logger = lib.get_logger()
    logger.propagate = False  # mapping detail stays in mapping log only
    logger.info("Start to run mapping M_DPA_SUMMARIZE_DMNS_CNTR_STG")

    config = lib.load_config('env/config.yml')
    objects = config.get('objects', {})

    spark = ctx.spark if ctx else lib.get_spark_session("M_DPA_SUMMARIZE_DMNS_CNTR_STG", config)
    metrics = metrics or lib.NullMetrics()
    metrics.start()

    conn_oracle = lib.get_db_config(config, "oracle-defaults")
    conn_source = lib.get_db_config(config, "SOR")
    conn_target = lib.get_db_config(config, "DPA")

    v_snsh_date = ""
    # Load mapping variables from job_params or UTL_JOB_PARAM file
    try:
        _param_obj = objects.get("UTL_JOB_PARAM", {})
        if isinstance(_param_obj, dict):
            _param_path = lib._resolve_path(_param_obj.get('path'))
        with open(_param_path, "r") as _f:
            for _line in _f:
                _line = _line.strip()
                for _var in [ "$$v_snsh_date", ]:
                    if _line.startswith(_var + "="):
                        _val = _line.split("=", 1)[1]
                        _clean = _var.replace("$", "")
                        if _clean == "v_snsh_date":
                            v_snsh_date = _val
                        logger.info("Loaded %s=%s from %s", _var, _val, _param_path)
    except Exception:
        logger.warning("UTL_JOB_PARAM not found, using default values")
    
    try:
        logger.info("Step: apply_SEQ_DMNS_CNTR_STG_KEY")
        # Sequence Generator: apply_SEQ_DMNS_CNTR_STG_KEY
        df_SEQ_DMNS_CNTR_STG_KEY = df_input.withColumn(
            "NEXTVAL", 
            monotonically_increasing_id() + 0
        )
        ctx.register_df("df_SEQ_DMNS_CNTR_STG_KEY", df_SEQ_DMNS_CNTR_STG_KEY)

        logger.info("Step: apply_SQ_SOR_HOM_CON_CNTR_STG")
        # Source Qualifier: apply_SQ_SOR_HOM_CON_CNTR_STG
        # SQL Pushdown - executes Informatica SQ SQL on source database
        _conn = lib.get_db_config(config, "SOR")
        # Parameterize schema from connection config
        _schema = _conn.get("schema", "") or "psor"
        query = f"""SELECT SOR_HOM_CON_CNTR_STG.CNTR_STG_CODE, SOR_HOM_CON_CNTR_STG_STS.CNTR_STG_DESP 
FROM
 SOR_HOM_CON_CNTR_STG, SOR_HOM_CON_CNTR_STG_STS 
WHERE
 SOR_HOM_CON_CNTR_STG.CNTR_STG_KEY=SOR_HOM_CON_CNTR_STG_STS.CNTR_STG_KEY AND
 SOR_HOM_CON_CNTR_STG.LAST_REC_TXN_TYPE_CODE IS NULL AND
  SOR_HOM_CON_CNTR_STG_STS.LAST_REC_TXN_TYPE_CODE IS NULL AND
  TO_DATE ('$$v_snsh_date', 'YYYYMMDD') BETWEEN SOR_HOM_CON_CNTR_STG_STS.bgn_date AND SOR_HOM_CON_CNTR_STG_STS.end_date
ORDER BY SOR_HOM_CON_CNTR_STG.CNTR_STG_CODE"""
        query = query.replace("$$v_snsh_date", v_snsh_date)
        df_SQ_SOR_HOM_CON_CNTR_STG = lib.read_sql(spark, _conn, query=query)
        # Rename SQL result columns to SQ output ports 
        # name match first, then positional fallback (handles unaliased expressions)
        _sql_cols = df_SQ_SOR_HOM_CON_CNTR_STG.columns
        _port_cols = ["CNTR_STG_CODE", "CNTR_STG_DESP"]
        _rename_map = {}
        _used_ports = set()
        # 1) Name-based match first (case-insensitive)
        for _sc in _sql_cols:
            for _pi, _port in enumerate(_port_cols):
                if _pi not in _used_ports and _sc.lower() == _port.lower():
                    _rename_map[_sc] = _port
                    _used_ports.add(_pi)
                    break
        # 2) Positional fallback for remaining SQL columns (unaliased expressions)
        _pi = 0
        for _sc in _sql_cols:
            if _sc in _rename_map:
                continue
            while _pi in _used_ports:
                _pi += 1
            if _pi < len(_port_cols):
                _rename_map[_sc] = _port_cols[_pi]
                _used_ports.add(_pi)
                _pi += 1
        df_SQ_SOR_HOM_CON_CNTR_STG = df_SQ_SOR_HOM_CON_CNTR_STG.select(*[col(f"`{old}`").alias(new) for old, new in _rename_map.items()])
        # Select only SQ output ports (matches Informatica behavior)
        # ports the SQL didn't return become lit(None) so downstream references never fail
        df_SQ_SOR_HOM_CON_CNTR_STG = df_SQ_SOR_HOM_CON_CNTR_STG.select([col(c) if c in df_SQ_SOR_HOM_CON_CNTR_STG.columns else lit(None).alias(c) for c in _port_cols])
        
        ctx.register_df("df_SQ_SOR_HOM_CON_CNTR_STG", df_SQ_SOR_HOM_CON_CNTR_STG)
        
        logger.info("Step: read_LKP_DDS_DMNS_CNTR_STG")
        # Reading Data From Source - read_LKP_DDS_DMNS_CNTR_STG
        # Resolve connection by alias (supports lookup/source connections dynamically)
        _conn = lib.get_db_config(config, "DPA")
        df_LKP_DDS_DMNS_CNTR_STG = lib.read_sql(spark, _conn, table="DDS_DMNS_CNTR_STG")
        
        logger.info("Step: apply_LKP_DDS_DMNS_CNTR_STG")
        # Lookup: apply_LKP_DDS_DMNS_CNTR_STG
        # Use First Value / Use Any Value: dedup by join keys
        df_LKP_DDS_DMNS_CNTR_STG = df_LKP_DDS_DMNS_CNTR_STG.dropDuplicates(subset=["CNTR_STG_CODE"])
        # Rename upstream columns to match lookup input port names before join
        _lkp_input = df_SQ_SOR_HOM_CON_CNTR_STG
        _lkp_input = _lkp_input.withColumn("IN_CNTR_STG_CODE", col("CNTR_STG_CODE"))
        # Join condition: IN_CNTR_STG_CODE=CNTR_STG_CODE
        # Alias-based join: _main.<source_col> == _lkp.<lookup_col>
        df_lkp_merge_1 = _lkp_input.alias("_main").join(
            broadcast(df_LKP_DDS_DMNS_CNTR_STG).alias("_lkp"),
            (col("_main.IN_CNTR_STG_CODE") == col("_lkp.CNTR_STG_CODE")),
            "left"
        ).select(
            *[_lkp_input[c] for c in _lkp_input.columns],
            *[df_LKP_DDS_DMNS_CNTR_STG[c] for c in df_LKP_DDS_DMNS_CNTR_STG.columns if c not in _lkp_input.columns]
        )
        ctx.register_df("df_lkp_merge_1", df_lkp_merge_1)        
        logger.info("Step: apply_EXPTRANS")
        # Expression: apply_EXPTRANS
        df_EXPTRANS = df_lkp_merge_1
        df_EXPTRANS = df_EXPTRANS.withColumn("IN_CNTR_STG_DESP", expr("CNTR_STG_DESP"))
        df_EXPTRANS = df_EXPTRANS.withColumn("CHANGE_FLAG", expr("CASE WHEN (DMNS_CNTR_STG_KEY IS NULL) OR CASE WHEN CNTR_STG_DESP = CNTR_STG_DESP THEN false ELSE true END THEN 1 ELSE 0 END"))
        # Ensure any missing pass-through columns exist (no connector feeding them)
        for _col in ["CNTR_STG_DESP", "DMNS_CNTR_STG_KEY", "CNTR_STG_CODE", "CNTR_STG_DISP_SEQ_NUM", "IN_CNTR_STG_CODE"]:
            if _col not in df_EXPTRANS.columns:
                df_EXPTRANS = df_EXPTRANS.withColumn(_col, lit(None))
        # Keep all upstream columns + computed columns (no select filtering)
        ctx.register_df("df_EXPTRANS", df_EXPTRANS)
        
        logger.info("Step: apply_FIL_CHANGE")
        # Filter: apply_FIL_CHANGE
        __fil_input = df_EXPTRANS
        df_FIL_CHANGE = __fil_input.filter(expr("CHANGE_FLAG = 1 AND ( NOT (DMNS_CNTR_STG_KEY IS NULL))"))
        ctx.register_df("df_FIL_CHANGE", df_FIL_CHANGE)
        
        logger.info("Step: apply_FIL_NEW")
        # Filter: apply_FIL_NEW
        __fil_input = df_EXPTRANS
        df_FIL_NEW = __fil_input.filter(expr("CHANGE_FLAG = 1 AND (DMNS_CNTR_STG_KEY IS NULL)"))
        ctx.register_df("df_FIL_NEW", df_FIL_NEW)
        
        logger.info("Step: apply_Union_Transformation")
        # Union: apply_Union_Transformation
        # Select + rename upstream columns per input, then union
        df_Union_Transformation_change = df_FIL_CHANGE.select(
            col("DMNS_CNTR_STG_KEY").alias("DMNS_CNTR_STG_KEY"),
            col("IN_CNTR_STG_CODE").alias("IN_CNTR_STG_CODE"),
            col("IN_CNTR_STG_DESP").alias("IN_CNTR_STG_DESP")        )
        df_Union_Transformation_new = df_FIL_NEW.select(
            col("NEXTVAL").alias("DMNS_CNTR_STG_KEY"),
            col("IN_CNTR_STG_CODE").alias("IN_CNTR_STG_CODE"),
            col("IN_CNTR_STG_DESP").alias("IN_CNTR_STG_DESP")        )
        df_Union_Transformation = df_Union_Transformation_change
        df_Union_Transformation = df_Union_Transformation.unionByName(df_Union_Transformation_new, allowMissingColumns=True)
        # Select only union output columns (add lit(None) for any missing)
        for _col in ["DMNS_CNTR_STG_KEY", "IN_CNTR_STG_CODE", "IN_CNTR_STG_DESP"]:
            if _col not in df_Union_Transformation.columns:
                df_Union_Transformation = df_Union_Transformation.withColumn(_col, lit(None))
        df_Union_Transformation = df_Union_Transformation.select("DMNS_CNTR_STG_KEY", "IN_CNTR_STG_CODE", "IN_CNTR_STG_DESP")
        ctx.register_df("df_Union_Transformation", df_Union_Transformation)
        
        logger.info("Step: write_DPA_DMNS_CNTR_STG")
        # Write to Target: write_DPA_DMNS_CNTR_STG
        df_write = df_Union_Transformation
        # Map source columns to target columns using connector field map (handles name
        # mismatches) — done BEFORE the _update_flag split so UPDATE/DELETE use target
        # column names in batch_update/batch_delete.
        _field_map = {"CNTR_STG_CODE": "IN_CNTR_STG_CODE", "CNTR_STG_DESP": "IN_CNTR_STG_DESP", "DMNS_CNTR_STG_KEY": "DMNS_CNTR_STG_KEY"}
        for _tgt_col, _src_col in _field_map.items():
            if _tgt_col not in df_write.columns and _src_col in df_write.columns:
                # Drop any column that would conflict case-insensitively with
                # the target name (e.g. vcnt_ind vs VCNT_IND after rename)
                for _c in list(df_write.columns):
                    if _c.lower() == _tgt_col.lower() and _c != _src_col:
                        df_write = df_write.drop(_c)
                df_write = df_write.withColumnRenamed(_src_col, _tgt_col)
        # Add NULL for unmapped target columns (schema parity) - excluding identity columns
        df_write = df_write.withColumn("CNTR_STG_DISP_SEQ_NUM", lit(None).cast(StringType()))
        # Select only target-defined columns (field_map already handled name alignment)
        _target_cols = ['DMNS_CNTR_STG_KEY', 'CNTR_STG_CODE', 'CNTR_STG_DESP', 'CNTR_STG_DISP_SEQ_NUM']
        df_write = df_write.select(*[col for col in _target_cols if col in df_write.columns])
        # Write to database table (Oracle, etc.) using write_table (supports smart repartition, batch size, empty-df skip)
        lib.write_table(df_write, conn_target, "DPA_DMNS_CNTR_STG", mode="append")

        logger.info("write_DPA_DMNS_CNTR_STG write completed")
        
        metrics.complete()
        logger.info("Mapping M_DPA_SUMMARIZE_DMNS_CNTR_STG completed: SUCCESS")
        return True
        
    except Exception as e:
        metrics.fail(e)
        logger.error(f"Mapping M_DPA_SUMMARIZE_DMNS_CNTR_STG FAILED: {e}", exc_info=True)
        return False


def main():
    """Standalone execution entry point."""
    lib.init_logger()
    logger = lib.get_logger()
    config = lib.load_config('env/config.yml')
    spark = lib.get_spark_session("M_DPA_SUMMARIZE_DMNS_CNTR_STG", config)
    ctx = lib.SparkContext(spark)
    metrics = lib.MappingMetrics("M_DPA_SUMMARIZE_DMNS_CNTR_STG")
    
    try:
        success = run_mapping(ctx, metrics)
        if success:
            lib._flush_pending_passwords()
        if not success:
            # Exit the JVM non-zero so YARN marks the application FAILED.
            # In client mode the AM lives in this JVM: a normal spark.stop() +
            # python exit code still reports SUCCEEDED (AM exits cleanly).
            spark.sparkContext._jvm.System.exit(1)
        return 0
    finally:
        spark.stop()


if __name__ == "__main__":
    # sys.exit propagates the failure exit code — without it the process exits 0
    # and YARN reports SUCCEEDED even when the mapping failed.
    import sys as _sys
    _sys.exit(main())