-- drop table airflow.bda_study_source_table purge';
--create table airflow.bda_study_source_table as
insert into airflow.bda_study_source_table
with seq as (
  select level as rn
  from dual
  connect by level <= 500000
),
base_rows as (
  select
    rn,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330), 'DAY') as disp_date,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 1, 'DAY') as issue_date,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 2, 'DAY') as dayend_date,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 3, 'DAY') as start_dtm,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 4, 'DAY') as end_dtm,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 5, 'DAY') as presc_start_dtm,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 6, 'DAY') as presc_end_dtm,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 7, 'DAY') as dos_dtm,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 8, 'DAY') as phs_txn_dtm,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 9, 'DAY') as filler_dtm9,
    to_timestamp('2017-03-06 08:00:00', 'yyyy-mm-dd hh24:mi:ss') + numtodsinterval(mod(rn, 3330) + 10, 'DAY') as snapshot_datetime,
    case
      when mod(rn, 5) = 0 then 'INST' || lpad(to_char(mod(rn, 500) + 1), 4, '0')
      else 'INST' || lpad(to_char(mod(rn, 250) + 1), 4, '0')
    end as phs_inst_cd,
    case
      when mod(rn, 7) = 0 then 'ORG' || lpad(to_char(mod(rn, 500) + 1), 4, '0')
      else null
    end as phs_inst_cd_org,
    case
      when mod(rn, 7) = 0 then 'PRESC' || lpad(to_char(mod(rn, 1200) + 1), 5, '0')
      else 'INST' || lpad(to_char(mod(rn, 250) + 1), 4, '0')
    end as presc_inst_cd_base,
    'DISP' || lpad(to_char(mod(rn, 1000) + 1), 5, '0') as disp_inst_id,
    'EIS' || lpad(to_char(mod(rn, 1500) + 1), 5, '0') as eis_inst_id,
    'T' || to_char(mod(rn, 6)) as phs_presc_type,
    'ITEM' || lpad(to_char(mod(rn, 40000) + 1), 6, '0') as item_cd,
    mod(rn, 99) + 1 as item_sub_id,
    'CAT' || to_char(mod(rn, 20)) as itemcat,
    'TYPE' || to_char(mod(rn, 15)) as itemtype,
    'DG' || to_char(mod(rn, 30)) as druggroup,
    'CG' || to_char(mod(rn, 25)) as comgroup,
    'CT' || to_char(mod(rn, 12)) as comtype,
    'P' || to_char(mod(rn, 9)) as bnfno_p,
    'S1' || to_char(mod(rn, 9)) as bnfno_s1,
    'S2' || to_char(mod(rn, 9)) as bnfno_s2,
    'S3' || to_char(mod(rn, 9)) as bnfno_s3,
    'WS' || to_char(mod(rn, 8)) as workstore,
    'PAT' || to_char(mod(rn, 5)) as phs_pat_type,
    'PCAT' || to_char(mod(rn, 7)) as phs_pat_cat,
    case when mod(rn, 11) = 0 then 'Y' else 'N' end as phs_dischg_ind,
    'PT' || to_char(mod(rn, 4)) as patient_type,
    'CASE' || to_char(mod(rn, 6)) as case_type,
    'CS' || lpad(to_char(mod(rn, 9000000) + 1), 7, '0') || substr(to_char(mod(rn, 9) + 1), 1, 1) as case_no,
    10000000 + mod(rn, 400000) as patient_id,
    'PSCORG' || to_char(mod(rn, 200)) as phs_spec_cd_org,
    'PSC' || to_char(mod(rn, 200)) as phs_spec_cd,
    'WARD' || to_char(mod(rn, 50)) as phs_ward_cd,
    'IPAS' || to_char(mod(rn, 40)) as ipas_spec_cd,
    'TL' || to_char(mod(rn, 60)) as treat_loc_cd,
    'D' || to_char(mod(rn, 20)) as dosage_cd,
    'F' || to_char(mod(rn, 20)) as freq_cd,
    'Frequency ' || to_char(mod(rn, 20)) as freq_desc,
    mod(rn, 30) + 1 as duration_day,
    mod(rn, 5000) + 1 as disp_qty,
    mod(rn, 5000) + 1 as disp_qty_abs,
    'DRUG' || to_char(mod(rn, 1000)) as mod_drug,
    'Drug display ' || to_char(rn) as drug_displayname,
    'FORM' || to_char(mod(rn, 20)) as mod_form,
    'Form desc ' || to_char(mod(rn, 20)) as mod_form_desc,
    'UNIT' || to_char(mod(rn, 15)) as mod_baseunit,
    'MO' || to_char(mod(rn, 30)) as mo_cd,
    'SRC' || to_char(mod(rn, 100)) as phs_src_id,
    round(mod(rn, 10000) / 10, 2) as unitprice_org,
    round(mod(rn, 10000) / 12, 2) as unitprice,
    round(mod(rn, 99) / 10, 2) as factor,
    'R' || to_char(mod(rn, 10)) as route,
    'Route ' || to_char(mod(rn, 10)) as route_desc,
    round(mod(rn, 12000) / 11, 2) as itemcost_org,
    round(mod(rn, 12000) / 13, 2) as itemcost,
    'Q' || to_char(mod(rn, 60)) as queuing_time,
    case when mod(rn, 2) = 0 then 'Y' else 'N' end as queuing_time_ind,
    case when mod(rn, 3) = 0 then 'Y' else 'N' end as refill_ind,
    'H' || to_char(mod(rn, 70)) as refill_hosp_cd,
    'REF' || lpad(to_char(mod(rn, 900000) + 1), 6, '0') as refill_1st_ord_no,
    mod(rn, 9) + 1 as refill_split_no,
    100000000 + mod(rn, 400000) as moe_ref_no,
    'CMS' || lpad(to_char(mod(rn, 50000) + 1), 6, '0') as cms_item_no,
    mod(rn, 800000) + 1 as phs_item_seq,
    'REG' || to_char(mod(rn, 10)) as regimen_type,
    case when mod(rn, 2) = 0 then 'Y' else 'N' end as moe_order_ind,
    case when mod(rn, 4) = 0 then 'Y' else 'N' end as multi_dose_ind,
    case when mod(rn, 5) = 0 then 'Y' else 'N' end as src_multi_dose_ind,
    case when mod(rn, 6) = 0 then 'Y' else 'N' end as src_split_ind,
    mod(rn, 30) as src_split_duration,
    'ACT' || to_char(mod(rn, 9)) as phs_act_status_cd,
    'F1' || to_char(mod(rn, 9)) as phs_formul_status_cd_1,
    'F2' || to_char(mod(rn, 9)) as phs_formul_status_cd_2,
    round(mod(rn, 1000) / 10, 2) as dosage_value,
    'DDU' || to_char(mod(rn, 10)) as disp_dos_unit,
    'DF' || to_char(mod(rn, 7)) as daily_freq_cd,
    'Daily ' || to_char(mod(rn, 7)) as daily_freq_input,
    'SF' || to_char(mod(rn, 7)) as supp_freq_cd,
    'Supp1 ' || to_char(mod(rn, 7)) as supp_freq_input_1,
    'Supp2 ' || to_char(mod(rn, 7)) as supp_freq_input_2,
    to_char(mod(rn, 7) + 1) as day_of_week,
    'AT' || to_char(mod(rn, 24)) as admin_time_cd,
    'Admin ' || to_char(mod(rn, 24)) as admin_time_desc,
    'SITE' || to_char(mod(rn, 15)) as site_cd,
    'Site ' || to_char(mod(rn, 15)) as site_desc,
    'Supp site ' || to_char(mod(rn, 15)) as supp_site_desc,
    'DU' || to_char(mod(rn, 10)) as duration_unit_cd,
    mod(rn, 3330) + 3 as presc_duration_day,
    mod(rn, 500) + 1 as mo_presc_qty,
    'U' || to_char(mod(rn, 8)) as mo_presc_unit,
    round(mod(rn, 1000) / 3, 2) as total_dosage_value,
    round(mod(rn, 1000) / 4, 2) as calculate_qty,
    round(mod(rn, 1000) / 5, 2) as adjust_qty,
    'F' || to_char(mod(rn, 6)) as form_verb,
    'Volume ' || to_char(mod(rn, 10)) as vol_desc,
    mod(rn, 48) + 1 as exact_duration,
    case when mod(rn, 3) = 0 then '0' when mod(rn, 3) = 1 then '1' else '2' end as tran_type,
    case when mod(rn, 4) = 0 then 'Y' else 'N' end as valid_case,
    case when mod(rn, 17) = 0 then 'Y' else 'N' end as drug_duplicate_ind,
    'CC' || to_char(mod(rn, 100)) as costcentre,
    'TK' || to_char(mod(rn, 10000)) as ticknum,
    'MP' || to_char(mod(rn, 150)) as moe_pat_inst_cd,
    case when mod(rn, 2) = 0 then 'Y' else 'N' end as sfi_ind,
    'MS' || to_char(mod(rn, 1000)) as new_mod_strength,
    'SRC' || to_char(mod(rn, 20)) as source_ind,
    'ADI' || to_char(mod(rn, 300)) as act_disp_inst_id,
    mod(rn, 9000) + 1 as filler_id2,
    100000000 + mod(rn, 500000) as filler_id3,
    mod(rn, 2000) + 1 as filler_id4,
    'F5' || to_char(mod(rn, 500)) as filler5,
    'PAY' || to_char(mod(rn, 50)) as pay_cd,
    'F7' || to_char(mod(rn, 500)) as filler7,
    'F10' || to_char(mod(rn, 500)) as filler10,
    'F11' || to_char(mod(rn, 500)) as filler11,
    case when mod(rn, 2) = 0 then 'I' else 'U' end as action_type
  from seq
)
select
  base_rows.*,
  to_number(to_char(disp_date, 'yyyymmdd')) as disp_date_id,
  cast(100000000 + rn as number(12)) as presc_no,
  rn as item_no,
  case
    when phs_inst_cd_org is not null and phs_inst_cd_org <> presc_inst_cd_base then phs_inst_cd_org
    else presc_inst_cd_base
  end as presc_inst_cd,
  to_number(to_char(issue_date, 'yyyymmdd')) as issue_date_id,
  to_number(to_char(dayend_date, 'yyyymmdd')) as dayend_date_id,
  to_number(to_char(disp_date, 'yyyymm')) as disp_month_id
from base_rows
;

select count(*) as row_count from airflow.bda_study_source_table;
